import ecstasy.collections.HashSet;
import ecstasy.maps.ListMap;

import FieldDescriptor.Label;

/**
 * Generates Ecstasy source files from parsed `.proto` file descriptors.
 *
 * Produces one `.x` file per top-level message, enum, or service. Nested messages and enums are
 * emitted as inner declarations within their enclosing message class.
 *
 * Generated message classes extend [AbstractMessage] and use the `Maybe*` union types from the
 * `protobuf` module for field presence tracking.
 */
class ProtoCodeGen {

    /**
     * Ecstasy keywords that must be escaped when used as field names.
     */
    static String[] Keywords = [
        "abstract", "annotation", "assert", "break", "case", "class", "conditional",
        "const", "construct", "continue", "default", "do", "else", "enum", "extends",
        "finally", "for", "function", "if", "immutable", "implements", "import",
        "incorporates", "interface", "is", "mixin", "module", "new", "package",
        "private", "protected", "public", "return", "service", "static", "switch",
        "this", "throw", "try", "typedef", "using", "val", "var", "void", "while",
    ];

    /**
     * Set of known enum type names collected during generation, used to distinguish
     * enum references from message references (the parser treats both as TypeMessage).
     */
    private Set<String> enumNames = new HashSet();

    // ----- public interface -----------------------------------------------------------------------

    /**
     * Generate Ecstasy source files from a parsed proto file descriptor.
     *
     * @param file  the parsed FileDescriptor
     *
     * @return a map from file name (e.g. `"Person.x"`) to source text
     */
    Map<String, String> generate(FileDescriptor file) {
        enumNames = collectEnumNames(file);
        ListMap<String, String> result = new ListMap();

        for (EnumDescriptor e : file.enums) {
            result.put($"{e.name}.x", generateTopLevelEnum(e, file));
        }

        for (MessageDescriptor msg : file.messages) {
            result.put($"{msg.name}.x", generateTopLevelMessage(msg, file));
        }

        for (ServiceDescriptor svc : file.services) {
            result.put($"{svc.name}.x", generateTopLevelService(svc, file));
        }

        return result.freeze(inPlace=True);
    }

    // ----- top-level generators ------------------------------------------------------------------

    /**
     * Generate a top-level enum file.
     */
    private String generateTopLevelEnum(EnumDescriptor e, FileDescriptor file) {
        StringBuffer buf = new StringBuffer();
        $"import protobuf.ProtoEnum;\n\n".appendTo(buf);
        generateEnum(buf, e, file, 0);
        return buf.toString();
    }

    /**
     * Generate a top-level message file.
     */
    private String generateTopLevelMessage(MessageDescriptor msg, FileDescriptor file) {
        StringBuffer buf = new StringBuffer();

        // collect imports
        Array<String> imports = collectImports(msg);
        for (String imp : imports) {
            $"import {imp};\n".appendTo(buf);
        }
        if (!imports.empty) {
            buf.add('\n');
        }

        generateMessage(buf, msg, file, 0, False);
        return buf.toString();
    }

    /**
     * Generate a top-level service interface file.
     */
    private String generateTopLevelService(ServiceDescriptor svc, FileDescriptor file) {
        StringBuffer buf = new StringBuffer();
        generateService(buf, svc, file, 0);
        return buf.toString();
    }

    // ----- enum generation ------------------------------------------------------------------------

    /**
     * Generate an enum declaration.
     */
    private void generateEnum(StringBuffer buf, EnumDescriptor e, FileDescriptor file, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);

        $|{pad}/**
         |{pad} * This enum has been generated by the Ecstasy protoc plugin from the message type
         |{pad} * {e.name} defined in the proto file {file.name}
         |{pad} */
         |{pad}enum {e.name}
         |{pad}        implements ProtoEnum \{
         |
         .appendTo(buf);

        // enum values
        for (Int i = 0; i < e.values.size; i++) {
            EnumValueDescriptor v = e.values[i];
            $|{pad1}{toPascalCase(v.name)}({v.number})
             .appendTo(buf);
            buf.add(i < e.values.size - 1 ? ',' : ';');
            buf.add('\n');
        }

        $|
         |{pad1}construct(Int protoValue) \{
         |{pad1}    this.protoValue = protoValue;
         |{pad1}}
         |
         |{pad1}@Override
         |{pad1}Int protoValue;
         |{pad}}
         .appendTo(buf);
    }

    // ----- message generation ---------------------------------------------------------------------

    /**
     * Generate a message class declaration.
     *
     * @param buf      the output buffer
     * @param msg      the message descriptor
     * @param file     the parent proto file descriptor
     * @param indent   the indentation level
     * @param nested   True if this is a nested (inner static) class
     */
    private void generateMessage(StringBuffer buf, MessageDescriptor msg, FileDescriptor file,
                                 Int indent, Boolean nested) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);

        // class declaration
        String classKind = nested ? "static class" : "class";
        $|{pad}/**
         |{pad} * This class has been generated by the Ecstasy protoc plugin from the message type
         |{pad} * {msg.name} defined in the proto file {file.name}
         |{pad} */
         |{pad}{classKind} {msg.name}
         |{pad}        extends AbstractMessage \{
         |
         .appendTo(buf);

        // collect non-oneof fields and oneof descriptors
        Array<FieldDescriptor> regularFields = new Array();
        Array<FieldDescriptor> oneofFields   = new Array();
        for (FieldDescriptor field : msg.fields) {
            if (field.oneofIndex >= 0) {
                oneofFields.add(field);
            } else {
                regularFields.add(field);
            }
        }

        // inline typedefs for message/enum references
        generateTypedefs(buf, msg, indent + 1);

        // default constructor with field parameters
        generateConstructor(buf, regularFields, msg.oneofs, indent + 1);

        // copy constructor
        generateCopyConstructor(buf, msg, regularFields, indent + 1);
        buf.add('\n');

        // field declarations
        generateFieldDeclarations(buf, regularFields, msg.oneofs, indent + 1);
        buf.add('\n');

        // field accessors
        generateFieldAccessors(buf, regularFields, indent + 1);

        // oneof accessors
        if (!msg.oneofs.empty) {
            $"{pad1}{separator("oneof accessors", indent + 1)}\n\n".appendTo(buf);
            for (Int oi = 0; oi < msg.oneofs.size; oi++) {
                generateOneofAccessors(buf, msg.oneofs[oi], oneofFields, oi, indent + 1);
            }
        }

        // nested enums
        for (EnumDescriptor e : msg.enums) {
            $"{pad1}{separator($"enum {e.name}", indent + 1)}\n\n".appendTo(buf);
            generateEnum(buf, e, file, indent + 1);
            buf.add('\n');
        }

        // nested messages
        for (MessageDescriptor nested2 : msg.nestedMessages) {
            $"{pad1}{separator($"message {nested2.name}", indent + 1)}\n\n".appendTo(buf);
            generateMessage(buf, nested2, file, indent + 1, True);
            buf.add('\n');
        }

        // serialization section
        $"{pad1}{separator("serialization", indent + 1)}\n\n".appendTo(buf);

        // parseField
        generateParseField(buf, msg, regularFields, oneofFields, indent + 1);
        buf.add('\n');

        // writeKnownFields
        generateWriteKnownFields(buf, msg, regularFields, oneofFields, indent + 1);
        buf.add('\n');

        // knownFieldsSize
        generateKnownFieldsSize(buf, msg, regularFields, oneofFields, indent + 1);
        buf.add('\n');

        // freeze
        generateFreeze(buf, msg, regularFields, indent + 1);

        $"{pad}}\n".appendTo(buf);
    }

    // ----- typedef generation ---------------------------------------------------------------------

    /**
     * Generate inline typedefs for message and enum field references.
     */
    private void generateTypedefs(StringBuffer buf, MessageDescriptor msg, Int indent) {
        String  pad     = spaces(indent);
        Boolean emitted = False;

        // collect unique type names that need Maybe typedefs
        Array<String> seen = new Array();
        for (FieldDescriptor field : msg.fields) {
            if (field.oneofIndex >= 0) {
                continue;  // oneof fields use Oneof class, not Maybe types
            }
            if (field.label == Repeated) {
                continue;  // repeated fields use arrays, not Maybe types
            }
            if (field.isMapField) {
                continue;
            }
            String tn = field.typeName;
            if (tn.size > 0 && !seen.contains(tn)) {
                seen.add(tn);
                $"{pad}typedef Presence | {tn} as Maybe{sanitizeTypedefName(tn)};\n".appendTo(buf);
                emitted = True;
            }
        }
        if (emitted) {
            buf.add('\n');
        }
    }

    // ----- field declaration generation ------------------------------------------------------------

    /**
     * Generate field declarations for regular (non-oneof) fields and oneof instances.
     */
    private void generateFieldDeclarations(StringBuffer buf,
                                           Array<FieldDescriptor> regularFields,
                                           OneofDescriptor[] oneofs, Int indent) {
        String pad = spaces(indent);

        for (FieldDescriptor field : regularFields) {
            String ftype = fieldTypeName(field);
            String fname = fieldName(field.name);
            String fdef  = fieldDefault(field);
            $"{pad}{ftype} {fname} = {fdef};\n".appendTo(buf);
        }

        for (OneofDescriptor oneof : oneofs) {
            $"{pad}Oneof {fieldName(oneof.name)} = new Oneof();\n".appendTo(buf);
        }
    }

    // ----- field accessor generation -----------------------------------------------------------------

    /**
     * Generate conditional accessor methods for scalar, message, and enum fields.
     */
    private void generateFieldAccessors(StringBuffer buf, Array<FieldDescriptor> regularFields,
                                        Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);

        for (FieldDescriptor field : regularFields) {
            if (field.label == Repeated || field.isMapField) {
                continue;
            }
            String fname     = fieldName(field.name);
            String pascName  = toPascalCase(field.name);
            String realType  = ecstasyScalarType(field);
            String maybeType = fieldTypeName(field);

            if (field.type == FieldType.TypeBool) {
                $|{pad}Boolean is{pascName}() \{
                 |{pad1}{maybeType} {fname} = this.{fname};
                 |{pad1}if ({fname}.is(Boolean)) \{
                 |{pad2}return {fname};
                 |{pad1}}
                 |{pad1}return False;
                 |{pad}}
                 |
                 .appendTo(buf);
            } else {
                $|{pad}conditional {realType} has{pascName}() \{
                 |{pad1}{maybeType} {fname} = this.{fname};
                 |{pad1}if ({fname}.is({realType})) \{
                 |{pad2}return True, {fname};
                 |{pad1}}
                 |{pad1}return False;
                 |{pad}}
                 |
                 .appendTo(buf);
            }
        }
    }

    // ----- constructor generation -------------------------------------------------------------------

    /**
     * Generate the default constructor with field parameters.
     */
    private void generateConstructor(StringBuffer buf, Array<FieldDescriptor> regularFields,
                                     OneofDescriptor[] oneofs, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);

        $"{pad}construct(".appendTo(buf);

        Boolean first = True;
        for (FieldDescriptor field : regularFields) {
            if (first) {
                first = False;
            } else {
                ",".appendTo(buf);
            }
            String ftype = fieldTypeName(field);
            String fname = fieldName(field.name);
            String fdef  = constructorDefault(field);
            $"\n{pad1}{pad}{ftype} {fname} = {fdef}".appendTo(buf);
        }

        $") \{\n{pad1}construct AbstractMessage();\n".appendTo(buf);

        for (FieldDescriptor field : regularFields) {
            String fname = fieldName(field.name);
            $"{pad1}this.{fname} = {fname};\n".appendTo(buf);
        }

        $"{pad}}\n\n".appendTo(buf);
    }

    /**
     * @return the default value literal for a constructor parameter
     */
    private String constructorDefault(FieldDescriptor field) {
        if (field.isMapField) {
            return "Map:[]";
        }
        if (field.label == Repeated) {
            return "[]";
        }
        return "Unset";
    }

    // ----- copy constructor generation ------------------------------------------------------------

    /**
     * Generate the Duplicable copy constructor.
     */
    private void generateCopyConstructor(StringBuffer buf, MessageDescriptor msg,
                                         Array<FieldDescriptor> regularFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);

        $|{pad}@Override
         |{pad}construct({msg.name} other) \{
         |{pad1}construct AbstractMessage(other);
         .appendTo(buf);

        for (FieldDescriptor field : regularFields) {
            String fname = fieldName(field.name);
            if (field.isMapField) {
                $|
                 |{pad1}if (other.{fname}.is(immutable)) \{
                 |{pad2}{fname} = other.{fname};
                 |{pad1}} else \{
                 |{pad2}{fname} = new ListMap(other.{fname});
                 |{pad1}}
                 .appendTo(buf);
            } else if (field.label == Repeated) {
                $"\n{pad1}{fname} = other.{fname}.duplicate();".appendTo(buf);
            } else {
                $"\n{pad1}{fname} = other.{fname};".appendTo(buf);
            }
        }

        for (OneofDescriptor oneof : msg.oneofs) {
            String oname = fieldName(oneof.name);
            $"\n{pad1}{oname} = other.{oname}.duplicate();".appendTo(buf);
        }

        $"\n{pad}}\n".appendTo(buf);
    }

    // ----- oneof accessor generation --------------------------------------------------------------

    /**
     * Generate typed getters and setters for oneof fields.
     */
    private void generateOneofAccessors(StringBuffer buf, OneofDescriptor oneof,
                                        Array<FieldDescriptor> oneofFields, Int oneofIndex,
                                        Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);
        String oname = fieldName(oneof.name);

        for (FieldDescriptor field : oneofFields) {
            if (field.oneofIndex != oneofIndex) {
                continue;
            }
            String fname    = toPascalCase(field.name);
            String ecType   = ecstasyScalarType(field);
            Int    fieldNum = field.number;

            // getter
            $|{pad}conditional {ecType} get{fname}() \{
             |{pad1}if (Object v := {oname}.get({fieldNum})) \{
             |{pad2}return True, v.as({ecType});
             |{pad1}}
             |{pad1}return False;
             |{pad}}
             |
             .appendTo(buf);

            // setter
            $|{pad}void set{fname}({ecType} value) \{
             |{pad1}this.{oname}.set({fieldNum}, value);
             |{pad}}
             |
             .appendTo(buf);
        }
    }

    // ----- parseField generation ------------------------------------------------------------------

    /**
     * Generate the parseField override.
     */
    private void generateParseField(StringBuffer buf, MessageDescriptor msg,
                                    Array<FieldDescriptor> regularFields,
                                    Array<FieldDescriptor> oneofFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);

        $|{pad}@Override
         |{pad}Boolean parseField(CodedInput input, Int tag) \{
         .appendTo(buf);

        if (regularFields.empty && oneofFields.empty) {
            $|
             |{pad1}return False;
             .appendTo(buf);
        } else {
            $|
             |{pad1}switch (WireType.getFieldNumber(tag)) \{
             .appendTo(buf);

            // regular fields
            for (FieldDescriptor field : regularFields) {
                String fname = fieldName(field.name);
                $"\n{pad1}case {field.number}:\n".appendTo(buf);

                if (field.isMapField) {
                    generateParseMapField(buf, field, fname, indent + 2);
                } else if (field.label == Repeated) {
                    generateParseRepeatedField(buf, field, fname, indent + 2);
                } else if (isEnumRef(field)) {
                    generateParseEnumField(buf, field, fname, indent + 2);
                } else if (field.type == TypeMessage) {
                    generateParseMessageField(buf, field, fname, indent + 2);
                } else {
                    $"{pad2}{fname} = input.{readMethod(field)};\n".appendTo(buf);
                }
                $"{pad2}return True;\n".appendTo(buf);
            }

            // oneof fields
            for (FieldDescriptor field : oneofFields) {
                String oname = fieldName(msg.oneofs[field.oneofIndex].name);
                $"\n{pad1}case {field.number}:\n".appendTo(buf);
                if (isEnumRef(field)) {
                    String tn   = field.typeName;
                    String pad3 = spaces(indent + 3);
                    $|{pad2}if ({tn} v := ProtoEnum.byProtoValue({tn}.values, input.readEnum())) \{
                     |{pad3}{oname}.set({field.number}, v);
                     |{pad2}}
                     .appendTo(buf);
                } else {
                    $"{pad2}{oname}.set({field.number}, input.{readMethod(field)});\n".appendTo(buf);
                }
                $"{pad2}return True;\n".appendTo(buf);
            }

            $|{pad1}}
             |{pad1}return False;
             .appendTo(buf);
        }

        $"\n{pad}}\n".appendTo(buf);
    }

    /**
     * Generate parse logic for a repeated field.
     */
    private void generateParseRepeatedField(StringBuffer buf, FieldDescriptor field,
                                            String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);
        String pad3 = spaces(indent + 3);

        // ensure the array is mutable (may be immutable from default parameter)
        $|{pad}if ({fname}.is(immutable)) \{
         |{pad1}{fname} = new Array({fname});
         |{pad}}
         |
         .appendTo(buf);

        if (isEnumRef(field)) {
            // repeated enum: read varints and convert to enum values
            String tn = field.typeName;
            $|{pad}if (WireType.getWireType(tag) == WireType.LEN) \{
             |{pad1}for (Int32 raw : input.readPackedInt32s()) \{
             |{pad2}if ({tn} v := ProtoEnum.byProtoValue({tn}.values, raw)) \{
             |{pad3}{fname}.add(v);
             |{pad2}}
             |{pad1}}
             |{pad}} else \{
             |{pad1}if ({tn} v := ProtoEnum.byProtoValue({tn}.values, input.readEnum())) \{
             |{pad2}{fname}.add(v);
             |{pad1}}
             |{pad}}
             .appendTo(buf);
        } else if (field.type.packable) {
            // handle both packed (LEN) and unpacked wire types
            $|{pad}if (WireType.getWireType(tag) == WireType.LEN) \{
             |{pad1}{fname}.addAll(input.{readPackedMethod(field)});
             |{pad}} else \{
             |{pad1}{fname}.add(input.{readMethod(field)});
             |{pad}}
             .appendTo(buf);
        } else if (field.type == TypeMessage) {
            // repeated message
            String tn = field.typeName;
            $|{pad}{tn} elem = new {tn}();
             |{pad}Int len = input.readVarint().toInt();
             |{pad}Int oldLimit = input.pushLimit(len);
             |{pad}elem.mergeFrom(input);
             |{pad}input.popLimit(oldLimit);
             |{pad}{fname}.add(elem);
             |
             .appendTo(buf);
        } else {
            // repeated non-packable scalar (string, bytes)
            $"{pad}{fname}.add(input.{readMethod(field)});\n".appendTo(buf);
        }
    }

    /**
     * Generate parse logic for a singular message field.
     */
    private void generateParseMessageField(StringBuffer buf, FieldDescriptor field,
                                           String fname, Int indent) {
        String pad = spaces(indent);
        String tn  = field.typeName;
        $|{pad}{tn} msg = new {tn}();
         |{pad}Int len = input.readVarint().toInt();
         |{pad}Int oldLimit = input.pushLimit(len);
         |{pad}msg.mergeFrom(input);
         |{pad}input.popLimit(oldLimit);
         |{pad}{fname} = msg;
         |{pad}
         .appendTo(buf);
    }

    /**
     * Generate parse logic for a singular enum field.
     */
    private void generateParseEnumField(StringBuffer buf, FieldDescriptor field,
                                        String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String tn   = field.typeName;
        $|{pad}if ({tn} v := ProtoEnum.byProtoValue({tn}.values, input.readEnum())) \{
         |{pad1}{fname} = v;
         |{pad}}
         |
         .appendTo(buf);
    }

    /**
     * Generate parse logic for a map field.
     */
    private void generateParseMapField(StringBuffer buf, FieldDescriptor field,
                                       String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String readMapMethod = mapReadMethod(field);
        if (readMapMethod.size > 0) {
            String kt = ecstasyType(field.mapKeyType);
            String vt = ecstasyType(field.mapValueType);

            // ensure the map is mutable (may be immutable from default parameter)
            $|{pad}if ({fname}.is(immutable)) \{
             |{pad1}{fname} = new ListMap({fname});
             |{pad}}
             |{pad}({kt} k, {vt} v) = input.{readMapMethod};
             |{pad}{fname}.put(k, v);
             |
             .appendTo(buf);
        } else {
            $"{pad}// TODO: unsupported map type combination\n".appendTo(buf);
        }
    }

    // ----- writeKnownFields generation ------------------------------------------------------------

    /**
     * Generate the writeKnownFields override.
     */
    private void generateWriteKnownFields(StringBuffer buf, MessageDescriptor msg,
                                          Array<FieldDescriptor> regularFields,
                                          Array<FieldDescriptor> oneofFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);

        $|{pad}@Override
         |{pad}void writeKnownFields(CodedOutput out) \{
         .appendTo(buf);

        // regular fields
        for (FieldDescriptor field : regularFields) {
            String fname = fieldName(field.name);
            Int    fn    = field.number;

            if (field.isMapField) {
                generateWriteMapField(buf, field, fname, indent + 1);
            } else if (field.label == Repeated) {
                generateWriteRepeatedField(buf, field, fname, indent + 1);
            } else if (isEnumRef(field)) {
                String ecType = field.typeName;
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}out.writeEnum({fn}, {fname});
                 |{pad1}}
                 .appendTo(buf);
            } else if (field.type == TypeMessage) {
                String ecType = field.typeName;
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}out.writeMessage({fn}, {fname});
                 |{pad1}}
                 .appendTo(buf);
            } else {
                String ecType = ecstasyScalarType(field);
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}out.{writeMethod(field)}({fn}, {fname});
                 |{pad1}}
                 .appendTo(buf);
            }
        }

        // oneof fields
        for (OneofDescriptor oneof : msg.oneofs) {
            generateWriteOneof(buf, oneof, oneofFields, indent + 1);
        }

        $"\n{pad}}\n".appendTo(buf);
    }

    /**
     * Generate write logic for a repeated field.
     */
    private void generateWriteRepeatedField(StringBuffer buf, FieldDescriptor field,
                                            String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        Int    fn   = field.number;

        if (isEnumRef(field)) {
            // repeated enum: write each value individually using writeEnum
            String tn = field.typeName;
            $|
             |{pad}for ({tn} v : {fname}) \{
             |{pad1}out.writeEnum({fn}, v);
             |{pad}}
             .appendTo(buf);
        } else if (field.type.packable) {
            $|
             |{pad}if (!{fname}.empty) \{
             |{pad1}out.{writePackedMethod(field)}({fn}, {fname});
             |{pad}}
             .appendTo(buf);
        } else {
            String ecType = field.type == TypeMessage ? field.typeName : ecstasyScalarType(field);
            String writeCall = field.type == TypeMessage
                    ? $"out.writeMessage({fn}, v)"
                    : $"out.{writeMethod(field)}({fn}, v)";
            $|
             |{pad}for ({ecType} v : {fname}) \{
             |{pad1}{writeCall};
             |{pad}}
             .appendTo(buf);
        }
    }

    /**
     * Generate write logic for a map field.
     */
    private void generateWriteMapField(StringBuffer buf, FieldDescriptor field,
                                       String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String writeMapMethod = mapWriteMethod(field);
        if (writeMapMethod.size > 0) {
            String kt = ecstasyType(field.mapKeyType);
            String vt = ecstasyType(field.mapValueType);
            Int    fn = field.number;
            $|
             |{pad}for (({kt} k, {vt} v) : {fname}) \{
             |{pad1}out.{writeMapMethod}({fn}, k, v);
             |{pad}}
             .appendTo(buf);
        }
    }

    /**
     * Generate write logic for a oneof group.
     */
    private void generateWriteOneof(StringBuffer buf, OneofDescriptor oneof,
                                    Array<FieldDescriptor> oneofFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);
        String oname = fieldName(oneof.name);

        $"\n{pad}switch ({oname}.activeFieldNumber) \{\n".appendTo(buf);

        for (FieldDescriptor field : oneofFields) {
            if (!Oneof.contains(field.number, oneof.fieldNumbers)) {
                continue;
            }
            String fname  = toPascalCase(field.name);
            String ecType = ecstasyScalarType(field);
            String fvar   = fieldName(field.name);
            Int    fn     = field.number;

            $|{pad}case {fn}:
             |{pad1}if ({ecType} {fvar} := get{fname}()) \{
             |{pad2}out.{writeMethod(field)}({fn}, {fvar});
             |{pad1}}
             |{pad1}break;
             .appendTo(buf);
        }

        $"\n{pad}}\n".appendTo(buf);
    }

    // ----- knownFieldsSize generation -------------------------------------------------------------

    /**
     * Generate the knownFieldsSize override.
     */
    private void generateKnownFieldsSize(StringBuffer buf, MessageDescriptor msg,
                                         Array<FieldDescriptor> regularFields,
                                         Array<FieldDescriptor> oneofFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);

        $|{pad}@Override
         |{pad}Int knownFieldsSize() \{
         |{pad1}Int size = 0;
         .appendTo(buf);

        // regular fields
        for (FieldDescriptor field : regularFields) {
            String fname = fieldName(field.name);

            if (field.isMapField) {
                generateSizeMapField(buf, field, fname, indent + 1);
            } else if (field.label == Repeated) {
                generateSizeRepeatedField(buf, field, fname, indent + 1);
            } else if (isEnumRef(field)) {
                String ecType = field.typeName;
                Int    fn     = field.number;
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}size += CodedOutput.computeEnumSize({fn}, {fname});
                 |{pad1}}
                 .appendTo(buf);
            } else if (field.type == TypeMessage) {
                String ecType = field.typeName;
                Int    fn     = field.number;
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}size += CodedOutput.computeMessageSize({fn}, {fname});
                 |{pad1}}
                 .appendTo(buf);
            } else {
                String ecType = ecstasyScalarType(field);
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({ecType})) \{
                 |{pad2}size += CodedOutput.{computeSizeMethod(field)};
                 |{pad1}}
                 .appendTo(buf);
            }
        }

        // oneof fields
        for (OneofDescriptor oneof : msg.oneofs) {
            generateSizeOneof(buf, oneof, oneofFields, indent + 1);
        }

        $|
         |{pad1}return size;
         |{pad}}
         |
         .appendTo(buf);
    }

    /**
     * Generate size logic for a repeated field.
     */
    private void generateSizeRepeatedField(StringBuffer buf, FieldDescriptor field,
                                           String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        Int    fn   = field.number;

        if (isEnumRef(field)) {
            // repeated enum: compute size for each element individually
            String tn = field.typeName;
            $|
             |{pad}for ({tn} v : {fname}) \{
             |{pad1}size += CodedOutput.computeEnumSize({fn}, v);
             |{pad}}
             .appendTo(buf);
        } else if (field.type.packable) {
            $|
             |{pad}if (!{fname}.empty) \{
             |{pad1}size += CodedOutput.{computePackedSizeMethod(field)};
             |{pad}}
             .appendTo(buf);
        } else {
            String ecType = field.type == TypeMessage ? field.typeName : ecstasyScalarType(field);
            String sizeCall = field.type == TypeMessage
                    ? $"CodedOutput.computeMessageSize({fn}, v)"
                    : $"CodedOutput.{computeSizeMethodForElement(field)}";
            $|
             |{pad}for ({ecType} v : {fname}) \{
             |{pad1}size += {sizeCall};
             |{pad}}
             .appendTo(buf);
        }
    }

    /**
     * Generate size logic for a map field.
     */
    private void generateSizeMapField(StringBuffer buf, FieldDescriptor field,
                                      String fname, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String computeMapMethod = mapComputeSizeMethod(field);
        if (computeMapMethod.size > 0) {
            String kt = ecstasyType(field.mapKeyType);
            String vt = ecstasyType(field.mapValueType);
            Int    fn = field.number;
            $|
             |{pad}for (({kt} k, {vt} v) : {fname}) \{
             |{pad1}size += CodedOutput.{computeMapMethod}({fn}, k, v);
             |{pad}}
             .appendTo(buf);
        }
    }

    /**
     * Generate size logic for a oneof group.
     */
    private void generateSizeOneof(StringBuffer buf, OneofDescriptor oneof,
                                   Array<FieldDescriptor> oneofFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);
        String oname = fieldName(oneof.name);

        $"\n{pad}switch ({oname}.activeFieldNumber) \{\n".appendTo(buf);

        for (FieldDescriptor field : oneofFields) {
            if (!Oneof.contains(field.number, oneof.fieldNumbers)) {
                continue;
            }
            String fname  = toPascalCase(field.name);
            String ecType = ecstasyScalarType(field);
            String fvar   = fieldName(field.name);
            Int    fn     = field.number;

            $|{pad}case {fn}:
             |{pad1}if ({ecType} {fvar} := get{fname}()) \{
             |{pad2}size += CodedOutput.{computeSizeMethodForOneof(field)};
             |{pad1}}
             |{pad1}break;
             .appendTo(buf);
        }

        $"\n{pad}}\n".appendTo(buf);
    }

    // ----- freeze generation ----------------------------------------------------------------------

    /**
     * Generate the freeze override.
     */
    private void generateFreeze(StringBuffer buf, MessageDescriptor msg,
                                Array<FieldDescriptor> regularFields, Int indent) {
        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);
        String pad2 = spaces(indent + 2);
        String pad3 = spaces(indent + 3);

        $|{pad}@Override
         |{pad}immutable {msg.name} freeze(Boolean inPlace = False) \{
         |{pad1}if (this.is(immutable {msg.name})) \{
         |{pad2}return this;
         |{pad1}}
         |{pad1}if (!inPlace) \{
         |{pad2}return new {msg.name}(this).freeze(True);
         |{pad1}}
         |{pad1}unknownFields.freeze(True);
         .appendTo(buf);

        // freeze mutable fields (arrays, maps, messages)
        for (FieldDescriptor field : regularFields) {
            String fname = fieldName(field.name);
            if (field.isMapField) {
                $|
                 |{pad1}Map {fname} = this.{fname};
                 |{pad1}if ({fname}.is(Freezable)) \{
                 |{pad2}{fname}.freeze(True);
                 |{pad1}} else \{
                 |{pad2}this.{fname} = new ListMap({fname}).freeze(True);
                 |{pad1}}
                 .appendTo(buf);
            } else if (field.label == Repeated) {
                $"\n{pad1}{fname}.freeze(True);".appendTo(buf);
            } else if (field.type == TypeMessage && !isEnumRef(field)) {
                String tn = field.typeName;
                $|
                 |{pad1}var {fname} = this.{fname};
                 |{pad1}if ({fname}.is({tn})) \{
                 |{pad2}{fname}.freeze(True);
                 |{pad1}}
                 .appendTo(buf);
            }
        }

        $|
         |{pad1}return this.makeImmutable();
         |{pad}}
         |
         .appendTo(buf);
    }

    // ----- service generation ---------------------------------------------------------------------

    /**
     * Generate a service interface.
     */
    private void generateService(StringBuffer buf, ServiceDescriptor svc, FileDescriptor file,
                                 Int indent) {

        String pad  = spaces(indent);
        String pad1 = spaces(indent + 1);

        $|{pad}/**
         |{pad} * This service has been generated by the Ecstasy protoc plugin from the message type
         |{pad} * {svc.name} defined in the proto file {file.name}
         |{pad} */
         |{pad}interface {svc.name} \{
         |
         .appendTo(buf);

        for (MethodDescriptor method : svc.methods) {
            buf.add('\n');
            String methodName = toCamelCase(method.name);

            if (method.clientStreaming || method.serverStreaming) {
                String clientStr = method.clientStreaming ? "stream " : "";
                String serverStr = method.serverStreaming ? "stream " : "";
                $|{pad1}// TODO: streaming RPC
                 |{pad1}// {method.name}({clientStr}{method.inputType}) returns ({serverStr}{method.outputType})
                 .appendTo(buf);
            } else {
                $"{pad1}{method.outputType} {methodName}({method.inputType} request);\n".appendTo(buf);
            }
        }

        $"{pad}}\n".appendTo(buf);
    }

    // ----- import collection ---------------------------------------------------------------------

    /**
     * Collect the import statements needed for a message.
     */
    private Array<String> collectImports(MessageDescriptor msg) {
        Array<String> imports = new Array();
        imports.add("protobuf.AbstractMessage");
        imports.add("protobuf.CodedInput");
        imports.add("protobuf.CodedOutput");
        imports.add("protobuf.WireType");

        HashSet<String> extras = new HashSet();
        collectImportsFromMessage(msg, extras);

        for (String imp : extras) {
            imports.add(imp);
        }

        return imports;
    }

    /**
     * Recursively scan a message and its nested messages for import requirements.
     */
    private void collectImportsFromMessage(MessageDescriptor msg, HashSet<String> imports) {
        if (msg.enums.size > 0) {
            imports.add("protobuf.ProtoEnum");
        }

        for (FieldDescriptor field : msg.fields) {
            if (field.isMapField) {
                imports.add("ecstasy.maps.ListMap");
                continue;
            }
            if (field.oneofIndex >= 0) {
                imports.add("protobuf.Oneof");
                continue;
            }
            if (isEnumRef(field)) {
                imports.add("protobuf.ProtoEnum");
            }
            if (field.label == Repeated) {
                continue;
            }
            // singular non-map, non-oneof field: uses a Maybe type or inline typedef
            if (field.type == TypeMessage || isEnumRef(field)) {
                imports.add("protobuf.Presence");
            } else {
                String mt = maybeType(field);
                if (mt != "Object") {
                    imports.add($"protobuf.{mt}");
                }
            }
        }

        for (MessageDescriptor nested : msg.nestedMessages) {
            collectImportsFromMessage(nested, imports);
        }
    }

    // ----- type mapping helpers -------------------------------------------------------------------

    /**
     * @return the Ecstasy type name for a field declaration (including Maybe wrappers)
     */
    private String fieldTypeName(FieldDescriptor field) {
        if (field.isMapField) {
            return $"Map<{ecstasyType(field.mapKeyType)}, {ecstasyType(field.mapValueType)}>";
        }
        if (field.label == Repeated) {
            if (field.type == TypeMessage) {
                return $"Array<{field.typeName}>";
            }
            return $"Array<{ecstasyScalarType(field)}>";
        }
        if (field.type == TypeMessage) {
            return $"Maybe{sanitizeTypedefName(field.typeName)}";
        }
        return maybeType(field);
    }

    /**
     * @return the default value literal for a field
     */
    private String fieldDefault(FieldDescriptor field) {
        return constructorDefault(field);
    }

    /**
     * @return the Maybe* type name for a scalar field
     */
    private String maybeType(FieldDescriptor field) {
        return switch (field.type) {
            case TypeInt32, TypeSint32, TypeSfixed32: "MaybeInt32";
            case TypeInt64, TypeSint64, TypeSfixed64: "MaybeInt64";
            case TypeUint32, TypeFixed32:             "MaybeUInt32";
            case TypeUint64, TypeFixed64:             "MaybeUInt64";
            case TypeBool:                            "MaybeBoolean";
            case TypeString:                          "MaybeString";
            case TypeBytes:                           "MaybeBytes";
            case TypeDouble:                          "MaybeFloat64";
            case TypeFloat:                           "MaybeFloat32";
            case TypeEnum:                            $"Maybe{sanitizeTypedefName(field.typeName)}";
            default:                                  "Object";
        };
    }

    /**
     * @return the raw Ecstasy type name for a scalar field type (no Maybe wrapper)
     */
    private String ecstasyScalarType(FieldDescriptor field) {
        if (field.type == TypeMessage) {
            return field.typeName;
        }
        if (field.type == TypeEnum) {
            return field.typeName;
        }
        return ecstasyType(field.type);
    }

    /**
     * @return the Ecstasy type name for a field type
     */
    private String ecstasyType(FieldType type) {
        return switch (type) {
            case TypeDouble:                          "Float64";
            case TypeFloat:                           "Float32";
            case TypeInt64, TypeSint64, TypeSfixed64: "Int64";
            case TypeUint64, TypeFixed64:             "UInt64";
            case TypeInt32, TypeSint32, TypeSfixed32: "Int32";
            case TypeUint32, TypeFixed32:             "UInt32";
            case TypeBool:                            "Boolean";
            case TypeString:                          "String";
            case TypeBytes:                           "Byte[]";
            default:                                  "Object";
        };
    }

    // ----- read/write method helpers --------------------------------------------------------------

    /**
     * @return the CodedInput read method call for a field (without "input." prefix)
     */
    private String readMethod(FieldDescriptor field) {
        return switch (field.type) {
            case TypeDouble:   "readDouble()";
            case TypeFloat:    "readFloat()";
            case TypeInt64:    "readInt64()";
            case TypeUint64:   "readUInt64()";
            case TypeInt32:    "readInt32()";
            case TypeFixed64:  "readFixed64()";
            case TypeFixed32:  "readFixed32()";
            case TypeBool:     "readBool()";
            case TypeString:   "readString()";
            case TypeBytes:    "readBytes()";
            case TypeUint32:   "readUInt32()";
            case TypeEnum:     "readEnum()";
            case TypeSfixed32: "readSFixed32()";
            case TypeSfixed64: "readSFixed64()";
            case TypeSint32:   "readSInt32()";
            case TypeSint64:   "readSInt64()";
            default:           "readVarint()";
        };
    }

    /**
     * @return the CodedInput packed read method call for a repeated field
     */
    private String readPackedMethod(FieldDescriptor field) {
        return switch (field.type) {
            case TypeDouble:                "readPackedDoubles()";
            case TypeFloat:                 "readPackedFloats()";
            case TypeInt64, TypeSint64:     "readPackedVarints()";
            case TypeUint64:                "readPackedUInt64s()";
            case TypeInt32, TypeSint32:     "readPackedInt32s()";
            case TypeFixed64, TypeSfixed64: "readPackedFixed64s()";
            case TypeFixed32, TypeSfixed32: "readPackedFixed32s()";
            case TypeBool:                  "readPackedBools()";
            case TypeUint32:                "readPackedInt32s()";
            case TypeEnum:                  "readPackedVarints()";
            default:                        "readPackedVarints()";
        };
    }

    /**
     * @return the CodedOutput write method name for a field (without "out." prefix)
     */
    private String writeMethod(FieldDescriptor field) {
        return switch (field.type) {
            case TypeDouble:   "writeDouble";
            case TypeFloat:    "writeFloat";
            case TypeInt64:    "writeInt64";
            case TypeUint64:   "writeUInt64";
            case TypeInt32:    "writeInt32";
            case TypeFixed64:  "writeFixed64";
            case TypeFixed32:  "writeFixed32";
            case TypeBool:     "writeBool";
            case TypeString:   "writeString";
            case TypeBytes:    "writeBytes";
            case TypeUint32:   "writeUInt32";
            case TypeEnum:     "writeEnum";
            case TypeSfixed32: "writeSFixed32";
            case TypeSfixed64: "writeSFixed64";
            case TypeSint32:   "writeSInt32";
            case TypeSint64:   "writeSInt64";
            default:           "writeVarint";
        };
    }

    /**
     * @return the CodedOutput packed write method name for a repeated field
     */
    private String writePackedMethod(FieldDescriptor field) {
        return switch (field.type) {
            case TypeDouble:                "writePackedDoubles";
            case TypeFloat:                 "writePackedFloats";
            case TypeInt64, TypeSint64:     "writePackedVarints";
            case TypeUint64:                "writePackedVarints";
            case TypeInt32, TypeSint32:     "writePackedVarints";
            case TypeFixed64, TypeSfixed64: "writePackedFixed64s";
            case TypeFixed32, TypeSfixed32: "writePackedFixed32s";
            case TypeBool:                  "writePackedBools";
            case TypeUint32:                "writePackedVarints";
            case TypeEnum:                  "writePackedVarints";
            default:                        "writePackedVarints";
        };
    }

    // ----- compute size helpers -------------------------------------------------------------------

    /**
     * @return the CodedOutput.compute*Size call for a singular field (using fname as the value)
     */
    private String computeSizeMethod(FieldDescriptor field) {
        String fn = field.number.toString();
        String fname = fieldName(field.name);
        return switch (field.type) {
            case TypeDouble:   $"computeFixed64Size({fn})";
            case TypeFloat:    $"computeFixed32Size({fn})";
            case TypeInt64:    $"computeInt64Size({fn}, {fname})";
            case TypeUint64:   $"computeUInt64Size({fn}, {fname})";
            case TypeInt32:    $"computeInt32Size({fn}, {fname})";
            case TypeFixed64:  $"computeFixed64Size({fn})";
            case TypeFixed32:  $"computeFixed32Size({fn})";
            case TypeBool:     $"computeBoolSize({fn})";
            case TypeString:   $"computeStringSize({fn}, {fname})";
            case TypeBytes:    $"computeBytesSize({fn}, {fname})";
            case TypeUint32:   $"computeUInt32Size({fn}, {fname})";
            case TypeEnum:     $"computeEnumSize({fn}, {fname})";
            case TypeSfixed32: $"computeFixed32Size({fn})";
            case TypeSfixed64: $"computeFixed64Size({fn})";
            case TypeSint32:   $"computeSInt32Size({fn}, {fname})";
            case TypeSint64:   $"computeSInt64Size({fn}, {fname})";
            default:           $"computeVarintSize({fname})";
        };
    }

    /**
     * @return the compute size call for a repeated element (uses "v" as variable name)
     */
    private String computeSizeMethodForElement(FieldDescriptor field) {
        String fn = field.number.toString();
        return switch (field.type) {
            case TypeString: $"computeStringSize({fn}, v)";
            case TypeBytes:  $"computeBytesSize({fn}, v)";
            default:         $"computeBytesSize({fn}, v)";
        };
    }

    /**
     * @return the compute packed size call for a repeated packable field
     */
    private String computePackedSizeMethod(FieldDescriptor field) {
        String fn = field.number.toString();
        String fname = fieldName(field.name);
        return switch (field.type) {
            case TypeDouble:                $"computePackedDoublesSize({fn}, {fname})";
            case TypeFloat:                 $"computePackedFloatsSize({fn}, {fname})";
            case TypeInt64, TypeSint64:     $"computePackedVarintsSize({fn}, {fname})";
            case TypeUint64:                $"computePackedVarintsSize({fn}, {fname})";
            case TypeInt32, TypeSint32:     $"computePackedVarintsSize({fn}, {fname})";
            case TypeFixed64, TypeSfixed64: $"computePackedFixed64sSize({fn}, {fname})";
            case TypeFixed32, TypeSfixed32: $"computePackedFixed32sSize({fn}, {fname})";
            case TypeBool:                  $"computePackedBoolsSize({fn}, {fname})";
            case TypeUint32:                $"computePackedVarintsSize({fn}, {fname})";
            case TypeEnum:                  $"computePackedVarintsSize({fn}, {fname})";
            default:                        $"computePackedVarintsSize({fn}, {fname})";
        };
    }

    /**
     * @return the compute size call for a oneof field (uses the local variable name)
     */
    private String computeSizeMethodForOneof(FieldDescriptor field) {
        String fn = field.number.toString();
        String fname = fieldName(field.name);
        return switch (field.type) {
            case TypeDouble:   $"computeFixed64Size({fn})";
            case TypeFloat:    $"computeFixed32Size({fn})";
            case TypeInt64:    $"computeInt64Size({fn}, {fname})";
            case TypeUint64:   $"computeUInt64Size({fn}, {fname})";
            case TypeInt32:    $"computeInt32Size({fn}, {fname})";
            case TypeFixed64:  $"computeFixed64Size({fn})";
            case TypeFixed32:  $"computeFixed32Size({fn})";
            case TypeBool:     $"computeBoolSize({fn})";
            case TypeString:   $"computeStringSize({fn}, {fname})";
            case TypeBytes:    $"computeBytesSize({fn}, {fname})";
            case TypeUint32:   $"computeUInt32Size({fn}, {fname})";
            case TypeEnum:     $"computeEnumSize({fn}, {fname})";
            case TypeSfixed32: $"computeFixed32Size({fn})";
            case TypeSfixed64: $"computeFixed64Size({fn})";
            case TypeSint32:   $"computeSInt32Size({fn}, {fname})";
            case TypeSint64:   $"computeSInt64Size({fn}, {fname})";
            default:           $"computeVarintSize({fname})";
        };
    }

    // ----- map method helpers --------------------------------------------------------------------

    /**
     * @return the CodedInput read method for a map field, or "" if unsupported
     */
    private String mapReadMethod(FieldDescriptor field) {
        String key = field.mapKeyType.protoName;
        String val = field.mapValueType.protoName;
        return switch (key, val) {
            case ("string", "string"): "readMapStringString()";
            case ("string", "int32"):  "readMapStringInt32()";
            case ("string", "int64"):  "readMapStringInt64()";
            case ("string", "bytes"):  "readMapStringBytes()";
            case ("int32",  "string"): "readMapInt32String()";
            case ("int32",  "int32"):  "readMapInt32Int32()";
            case ("int64",  "string"): "readMapInt64String()";
            case ("int64",  "int64"):  "readMapInt64Int64()";
            case ("bool",   "string"): "readMapBoolString()";
            default: "";
        };
    }

    /**
     * @return the CodedOutput write method for a map field, or "" if unsupported
     */
    private String mapWriteMethod(FieldDescriptor field) {
        String key = field.mapKeyType.protoName;
        String val = field.mapValueType.protoName;
        return switch (key, val) {
            case ("string", "string"): "writeMapStringString";
            case ("string", "int32"):  "writeMapStringInt32";
            case ("string", "int64"):  "writeMapStringInt64";
            case ("string", "bytes"):  "writeMapStringBytes";
            case ("int32",  "string"): "writeMapInt32String";
            case ("int32",  "int32"):  "writeMapInt32Int32";
            case ("int64",  "string"): "writeMapInt64String";
            case ("int64",  "int64"):  "writeMapInt64Int64";
            case ("bool",   "string"): "writeMapBoolString";
            default: "";
        };
    }

    /**
     * @return the CodedOutput compute size method for a map field, or "" if unsupported
     */
    private String mapComputeSizeMethod(FieldDescriptor field) {
        String key = field.mapKeyType.protoName;
        String val = field.mapValueType.protoName;
        return switch (key, val) {
            case ("string", "string"): "computeMapStringStringSize";
            case ("string", "int32"):  "computeMapStringInt32Size";
            case ("string", "int64"):  "computeMapStringInt64Size";
            case ("string", "bytes"):  "computeMapStringBytesSize";
            case ("int32",  "string"): "computeMapInt32StringSize";
            case ("int32",  "int32"):  "computeMapInt32Int32Size";
            case ("int64",  "string"): "computeMapInt64StringSize";
            case ("int64",  "int64"):  "computeMapInt64Int64Size";
            case ("bool",   "string"): "computeMapBoolStringSize";
            default: "";
        };
    }

    // ----- enum resolution helpers ----------------------------------------------------------------

    /**
     * Collect all enum type names from the file (top-level and nested).
     */
    private Set<String> collectEnumNames(FileDescriptor file) {
        HashSet<String> names = new HashSet();
        for (EnumDescriptor e : file.enums) {
            names.add(e.name);
        }
        for (MessageDescriptor msg : file.messages) {
            collectEnumNamesFromMessage(msg, "", names);
        }
        return names;
    }

    /**
     * Recursively collect enum type names from a message and its nested types.
     * Adds both the simple name and the dot-qualified name so that references like
     * `VisibilityFeature.DefaultSymbolVisibility` are recognized as enum references.
     */
    private void collectEnumNamesFromMessage(MessageDescriptor msg, String prefix,
                                             HashSet<String> names) {
        String qualifiedPrefix = prefix.size == 0 ? msg.name : $"{prefix}.{msg.name}";
        for (EnumDescriptor e : msg.enums) {
            names.add(e.name);
            names.add($"{qualifiedPrefix}.{e.name}");
        }
        for (MessageDescriptor nested : msg.nestedMessages) {
            collectEnumNamesFromMessage(nested, qualifiedPrefix, names);
        }
    }

    /**
     * @return True if the field references an enum type (either via TypeEnum or by
     *         having a typeName that matches a known enum)
     */
    private Boolean isEnumRef(FieldDescriptor field) {
        if (field.type == TypeEnum) {
            return True;
        }
        if (field.type != TypeMessage || field.typeName.size == 0) {
            return False;
        }
        if (enumNames.contains(field.typeName)) {
            return True;
        }
        // check if the last segment of a dotted name is a known enum
        if (Int dot := field.typeName.lastIndexOf('.')) {
            return enumNames.contains(field.typeName[dot + 1 ..< field.typeName.size]);
        }
        return False;
    }

    // ----- naming helpers ------------------------------------------------------------------------

    /**
     * Convert a proto field name to a safe Ecstasy camelCase identifier, escaping keywords.
     */
    private String fieldName(String name) = escapeKeyword(toCamelCase(name));

    /**
     * Convert a `snake_case` or `UPPER_SNAKE_CASE` name to `camelCase`.
     */
    private String toCamelCase(String name) {
        // if no underscores, it's PascalCase or a single word — just lowercase the first char
        if (!name.indexOf('_')) {
            if (name.size == 0) {
                return name;
            }
            // check if it's ALL_UPPERCASE (no lowercase chars)
            Boolean allUpper = True;
            for (Int i = 0; i < name.size; i++) {
                if (name[i] >= 'a' && name[i] <= 'z') {
                    allUpper = False;
                    break;
                }
            }
            if (allUpper) {
                // ALL_UPPER single word: lowercase everything then uppercase first
                // handled by toPascalCase caller — here just lowercase all
                StringBuffer buf = new StringBuffer();
                for (Int i = 0; i < name.size; i++) {
                    buf.add(name[i] >= 'A' && name[i] <= 'Z' ? name[i].lowercase : name[i]);
                }
                return buf.toString();
            }
            // PascalCase: just lowercase first char
            return $"{name[0].lowercase}{name[1..<name.size]}";
        }

        // snake_case or UPPER_SNAKE_CASE: split on underscore, capitalize each segment
        StringBuffer buf       = new StringBuffer();
        Boolean      upperNext = False;
        Boolean      first     = True;

        for (Int i = 0; i < name.size; i++) {
            Char ch = name[i];
            if (ch == '_') {
                upperNext = True;
            } else if (first) {
                buf.add(ch >= 'A' && ch <= 'Z' ? ch.lowercase : ch);
                first = False;
            } else if (upperNext) {
                buf.add(ch >= 'a' && ch <= 'z' ? ch.uppercase : ch);
                upperNext = False;
            } else {
                buf.add(ch >= 'A' && ch <= 'Z' ? ch.lowercase : ch);
            }
        }
        return buf.toString();
    }

    /**
     * Convert a `snake_case`, `UPPER_SNAKE_CASE`, or `PascalCase` name to `PascalCase`.
     */
    private String toPascalCase(String name) {
        String camel = toCamelCase(name);
        return camel.size > 0 && camel[0] >= 'a' && camel[0] <= 'z'
                ? $"{camel[0].uppercase}{camel[1..<camel.size]}"
                : camel;
    }

    /**
     * Escape a field name if it matches an Ecstasy keyword by appending an underscore.
     */
    private String escapeKeyword(String name) {
        for (String kw : Keywords) {
            if (kw == name) {
                return name + "_";
            }
        }
        return name;
    }

    /**
     * Sanitize a type name for use in a typedef alias (convert dots to underscores).
     */
    private String sanitizeTypedefName(String typeName) {
        if (!typeName.indexOf('.')) {
            return typeName;
        }
        StringBuffer buf = new StringBuffer(typeName.size);
        for (Int i = 0; i < typeName.size; i++) {
            Char ch = typeName[i];
            buf.add(ch == '.' ? '_' : ch);
        }
        return buf.toString();
    }

    // ----- formatting helpers --------------------------------------------------------------------

    /**
     * @return whitespace for the given indentation level (4 spaces per level)
     */
    private String spaces(Int level) {
        StringBuffer buf = new StringBuffer(level * 4);
        for (Int i = 0; i < level * 4; i++) {
            buf.add(' ');
        }
        return buf.toString();
    }

    /**
     * @return a separator comment line padded to 100 characters
     */
    private String separator(String label, Int indent) {
        StringBuffer buf = new StringBuffer();
        buf.addAll("// ----- ").addAll(label).addAll(" ");
        Int padLen = indent * 4;
        Int targetLen = 100 - padLen;
        while (buf.size < targetLen) {
            buf.add('-');
        }
        return buf.toString();
    }
}
