package org.xvm.javajit.classfile;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.condition.EnabledOnJre;
import org.junit.jupiter.api.condition.JRE;

import java.lang.classfile.ClassBuilder;
import java.lang.classfile.ClassFile;
import java.lang.classfile.CodeBuilder;
import java.lang.classfile.MethodBuilder;
import java.lang.classfile.TypeKind;
import java.lang.classfile.attribute.SourceFileAttribute;

import java.lang.constant.ClassDesc;
import java.lang.constant.MethodTypeDesc;
import java.lang.constant.ConstantDescs;

import java.lang.reflect.Method;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.logging.ConsoleHandler;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive unit tests for ClassFile API JIT implementation.
 * Tests bytecode generation, transforms, and class loading with detailed logging.
 * 
 * Note: These tests require Java 22+ with ClassFile API available.
 * On Java 22/23, requires --enable-preview flag.
 */
@EnabledOnJre({JRE.JAVA_22, JRE.JAVA_23, JRE.JAVA_24, JRE.OTHER}) // Enable on Java 22+
public class ClassFileJitTest {
    
    private static final Logger LOGGER = Logger.getLogger(ClassFileJitTest.class.getName());
    private ClassFile classFile;
    
    static {
        // Configure detailed logging for test visibility
        LOGGER.setLevel(Level.ALL);
        ConsoleHandler handler = new ConsoleHandler();
        handler.setLevel(Level.ALL);
        LOGGER.addHandler(handler);
    }
    
    @BeforeEach
    void setUp() {
        LOGGER.info("=== ClassFile API JIT Test Setup ===");
        
        // Check if ClassFile API is available
        try {
            Class.forName("java.lang.classfile.ClassFile");
            LOGGER.info("ClassFile API is available");
        } catch (ClassNotFoundException e) {
            LOGGER.severe("ClassFile API not available - tests will be skipped");
            fail("ClassFile API not available on this JVM");
        }
        
        classFile = ClassFile.of();
        LOGGER.info("ClassFile instance created: " + classFile.getClass().getName());
        
        // Log Java version and ClassFile API status
        String javaVersion = System.getProperty("java.version");
        LOGGER.info("Java version: " + javaVersion);
        LOGGER.info("ClassFile API status: Available (finalized in Java 24, preview in 22/23)");
    }
    
    @Test
    @DisplayName("ClassFile API - Basic Class Generation")
    void testBasicClassGeneration() throws Exception {
        LOGGER.info("--- Test: Basic Class Generation ---");
        
        String className = "org.xvm.test.GeneratedByClassFile";
        ClassDesc classDesc = ClassDesc.of(className);
        LOGGER.info("Generating class: " + className);
        
        // Generate a simple class with ClassFile API
        byte[] bytecode = classFile.build(classDesc, classBuilder -> {
            LOGGER.info("Building class with ClassFile API...");
            
            classBuilder
                .withFlags(ClassFile.ACC_PUBLIC)
                .with(SourceFileAttribute.of("GeneratedByClassFile.java"))
                .withMethodBody("getMessage", 
                    MethodTypeDesc.of(ConstantDescs.CD_String), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building method: getMessage()");
                        codeBuilder
                            .ldc("Hello from ClassFile API!")
                            .areturn();
                    });
        });
        
        LOGGER.info("Generated bytecode size: " + bytecode.length + " bytes");
        
        // Load the class using a custom ClassLoader
        Class<?> generatedClass = loadClassFromBytecode(className, bytecode);
        LOGGER.info("Loaded class: " + generatedClass.getName());
        LOGGER.info("Superclass: " + generatedClass.getSuperclass().getName());
        
        // Test the generated class
        Object instance = generatedClass.getDeclaredConstructor().newInstance();
        Method method = generatedClass.getMethod("getMessage");
        String result = (String) method.invoke(instance);
        
        LOGGER.info("Method invocation result: " + result);
        
        assertEquals("Hello from ClassFile API!", result);
        assertEquals(className, generatedClass.getName());
        assertEquals(Object.class, generatedClass.getSuperclass());
        
        LOGGER.info("✓ Basic class generation test passed");
    }
    
    @Test
    @DisplayName("ClassFile API - Bytecode Transform Test")
    void testBytecodeTransform() throws Exception {
        LOGGER.info("--- Test: Bytecode Transform ---");
        
        String originalClassName = "org.xvm.test.OriginalClassFile";
        String transformedClassName = "org.xvm.test.TransformedClassFile";
        
        LOGGER.info("Creating original class: " + originalClassName);
        
        // Create original class
        byte[] originalBytecode = classFile.build(ClassDesc.of(originalClassName), classBuilder -> {
            classBuilder
                .withFlags(ClassFile.ACC_PUBLIC)
                .with(SourceFileAttribute.of("OriginalClassFile.java"))
                .withMethodBody("getValue", 
                    MethodTypeDesc.of(ConstantDescs.CD_int), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building original getValue() method");
                        codeBuilder
                            .bipush(42)
                            .ireturn();
                    });
        });
        
        LOGGER.info("Original class bytecode size: " + originalBytecode.length + " bytes");
        
        // Create transformed class
        LOGGER.info("Creating transformed class: " + transformedClassName);
        
        byte[] transformedBytecode = classFile.build(ClassDesc.of(transformedClassName), classBuilder -> {
            classBuilder
                .withFlags(ClassFile.ACC_PUBLIC)
                .with(SourceFileAttribute.of("TransformedClassFile.java"))
                .withMethodBody("getValue", 
                    MethodTypeDesc.of(ConstantDescs.CD_int), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building transformed getValue() method");
                        codeBuilder
                            .bipush(99)  // Different value
                            .ireturn();
                    })
                .withMethodBody("getTransformed", 
                    MethodTypeDesc.of(ConstantDescs.CD_boolean), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building additional getTransformed() method");
                        codeBuilder
                            .iconst_1()  // true
                            .ireturn();
                    });
        });
        
        LOGGER.info("Transformed class bytecode size: " + transformedBytecode.length + " bytes");
        
        // Load and test both classes
        Class<?> originalClass = loadClassFromBytecode(originalClassName, originalBytecode);
        Class<?> transformedClass = loadClassFromBytecode(transformedClassName, transformedBytecode);
        
        Object originalInstance = originalClass.getDeclaredConstructor().newInstance();
        Object transformedInstance = transformedClass.getDeclaredConstructor().newInstance();
        
        // Test original class
        Method originalGetValue = originalClass.getMethod("getValue");
        int originalValue = (int) originalGetValue.invoke(originalInstance);
        LOGGER.info("Original class getValue(): " + originalValue);
        
        // Test transformed class
        Method transformedGetValue = transformedClass.getMethod("getValue");
        int transformedValue = (int) transformedGetValue.invoke(transformedInstance);
        LOGGER.info("Transformed class getValue(): " + transformedValue);
        
        Method getTransformed = transformedClass.getMethod("getTransformed");
        boolean isTransformed = (boolean) getTransformed.invoke(transformedInstance);
        LOGGER.info("Transformed class getTransformed(): " + isTransformed);
        
        // Verify the transform worked
        assertEquals(42, originalValue);
        assertEquals(99, transformedValue);
        assertTrue(isTransformed);
        
        // Verify bytecode is different
        assertFalse(java.util.Arrays.equals(originalBytecode, transformedBytecode));
        LOGGER.info("✓ Bytecode sizes differ: original=" + originalBytecode.length + 
                   ", transformed=" + transformedBytecode.length);
        
        LOGGER.info("✓ Bytecode transform test passed");
    }
    
    @Test
    @DisplayName("ClassFile API - Complex Method Generation")
    void testComplexMethodGeneration() throws Exception {
        LOGGER.info("--- Test: Complex Method Generation ---");
        
        String className = "org.xvm.test.ComplexClassFileClass";
        ClassDesc classDesc = ClassDesc.of(className);
        LOGGER.info("Generating complex class: " + className);
        
        byte[] bytecode = classFile.build(classDesc, classBuilder -> {
            classBuilder
                .withFlags(ClassFile.ACC_PUBLIC)
                .with(SourceFileAttribute.of("ComplexClassFileClass.java"))
                // Method with parameters
                .withMethodBody("calculate", 
                    MethodTypeDesc.of(ConstantDescs.CD_int, ConstantDescs.CD_int, ConstantDescs.CD_int), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building calculate(int, int) method");
                        codeBuilder
                            .iload(1)  // Load first parameter
                            .iload(2)  // Load second parameter
                            .iadd()    // Add them
                            .ireturn();
                    })
                // String method
                .withMethodBody("formatResult", 
                    MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_int), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building formatResult(int) method");
                        codeBuilder
                            .ldc("Result: ")
                            .aload(0)  // this
                            .iload(1)  // parameter
                            .invokevirtual(ClassDesc.of("java.lang.String"), "valueOf", 
                                MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_int))
                            .invokespecial(ClassDesc.of("java.lang.String"), "concat", 
                                MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_String))
                            .areturn();
                    })
                // Boolean method
                .withMethodBody("isPositive", 
                    MethodTypeDesc.of(ConstantDescs.CD_boolean, ConstantDescs.CD_int), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building isPositive(int) method");
                        codeBuilder
                            .iload(1)     // Load parameter
                            .ifle(codeBuilder.newLabel())  // If <= 0, jump to label
                            .iconst_1()   // true
                            .ireturn()
                            .labelBinding(codeBuilder.newLabel())
                            .iconst_0()   // false
                            .ireturn();
                    });
        });
        
        LOGGER.info("Complex class bytecode size: " + bytecode.length + " bytes");
        
        // Load and test
        Class<?> complexClass = loadClassFromBytecode(className, bytecode);
        Object instance = complexClass.getDeclaredConstructor().newInstance();
        
        // Test calculate method
        Method calculate = complexClass.getMethod("calculate", int.class, int.class);
        int calcResult = (int) calculate.invoke(instance, 10, 20);
        LOGGER.info("calculate(10, 20): " + calcResult);
        
        // Test formatResult method  
        Method formatResult = complexClass.getMethod("formatResult", int.class);
        String formatResultStr = (String) formatResult.invoke(instance, 42);
        LOGGER.info("formatResult(42): " + formatResultStr);
        
        // Test isPositive method
        Method isPositive = complexClass.getMethod("isPositive", int.class);
        boolean positiveResult = (boolean) isPositive.invoke(instance, 5);
        boolean negativeResult = (boolean) isPositive.invoke(instance, -3);
        LOGGER.info("isPositive(5): " + positiveResult);
        LOGGER.info("isPositive(-3): " + negativeResult);
        
        // Verify results
        assertEquals(30, calcResult);
        assertTrue(formatResultStr.contains("Result: ") && formatResultStr.contains("42"));
        assertTrue(positiveResult);
        assertFalse(negativeResult);
        
        LOGGER.info("✓ Complex method generation test passed");
    }
    
    @Test
    @DisplayName("ClassFile API - Resource Loading Simulation")
    void testResourceLoadingSimulation() throws Exception {
        LOGGER.info("--- Test: Resource Loading Simulation ---");
        
        String resourceClassName = "org.xvm.test.ClassFileResourceHandler";
        ClassDesc classDesc = ClassDesc.of(resourceClassName);
        LOGGER.info("Creating resource handler class: " + resourceClassName);
        
        byte[] bytecode = classFile.build(classDesc, classBuilder -> {
            classBuilder
                .withFlags(ClassFile.ACC_PUBLIC)
                .with(SourceFileAttribute.of("ClassFileResourceHandler.java"))
                .withMethodBody("loadResource", 
                    MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_String), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building loadResource(String) method");
                        codeBuilder
                            .ldc("ClassFile API Resource loaded: ")
                            .aload(1)  // parameter (resource name)
                            .invokespecial(ClassDesc.of("java.lang.String"), "concat", 
                                MethodTypeDesc.of(ConstantDescs.CD_String, ConstantDescs.CD_String))
                            .areturn();
                    })
                .withMethodBody("getHandlerInfo", 
                    MethodTypeDesc.of(ConstantDescs.CD_String), 
                    ClassFile.ACC_PUBLIC,
                    codeBuilder -> {
                        LOGGER.info("Building getHandlerInfo() method");
                        codeBuilder
                            .ldc("ClassFile API Resource Handler v1.0")
                            .areturn();
                    });
        });
        
        LOGGER.info("Resource handler bytecode size: " + bytecode.length + " bytes");
        
        // Simulate storing bytecode as resource
        LOGGER.info("Simulating bytecode storage and retrieval...");
        
        // Load from "resource" (bytecode array)
        Class<?> resourceClass = loadClassFromBytecode(resourceClassName, bytecode);
        Object resourceHandler = resourceClass.getDeclaredConstructor().newInstance();
        
        Method loadResource = resourceClass.getMethod("loadResource", String.class);
        Method getHandlerInfo = resourceClass.getMethod("getHandlerInfo");
        
        String loadResult = (String) loadResource.invoke(resourceHandler, "config.properties");
        String info = (String) getHandlerInfo.invoke(resourceHandler);
        
        LOGGER.info("loadResource('config.properties'): " + loadResult);
        LOGGER.info("getHandlerInfo(): " + info);
        
        assertEquals("ClassFile API Resource loaded: config.properties", loadResult);
        assertEquals("ClassFile API Resource Handler v1.0", info);
        
        LOGGER.info("✓ Resource loading simulation test passed");
    }
    
    /**
     * Helper method to load a class from bytecode using a custom ClassLoader.
     */
    private Class<?> loadClassFromBytecode(String className, byte[] bytecode) throws Exception {
        ClassLoader classLoader = new ClassLoader(getClass().getClassLoader()) {
            @Override
            protected Class<?> findClass(String name) throws ClassNotFoundException {
                if (name.equals(className)) {
                    return defineClass(name, bytecode, 0, bytecode.length);
                }
                throw new ClassNotFoundException(name);
            }
        };
        
        return classLoader.loadClass(className);
    }
}