package org.xvm.javajit.bytebuddy;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.implementation.FixedValue;
import net.bytebuddy.matcher.ElementMatchers;

import java.lang.reflect.Method;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.util.logging.ConsoleHandler;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive unit tests for ByteBuddy JIT implementation.
 * Tests bytecode generation, transforms, and class loading with detailed logging.
 */
public class ByteBuddyJitTest {
    
    private static final Logger LOGGER = Logger.getLogger(ByteBuddyJitTest.class.getName());
    private ByteBuddy byteBuddy;
    
    static {
        // Configure detailed logging for test visibility
        LOGGER.setLevel(Level.ALL);
        ConsoleHandler handler = new ConsoleHandler();
        handler.setLevel(Level.ALL);
        LOGGER.addHandler(handler);
    }
    
    @BeforeEach
    void setUp() {
        LOGGER.info("=== ByteBuddy JIT Test Setup ===");
        byteBuddy = new ByteBuddy();
        LOGGER.info("ByteBuddy instance created: " + byteBuddy.getClass().getName());
        
        // Log ByteBuddy version
        Package pkg = ByteBuddy.class.getPackage();
        String version = pkg != null && pkg.getImplementationVersion() != null 
            ? pkg.getImplementationVersion() 
            : "unknown";
        LOGGER.info("ByteBuddy version: " + version);
    }
    
    @Test
    @DisplayName("ByteBuddy - Basic Class Generation")
    void testBasicClassGeneration() throws Exception {
        LOGGER.info("--- Test: Basic Class Generation ---");
        
        // Generate a simple class with ByteBuddy
        String className = "org.xvm.test.GeneratedByByteBuddy";
        LOGGER.info("Generating class: " + className);
        
        DynamicType.Unloaded<?> unloaded = byteBuddy
            .subclass(Object.class)
            .name(className)
            .defineMethod("getMessage", String.class)
            .intercept(FixedValue.value("Hello from ByteBuddy!"))
            .make();
        
        // Get bytecode
        byte[] bytecode = unloaded.getBytes();
        LOGGER.info("Generated bytecode size: " + bytecode.length + " bytes");
        
        // Load the class
        Class<?> generatedClass = unloaded.load(getClass().getClassLoader()).getLoaded();
        LOGGER.info("Loaded class: " + generatedClass.getName());
        LOGGER.info("Superclass: " + generatedClass.getSuperclass().getName());
        
        // Test the generated class
        Object instance = generatedClass.getDeclaredConstructor().newInstance();
        Method method = generatedClass.getMethod("getMessage");
        String result = (String) method.invoke(instance);
        
        LOGGER.info("Method invocation result: " + result);
        
        assertEquals("Hello from ByteBuddy!", result);
        assertEquals(className, generatedClass.getName());
        assertEquals(Object.class, generatedClass.getSuperclass());
        
        LOGGER.info("✓ Basic class generation test passed");
    }
    
    @Test
    @DisplayName("ByteBuddy - Bytecode Transform Test")
    void testBytecodeTransform() throws Exception {
        LOGGER.info("--- Test: Bytecode Transform ---");
        
        // Create a class that we'll transform
        String originalClassName = "org.xvm.test.OriginalClass";
        String transformedClassName = "org.xvm.test.TransformedClass";
        
        LOGGER.info("Creating original class: " + originalClassName);
        
        // First, create an original class
        DynamicType.Unloaded<?> originalType = byteBuddy
            .subclass(Object.class)
            .name(originalClassName)
            .defineMethod("getValue", int.class)
            .intercept(FixedValue.value(42))
            .make();
        
        byte[] originalBytecode = originalType.getBytes();
        LOGGER.info("Original class bytecode size: " + originalBytecode.length + " bytes");
        
        // Now create a transformed version
        LOGGER.info("Creating transformed class: " + transformedClassName);
        
        DynamicType.Unloaded<?> transformedType = byteBuddy
            .subclass(Object.class)
            .name(transformedClassName)
            .defineMethod("getValue", int.class)
            .intercept(FixedValue.value(99))  // Different value
            .defineMethod("getTransformed", boolean.class)
            .intercept(FixedValue.value(true))  // Additional method
            .make();
        
        byte[] transformedBytecode = transformedType.getBytes();
        LOGGER.info("Transformed class bytecode size: " + transformedBytecode.length + " bytes");
        
        // Load and test both classes
        Class<?> originalClass = originalType.load(getClass().getClassLoader()).getLoaded();
        Class<?> transformedClass = transformedType.load(getClass().getClassLoader()).getLoaded();
        
        Object originalInstance = originalClass.getDeclaredConstructor().newInstance();
        Object transformedInstance = transformedClass.getDeclaredConstructor().newInstance();
        
        // Test original class
        Method originalGetValue = originalClass.getMethod("getValue");
        int originalValue = (int) originalGetValue.invoke(originalInstance);
        LOGGER.info("Original class getValue(): " + originalValue);
        
        // Test transformed class
        Method transformedGetValue = transformedClass.getMethod("getValue");
        int transformedValue = (int) transformedGetValue.invoke(transformedInstance);
        LOGGER.info("Transformed class getValue(): " + transformedValue);
        
        Method getTransformed = transformedClass.getMethod("getTransformed");
        boolean isTransformed = (boolean) getTransformed.invoke(transformedInstance);
        LOGGER.info("Transformed class getTransformed(): " + isTransformed);
        
        // Verify the transform worked
        assertEquals(42, originalValue);
        assertEquals(99, transformedValue);
        assertTrue(isTransformed);
        
        // Verify bytecode is different
        assertFalse(java.util.Arrays.equals(originalBytecode, transformedBytecode));
        LOGGER.info("✓ Bytecode sizes differ: original=" + originalBytecode.length + 
                   ", transformed=" + transformedBytecode.length);
        
        LOGGER.info("✓ Bytecode transform test passed");
    }
    
    @Test
    @DisplayName("ByteBuddy - Method Interception Transform")
    void testMethodInterceptionTransform() throws Exception {
        LOGGER.info("--- Test: Method Interception Transform ---");
        
        String className = "org.xvm.test.InterceptedClass";
        LOGGER.info("Creating intercepted class: " + className);
        
        // Create a class with method interception (more complex transform)
        DynamicType.Unloaded<?> interceptedType = byteBuddy
            .subclass(Object.class)
            .name(className)
            .defineMethod("calculate", int.class)
                .withParameter(int.class, "input")
            .intercept(FixedValue.value(0)) // Placeholder - in real scenario would be complex logic
            .defineMethod("getInfo", String.class)
            .intercept(FixedValue.value("ByteBuddy Generated Class with Interception"))
            .make();
        
        byte[] bytecode = interceptedType.getBytes();
        LOGGER.info("Intercepted class bytecode size: " + bytecode.length + " bytes");
        
        // Load and test
        Class<?> interceptedClass = interceptedType.load(getClass().getClassLoader()).getLoaded();
        Object instance = interceptedClass.getDeclaredConstructor().newInstance();
        
        Method calculate = interceptedClass.getMethod("calculate", int.class);
        Method getInfo = interceptedClass.getMethod("getInfo");
        
        int result = (int) calculate.invoke(instance, 100);
        String info = (String) getInfo.invoke(instance);
        
        LOGGER.info("calculate(100) result: " + result);
        LOGGER.info("getInfo() result: " + info);
        
        assertEquals(0, result);
        assertEquals("ByteBuddy Generated Class with Interception", info);
        
        LOGGER.info("✓ Method interception transform test passed");
    }
    
    @Test
    @DisplayName("ByteBuddy - Resource Loading Simulation")
    void testResourceLoadingSimulation() throws Exception {
        LOGGER.info("--- Test: Resource Loading Simulation ---");
        
        // Simulate what would happen in a real resource loading scenario
        String resourceClassName = "org.xvm.test.ResourceHandler";
        LOGGER.info("Creating resource handler class: " + resourceClassName);
        
        DynamicType.Unloaded<?> resourceType = byteBuddy
            .subclass(Object.class)
            .name(resourceClassName)
            .defineMethod("loadResource", String.class)
                .withParameter(String.class, "resourceName")
            .intercept(FixedValue.value("Resource loaded successfully"))
            .defineMethod("getResourceInfo", String.class)
            .intercept(FixedValue.value("ByteBuddy Resource Handler v1.0"))
            .make();
        
        byte[] bytecode = resourceType.getBytes();
        LOGGER.info("Resource handler bytecode size: " + bytecode.length + " bytes");
        
        // Simulate storing bytecode as if it were a resource
        LOGGER.info("Simulating bytecode storage and retrieval...");
        
        // Load from "resource" (bytecode array)
        Class<?> resourceClass = resourceType.load(getClass().getClassLoader()).getLoaded();
        Object resourceHandler = resourceClass.getDeclaredConstructor().newInstance();
        
        Method loadResource = resourceClass.getMethod("loadResource", String.class);
        Method getResourceInfo = resourceClass.getMethod("getResourceInfo");
        
        String loadResult = (String) loadResource.invoke(resourceHandler, "test.properties");
        String info = (String) getResourceInfo.invoke(resourceHandler);
        
        LOGGER.info("loadResource('test.properties') result: " + loadResult);
        LOGGER.info("getResourceInfo() result: " + info);
        
        assertEquals("Resource loaded successfully", loadResult);
        assertEquals("ByteBuddy Resource Handler v1.0", info);
        
        LOGGER.info("✓ Resource loading simulation test passed");
    }
    
    @Test
    @DisplayName("ByteBuddy - Complex Class Structure")
    void testComplexClassStructure() throws Exception {
        LOGGER.info("--- Test: Complex Class Structure ---");
        
        String className = "org.xvm.test.ComplexGeneratedClass";
        LOGGER.info("Creating complex class: " + className);
        
        // Create a more complex class structure
        DynamicType.Unloaded<?> complexType = byteBuddy
            .subclass(Object.class)
            .name(className)
            // Multiple methods with different signatures
            .defineMethod("getString", String.class)
            .intercept(FixedValue.value("ByteBuddy Complex Class"))
            .defineMethod("getNumber", int.class)
            .intercept(FixedValue.value(42))
            .defineMethod("getBoolean", boolean.class)
            .intercept(FixedValue.value(true))
            .defineMethod("processData", String.class)
                .withParameter(String.class, "input")
                .withParameter(int.class, "count")
            .intercept(FixedValue.value("Processed"))
            // Define fields (simulated)
            .defineMethod("getFieldValue", String.class)
            .intercept(FixedValue.value("field_value"))
            .make();
        
        byte[] bytecode = complexType.getBytes();
        LOGGER.info("Complex class bytecode size: " + bytecode.length + " bytes");
        
        // Load and thoroughly test
        Class<?> complexClass = complexType.load(getClass().getClassLoader()).getLoaded();
        Object instance = complexClass.getDeclaredConstructor().newInstance();
        
        // Test all methods
        Method getString = complexClass.getMethod("getString");
        Method getNumber = complexClass.getMethod("getNumber");
        Method getBoolean = complexClass.getMethod("getBoolean");
        Method processData = complexClass.getMethod("processData", String.class, int.class);
        Method getFieldValue = complexClass.getMethod("getFieldValue");
        
        String stringResult = (String) getString.invoke(instance);
        int numberResult = (int) getNumber.invoke(instance);
        boolean booleanResult = (boolean) getBoolean.invoke(instance);
        String processedResult = (String) processData.invoke(instance, "test", 5);
        String fieldResult = (String) getFieldValue.invoke(instance);
        
        LOGGER.info("getString(): " + stringResult);
        LOGGER.info("getNumber(): " + numberResult);
        LOGGER.info("getBoolean(): " + booleanResult);
        LOGGER.info("processData('test', 5): " + processedResult);
        LOGGER.info("getFieldValue(): " + fieldResult);
        
        // Verify all results
        assertEquals("ByteBuddy Complex Class", stringResult);
        assertEquals(42, numberResult);
        assertTrue(booleanResult);
        assertEquals("Processed", processedResult);
        assertEquals("field_value", fieldResult);
        
        // Verify method count
        Method[] methods = complexClass.getDeclaredMethods();
        LOGGER.info("Total methods in complex class: " + methods.length);
        assertTrue(methods.length >= 5, "Should have at least 5 methods");
        
        LOGGER.info("✓ Complex class structure test passed");
    }
}