package org.xvm.javajit;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.implementation.FixedValue;

import java.lang.reflect.Method;

/**
 * Demonstration class that shows both ByteBuddy and ClassFile API implementations working.
 * This can be run as a standalone program to verify functionality.
 */
public class JitDemonstration {
    
    public static void main(String[] args) {
        System.out.println("========================================");
        System.out.println("    JIT IMPLEMENTATION DEMONSTRATION   ");
        System.out.println("========================================");
        System.out.println();
        
        try {
            // Show system information
            showSystemInformation();
            System.out.println();
            
            // Show JIT implementation factory status
            showJitFactoryStatus();
            System.out.println();
            
            // Demonstrate ByteBuddy
            demonstrateByteBuddy();
            System.out.println();
            
            // Demonstrate ClassFile API (if available)
            demonstrateClassFileApi();
            System.out.println();
            
            // Show comparison
            showComparison();
            
            System.out.println("========================================");
            System.out.println("        DEMONSTRATION COMPLETE         ");
            System.out.println("========================================");
            
        } catch (Exception e) {
            System.err.println("ERROR: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private static void showSystemInformation() {
        System.out.println("--- System Information ---");
        System.out.println("Java Version: " + System.getProperty("java.version"));
        System.out.println("Java Vendor: " + System.getProperty("java.vendor"));
        System.out.println("Java Home: " + System.getProperty("java.home"));
        System.out.println("JVM: " + System.getProperty("java.vm.name") + " " + System.getProperty("java.vm.version"));
        System.out.println("OS: " + System.getProperty("os.name") + " " + System.getProperty("os.version"));
        
        // Check for preview features
        String[] jvmArgs = java.lang.management.ManagementFactory.getRuntimeMXBean().getInputArguments().toArray(new String[0]);
        boolean hasPreview = false;
        for (String arg : jvmArgs) {
            if (arg.contains("enable-preview")) {
                hasPreview = true;
                break;
            }
        }
        System.out.println("Preview Features Enabled: " + hasPreview);
    }
    
    private static void showJitFactoryStatus() {
        System.out.println("--- JIT Implementation Factory Status ---");
        
        // Show property configuration
        System.out.println("JIT implementation configured via xdk.properties");
        
        // Show detailed status
        String detailedStatus = JitImplementationFactory.getDetailedStatus();
        for (String line : detailedStatus.split("\n")) {
            System.out.println(line);
        }
    }
    
    private static void demonstrateByteBuddy() throws Exception {
        System.out.println("--- ByteBuddy Demonstration ---");
        
        try {
            // Check if ByteBuddy is available
            Class.forName("net.bytebuddy.ByteBuddy");
            System.out.println("✓ ByteBuddy is available");
            
            // Get version
            Package pkg = ByteBuddy.class.getPackage();
            String version = pkg != null && pkg.getImplementationVersion() != null 
                ? pkg.getImplementationVersion() 
                : "unknown";
            System.out.println("ByteBuddy Version: " + version);
            
            // Create a simple class with ByteBuddy
            ByteBuddy byteBuddy = new ByteBuddy();
            System.out.println("Creating class with ByteBuddy...");
            
            String className = "org.xvm.demo.ByteBuddyGeneratedClass";
            DynamicType.Unloaded<?> unloaded = byteBuddy
                .subclass(Object.class)
                .name(className)
                .defineMethod("getMessage", String.class)
                .intercept(FixedValue.value("Hello from ByteBuddy! 🚀"))
                .defineMethod("getNumber", int.class)
                .intercept(FixedValue.value(42))
                .make();
            
            byte[] bytecode = unloaded.getBytes();
            System.out.println("Generated bytecode size: " + bytecode.length + " bytes");
            
            // Load and test the class
            Class<?> generatedClass = unloaded.load(JitDemonstration.class.getClassLoader()).getLoaded();
            Object instance = generatedClass.getDeclaredConstructor().newInstance();
            
            Method getMessage = generatedClass.getMethod("getMessage");
            Method getNumber = generatedClass.getMethod("getNumber");
            
            String message = (String) getMessage.invoke(instance);
            int number = (int) getNumber.invoke(instance);
            
            System.out.println("✓ Class loaded successfully: " + generatedClass.getName());
            System.out.println("✓ getMessage() result: " + message);
            System.out.println("✓ getNumber() result: " + number);
            
            // Test bytecode transformation
            System.out.println("Testing bytecode transformation...");
            
            DynamicType.Unloaded<?> transformedUnloaded = byteBuddy
                .subclass(Object.class)
                .name("org.xvm.demo.ByteBuddyTransformedClass")
                .defineMethod("getMessage", String.class)
                .intercept(FixedValue.value("Transformed with ByteBuddy! ✨"))
                .defineMethod("getNumber", int.class)
                .intercept(FixedValue.value(99))
                .defineMethod("isTransformed", boolean.class)
                .intercept(FixedValue.value(true))
                .make();
            
            byte[] transformedBytecode = transformedUnloaded.getBytes();
            System.out.println("Transformed bytecode size: " + transformedBytecode.length + " bytes");
            
            Class<?> transformedClass = transformedUnloaded.load(JitDemonstration.class.getClassLoader()).getLoaded();
            Object transformedInstance = transformedClass.getDeclaredConstructor().newInstance();
            
            Method transformedGetMessage = transformedClass.getMethod("getMessage");
            Method transformedGetNumber = transformedClass.getMethod("getNumber");
            Method isTransformed = transformedClass.getMethod("isTransformed");
            
            String transformedMessage = (String) transformedGetMessage.invoke(transformedInstance);
            int transformedNumber = (int) transformedGetNumber.invoke(transformedInstance);
            boolean transformed = (boolean) isTransformed.invoke(transformedInstance);
            
            System.out.println("✓ Transformed class: " + transformedClass.getName());
            System.out.println("✓ Transformed getMessage(): " + transformedMessage);
            System.out.println("✓ Transformed getNumber(): " + transformedNumber);
            System.out.println("✓ isTransformed(): " + transformed);
            
            System.out.println("✅ ByteBuddy demonstration completed successfully!");
            
        } catch (ClassNotFoundException e) {
            System.out.println("❌ ByteBuddy is not available on the classpath");
        } catch (Exception e) {
            System.out.println("❌ ByteBuddy demonstration failed: " + e.getMessage());
            throw e;
        }
    }
    
    private static void demonstrateClassFileApi() throws Exception {
        System.out.println("--- ClassFile API Demonstration ---");
        
        try {
            // Check if ClassFile API is available
            Class.forName("java.lang.classfile.ClassFile");
            System.out.println("✓ ClassFile API is available");
            
            // Show Java version context
            String javaVersion = System.getProperty("java.version");
            if (javaVersion.startsWith("22") || javaVersion.startsWith("23")) {
                System.out.println("ℹ️  Note: ClassFile API requires --enable-preview on Java " + javaVersion.substring(0, 2));
            } else if (javaVersion.startsWith("24")) {
                System.out.println("ℹ️  Note: ClassFile API is finalized in Java 24");
            }
            
            System.out.println("⚠️  ClassFile API demonstration would require complex reflection");
            System.out.println("⚠️  to avoid compile-time dependencies in this demonstration");
            System.out.println("⚠️  See ClassFileJitTest for full ClassFile API examples");
            System.out.println("✅ ClassFile API is available and ready for use!");
            
        } catch (ClassNotFoundException e) {
            System.out.println("❌ ClassFile API is not available");
            String javaVersion = System.getProperty("java.version");
            if (javaVersion.startsWith("21")) {
                System.out.println("ℹ️  This is expected on Java 21 - ClassFile API was introduced in Java 22");
            } else {
                System.out.println("ℹ️  ClassFile API should be available on Java 22+");
                System.out.println("ℹ️  On Java 22/23, ensure --enable-preview flag is used");
            }
        }
    }
    
    private static void showComparison() {
        System.out.println("--- Implementation Comparison Summary ---");
        
        boolean byteBuddyAvailable = false;
        boolean classFileAvailable = false;
        
        try {
            Class.forName("net.bytebuddy.ByteBuddy");
            byteBuddyAvailable = true;
        } catch (ClassNotFoundException e) {
            // Not available
        }
        
        try {
            Class.forName("java.lang.classfile.ClassFile");
            classFileAvailable = true;
        } catch (ClassNotFoundException e) {
            // Not available
        }
        
        System.out.println("ByteBuddy Available: " + (byteBuddyAvailable ? "✅ YES" : "❌ NO"));
        System.out.println("ClassFile API Available: " + (classFileAvailable ? "✅ YES" : "❌ NO"));
        
        if (byteBuddyAvailable || classFileAvailable) {
            System.out.println();
            System.out.println("Current JIT Selection:");
            System.out.println("  Implementation: " + JitImplementationFactory.getImplementationInfo());
            System.out.println("  Using ByteBuddy: " + JitImplementationFactory.isUsingByteBuddy());
            System.out.println("  Using ClassFile API: " + JitImplementationFactory.isUsingClassFileApi());
        }
        
        System.out.println();
        System.out.println("Recommendation Summary:");
        
        String javaVersion = System.getProperty("java.version");
        if (javaVersion.startsWith("21")) {
            System.out.println("✅ Java 21: ByteBuddy is the recommended choice (only option)");
        } else if (javaVersion.startsWith("22") || javaVersion.startsWith("23")) {
            System.out.println("✅ Java " + javaVersion.substring(0, 2) + ": ByteBuddy recommended (no --enable-preview needed)");
            System.out.println("⚠️  ClassFile API available but requires --enable-preview");
        } else if (javaVersion.startsWith("24")) {
            System.out.println("✅ Java 24: Both implementations available");
            System.out.println("✅ ByteBuddy: Stable, no preview features required");
            System.out.println("✅ ClassFile API: Finalized, no preview features required");
        }
        
        if (byteBuddyAvailable && !JitImplementationFactory.isUsingByteBuddy()) {
            System.out.println();
            System.out.println("💡 To use ByteBuddy: set org.xtclang.jit.implementation=bytebuddy in xdk.properties");
        }
        
        if (classFileAvailable && !JitImplementationFactory.isUsingClassFileApi()) {
            System.out.println();
            System.out.println("💡 To use ClassFile API: set org.xtclang.jit.implementation=classfile in xdk.properties");
        }
    }
}