/**
 * TODO Enums in C++ gencode (and potentially other languages) are
 * not well scoped.  This means that each of the feature enums below can clash
 * with each other.  The short names we've chosen maximize call-site
 * readability, but leave us very open to this scenario.  A future feature will
 * be designed and implemented to handle this, hopefully before we ever hit a
 * conflict here.
 *
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * FeatureSet defined in the proto file google/protobuf/descriptor.proto
 */
class FeatureSet
        extends protobuf.AbstractMessage {
    construct(
            wellknown.FeatureSet.FieldPresence? fieldPresence = Null,
            wellknown.FeatureSet.EnumType? enumType = Null,
            wellknown.FeatureSet.RepeatedFieldEncoding? repeatedFieldEncoding = Null,
            wellknown.FeatureSet.Utf8Validation? utf8Validation = Null,
            wellknown.FeatureSet.MessageEncoding? messageEncoding = Null,
            wellknown.FeatureSet.JsonFormat? jsonFormat = Null,
            wellknown.FeatureSet.EnforceNamingStyle? enforceNamingStyle = Null,
            wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility? defaultSymbolVisibility = Null) {
        construct protobuf.AbstractMessage();
        this.fieldPresence = fieldPresence;
        this.enumType = enumType;
        this.repeatedFieldEncoding = repeatedFieldEncoding;
        this.utf8Validation = utf8Validation;
        this.messageEncoding = messageEncoding;
        this.jsonFormat = jsonFormat;
        this.enforceNamingStyle = enforceNamingStyle;
        this.defaultSymbolVisibility = defaultSymbolVisibility;
    }

    @Override
    construct(FeatureSet other) {
        construct protobuf.AbstractMessage(other);
        fieldPresence = other.fieldPresence;
        enumType = other.enumType;
        repeatedFieldEncoding = other.repeatedFieldEncoding;
        utf8Validation = other.utf8Validation;
        messageEncoding = other.messageEncoding;
        jsonFormat = other.jsonFormat;
        enforceNamingStyle = other.enforceNamingStyle;
        defaultSymbolVisibility = other.defaultSymbolVisibility;
    }

    wellknown.FeatureSet.FieldPresence? fieldPresence = Null;
    wellknown.FeatureSet.EnumType? enumType = Null;
    wellknown.FeatureSet.RepeatedFieldEncoding? repeatedFieldEncoding = Null;
    wellknown.FeatureSet.Utf8Validation? utf8Validation = Null;
    wellknown.FeatureSet.MessageEncoding? messageEncoding = Null;
    wellknown.FeatureSet.JsonFormat? jsonFormat = Null;
    wellknown.FeatureSet.EnforceNamingStyle? enforceNamingStyle = Null;
    wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility? defaultSymbolVisibility = Null;

    conditional wellknown.FeatureSet.FieldPresence hasFieldPresence() {
        wellknown.FeatureSet.FieldPresence? value = fieldPresence;
        if (value.is(wellknown.FeatureSet.FieldPresence)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.EnumType hasEnumType() {
        wellknown.FeatureSet.EnumType? value = enumType;
        if (value.is(wellknown.FeatureSet.EnumType)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.RepeatedFieldEncoding hasRepeatedFieldEncoding() {
        wellknown.FeatureSet.RepeatedFieldEncoding? value = repeatedFieldEncoding;
        if (value.is(wellknown.FeatureSet.RepeatedFieldEncoding)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.Utf8Validation hasUtf8Validation() {
        wellknown.FeatureSet.Utf8Validation? value = utf8Validation;
        if (value.is(wellknown.FeatureSet.Utf8Validation)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.MessageEncoding hasMessageEncoding() {
        wellknown.FeatureSet.MessageEncoding? value = messageEncoding;
        if (value.is(wellknown.FeatureSet.MessageEncoding)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.JsonFormat hasJsonFormat() {
        wellknown.FeatureSet.JsonFormat? value = jsonFormat;
        if (value.is(wellknown.FeatureSet.JsonFormat)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.EnforceNamingStyle hasEnforceNamingStyle() {
        wellknown.FeatureSet.EnforceNamingStyle? value = enforceNamingStyle;
        if (value.is(wellknown.FeatureSet.EnforceNamingStyle)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility hasDefaultSymbolVisibility() {
        wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility? value = defaultSymbolVisibility;
        if (value.is(wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility)) {
            return True, value;
        }
        return False;
    }
    // ----- enum FieldPresence --------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * FieldPresence defined in the proto file google/protobuf/descriptor.proto
     */
    enum FieldPresence
            implements protobuf.ProtoEnum {
        FieldPresenceUnknown(0),
        Explicit(1),
        Implicit(2),
        LegacyRequired(3);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum EnumType -------------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * EnumType defined in the proto file google/protobuf/descriptor.proto
     */
    enum EnumType
            implements protobuf.ProtoEnum {
        EnumTypeUnknown(0),
        Open(1),
        Closed(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum RepeatedFieldEncoding ------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * RepeatedFieldEncoding defined in the proto file google/protobuf/descriptor.proto
     */
    enum RepeatedFieldEncoding
            implements protobuf.ProtoEnum {
        RepeatedFieldEncodingUnknown(0),
        Packed(1),
        Expanded(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum Utf8Validation -------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * Utf8Validation defined in the proto file google/protobuf/descriptor.proto
     */
    enum Utf8Validation
            implements protobuf.ProtoEnum {
        Utf8ValidationUnknown(0),
        Verify(2),
        None(3);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum MessageEncoding ------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * MessageEncoding defined in the proto file google/protobuf/descriptor.proto
     */
    enum MessageEncoding
            implements protobuf.ProtoEnum {
        MessageEncodingUnknown(0),
        LengthPrefixed(1),
        Delimited(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum JsonFormat -----------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * JsonFormat defined in the proto file google/protobuf/descriptor.proto
     */
    enum JsonFormat
            implements protobuf.ProtoEnum {
        JsonFormatUnknown(0),
        Allow(1),
        LegacyBestEffort(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum EnforceNamingStyle ---------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * EnforceNamingStyle defined in the proto file google/protobuf/descriptor.proto
     */
    enum EnforceNamingStyle
            implements protobuf.ProtoEnum {
        EnforceNamingStyleUnknown(0),
        Style2024(1),
        StyleLegacy(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- message VisibilityFeature -------------------------------------------------------------

    /**
     * This class has been generated by the Ecstasy protoc plugin from the message type
     * VisibilityFeature defined in the proto file google/protobuf/descriptor.proto
     */
    static class VisibilityFeature
            extends protobuf.AbstractMessage {
        construct() {
            construct protobuf.AbstractMessage();
        }

        @Override
        construct(VisibilityFeature other) {
            construct protobuf.AbstractMessage(other);
        }

        // ----- enum DefaultSymbolVisibility ------------------------------------------------------

        /**
         * This enum has been generated by the Ecstasy protoc plugin from the message type
         * DefaultSymbolVisibility defined in the proto file google/protobuf/descriptor.proto
         */
        enum DefaultSymbolVisibility
                implements protobuf.ProtoEnum {
            DefaultSymbolVisibilityUnknown(0),
            /**
             * Default pre-EDITION_2024, all UNSET visibility are export.
             */
            ExportAll(1),
            /**
             * All top-level symbols default to export, nested default to local.
             */
            ExportTopLevel(2),
            /**
             * All symbols default to local.
             */
            LocalAll(3),
            /**
             * All symbols local by default. Nested types cannot be exported.
             * With special case caveat for message { enum {} reserved 1 to max; }
             * This is the recommended setting for new protos.
             */
            Strict(4);

            construct(Int protoValue) {
                this.protoValue = protoValue;
            }

            @Override
            Int protoValue;
        }
        // ----- serialization ---------------------------------------------------------------------

        @Override
        Boolean parseField(protobuf.CodedInput input, Int tag) {
            return False;
        }

        @Override
        void writeKnownFields(protobuf.CodedOutput out) {
        }

        @Override
        Int knownFieldsSize() {
            Int size = 0;
            return size;
        }

        @Override
        VisibilityFeature! mergeFrom(VisibilityFeature other) {
            if (this.is(immutable)) {
                return new VisibilityFeature(this).mergeFrom(other);
            }
            super(other);
            return this;
        }

        @Override
        immutable VisibilityFeature freeze(Boolean inPlace = False) {
            if (this.is(immutable VisibilityFeature)) {
                return this;
            }
            if (!inPlace) {
                return new VisibilityFeature(this).freeze(True);
            }
            unknownFields.freeze(True);
            return this.makeImmutable();
        }
    }

    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            if (wellknown.FeatureSet.FieldPresence v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.FieldPresence.values, input.readEnum())) {
                fieldPresence = v;
            }
            return True;

        case 2:
            if (wellknown.FeatureSet.EnumType v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.EnumType.values, input.readEnum())) {
                enumType = v;
            }
            return True;

        case 3:
            if (wellknown.FeatureSet.RepeatedFieldEncoding v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.RepeatedFieldEncoding.values, input.readEnum())) {
                repeatedFieldEncoding = v;
            }
            return True;

        case 4:
            if (wellknown.FeatureSet.Utf8Validation v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.Utf8Validation.values, input.readEnum())) {
                utf8Validation = v;
            }
            return True;

        case 5:
            if (wellknown.FeatureSet.MessageEncoding v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.MessageEncoding.values, input.readEnum())) {
                messageEncoding = v;
            }
            return True;

        case 6:
            if (wellknown.FeatureSet.JsonFormat v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.JsonFormat.values, input.readEnum())) {
                jsonFormat = v;
            }
            return True;

        case 7:
            if (wellknown.FeatureSet.EnforceNamingStyle v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.EnforceNamingStyle.values, input.readEnum())) {
                enforceNamingStyle = v;
            }
            return True;

        case 8:
            if (wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility v := protobuf.ProtoEnum.byProtoValue(wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility.values, input.readEnum())) {
                defaultSymbolVisibility = v;
            }
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        wellknown.FeatureSet.FieldPresence? fieldPresence = this.fieldPresence;
        if (fieldPresence != Null) {
            out.writeEnum(1, fieldPresence);
        }
        wellknown.FeatureSet.EnumType? enumType = this.enumType;
        if (enumType != Null) {
            out.writeEnum(2, enumType);
        }
        wellknown.FeatureSet.RepeatedFieldEncoding? repeatedFieldEncoding = this.repeatedFieldEncoding;
        if (repeatedFieldEncoding != Null) {
            out.writeEnum(3, repeatedFieldEncoding);
        }
        wellknown.FeatureSet.Utf8Validation? utf8Validation = this.utf8Validation;
        if (utf8Validation != Null) {
            out.writeEnum(4, utf8Validation);
        }
        wellknown.FeatureSet.MessageEncoding? messageEncoding = this.messageEncoding;
        if (messageEncoding != Null) {
            out.writeEnum(5, messageEncoding);
        }
        wellknown.FeatureSet.JsonFormat? jsonFormat = this.jsonFormat;
        if (jsonFormat != Null) {
            out.writeEnum(6, jsonFormat);
        }
        wellknown.FeatureSet.EnforceNamingStyle? enforceNamingStyle = this.enforceNamingStyle;
        if (enforceNamingStyle != Null) {
            out.writeEnum(7, enforceNamingStyle);
        }
        wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility? defaultSymbolVisibility = this.defaultSymbolVisibility;
        if (defaultSymbolVisibility != Null) {
            out.writeEnum(8, defaultSymbolVisibility);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        wellknown.FeatureSet.FieldPresence? fieldPresence = this.fieldPresence;
        if (fieldPresence != Null) {
            size += protobuf.CodedOutput.computeEnumSize(1, fieldPresence);
        }
        wellknown.FeatureSet.EnumType? enumType = this.enumType;
        if (enumType != Null) {
            size += protobuf.CodedOutput.computeEnumSize(2, enumType);
        }
        wellknown.FeatureSet.RepeatedFieldEncoding? repeatedFieldEncoding = this.repeatedFieldEncoding;
        if (repeatedFieldEncoding != Null) {
            size += protobuf.CodedOutput.computeEnumSize(3, repeatedFieldEncoding);
        }
        wellknown.FeatureSet.Utf8Validation? utf8Validation = this.utf8Validation;
        if (utf8Validation != Null) {
            size += protobuf.CodedOutput.computeEnumSize(4, utf8Validation);
        }
        wellknown.FeatureSet.MessageEncoding? messageEncoding = this.messageEncoding;
        if (messageEncoding != Null) {
            size += protobuf.CodedOutput.computeEnumSize(5, messageEncoding);
        }
        wellknown.FeatureSet.JsonFormat? jsonFormat = this.jsonFormat;
        if (jsonFormat != Null) {
            size += protobuf.CodedOutput.computeEnumSize(6, jsonFormat);
        }
        wellknown.FeatureSet.EnforceNamingStyle? enforceNamingStyle = this.enforceNamingStyle;
        if (enforceNamingStyle != Null) {
            size += protobuf.CodedOutput.computeEnumSize(7, enforceNamingStyle);
        }
        wellknown.FeatureSet.VisibilityFeature.DefaultSymbolVisibility? defaultSymbolVisibility = this.defaultSymbolVisibility;
        if (defaultSymbolVisibility != Null) {
            size += protobuf.CodedOutput.computeEnumSize(8, defaultSymbolVisibility);
        }
        return size;
    }

    @Override
    FeatureSet! mergeFrom(FeatureSet other) {
        if (this.is(immutable)) {
            return new FeatureSet(this).mergeFrom(other);
        }
        if (other.fieldPresence != Null) {
            fieldPresence = other.fieldPresence;
        }
        if (other.enumType != Null) {
            enumType = other.enumType;
        }
        if (other.repeatedFieldEncoding != Null) {
            repeatedFieldEncoding = other.repeatedFieldEncoding;
        }
        if (other.utf8Validation != Null) {
            utf8Validation = other.utf8Validation;
        }
        if (other.messageEncoding != Null) {
            messageEncoding = other.messageEncoding;
        }
        if (other.jsonFormat != Null) {
            jsonFormat = other.jsonFormat;
        }
        if (other.enforceNamingStyle != Null) {
            enforceNamingStyle = other.enforceNamingStyle;
        }
        if (other.defaultSymbolVisibility != Null) {
            defaultSymbolVisibility = other.defaultSymbolVisibility;
        }
        super(other);
        return this;
    }

    @Override
    immutable FeatureSet freeze(Boolean inPlace = False) {
        if (this.is(immutable FeatureSet)) {
            return this;
        }
        if (!inPlace) {
            return new FeatureSet(this).freeze(True);
        }
        unknownFields.freeze(True);
        return this.makeImmutable();
    }
}
