/**
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * FieldOptions defined in the proto file google/protobuf/descriptor.proto
 */
@protobuf.WellKnownLocation("google.protobuf.FieldOptions")
class FieldOptions
        extends protobuf.AbstractMessage {
    construct(
            wellknown.FieldOptions.CType? ctype = Null,
            Boolean? packed = Null,
            wellknown.FieldOptions.JSType? jstype = Null,
            Boolean? lazy = Null,
            Boolean? unverifiedLazy = Null,
            Boolean? deprecated = Null,
            Boolean? weak = Null,
            Boolean? debugRedact = Null,
            wellknown.FieldOptions.OptionRetention? retention = Null,
            wellknown.FieldOptions.OptionTargetType[] targets = [],
            wellknown.FieldOptions.EditionDefault[] editionDefaults = [],
            protobuf.wellknown.FeatureSet? features = Null,
            wellknown.FieldOptions.FeatureSupport? featureSupport = Null,
            protobuf.wellknown.UninterpretedOption[] uninterpretedOption = []) {
        construct protobuf.AbstractMessage();
        this.ctype = ctype;
        this.jstype = jstype;
        this.retention = retention;
        this.targets = targets;
        this.editionDefaults = editionDefaults;
        this.features = features;
        this.featureSupport = featureSupport;
        this.uninterpretedOption = uninterpretedOption;
    } finally {
        this.packed ?= packed;
        this.lazy ?= lazy;
        this.unverifiedLazy ?= unverifiedLazy;
        this.deprecated ?= deprecated;
        this.weak ?= weak;
        this.debugRedact ?= debugRedact;
    }

    @Override
    construct(FieldOptions other) {
        construct protobuf.AbstractMessage(other);
        ctype = other.ctype;
        _packed = other.packed;
        jstype = other.jstype;
        _lazy = other.lazy;
        _unverifiedLazy = other.unverifiedLazy;
        _deprecated = other.deprecated;
        _weak = other.weak;
        _debugRedact = other.debugRedact;
        retention = other.retention;
        targets = other.targets.duplicate();
        editionDefaults = other.editionDefaults.duplicate();
        features = other.features;
        featureSupport = other.featureSupport;
        uninterpretedOption = other.uninterpretedOption.duplicate();
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    /**
     * NOTE: ctype is deprecated. Use `features.(pb.cpp).string_type` instead.
     * The ctype option instructs the C++ code generator to use a different
     * representation of the field than it normally would.  See the specific
     * options below.  This option is only implemented to support use of
     * [ctype=CORD] and [ctype=STRING] (the default) on non-repeated fields of
     * type "bytes" in the open source release.
     * TODO: make ctype actually deprecated.
     */
    wellknown.FieldOptions.CType? ctype = Null;

    /**
     * Internal storage for the packed field.
     */
    private Boolean _packed = False;

    /**
     * The packed option can be enabled for repeated primitive fields to enable
     * a more efficient representation on the wire. Rather than repeatedly
     * writing the tag and type for each element, the entire array is encoded as
     * a single length-delimited blob. In proto3, only explicit setting it to
     * false will avoid using packed encoding.  This option is prohibited in
     * Editions, but the `repeated_field_encoding` feature can be used to control
     * the behavior.
     */
    Boolean packed {
        @Override
        Boolean get() {
            return _packed;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x01;
            _packed = value;
        }
    }

    /**
     * The jstype option determines the JavaScript type used for values of the
     * field.  The option is permitted only for 64 bit integral and fixed types
     * (int64, uint64, sint64, fixed64, sfixed64).  A field with jstype JS_STRING
     * is represented as JavaScript string, which avoids loss of precision that
     * can happen when a large value is converted to a floating point JavaScript.
     * Specifying JS_NUMBER for the jstype causes the generated JavaScript code to
     * use the JavaScript "number" type.  The behavior of the default option
     * JS_NORMAL is implementation dependent.
     *
     * This option is an enum to permit additional types to be added, e.g.
     * goog.math.Integer.
     */
    wellknown.FieldOptions.JSType? jstype = Null;

    /**
     * Internal storage for the lazy field.
     */
    private Boolean _lazy = False;

    /**
     * Should this field be parsed lazily?  Lazy applies only to message-type
     * fields.  It means that when the outer message is initially parsed, the
     * inner message's contents will not be parsed but instead stored in encoded
     * form.  The inner message will actually be parsed when it is first accessed.
     *
     * This is only a hint.  Implementations are free to choose whether to use
     * eager or lazy parsing regardless of the value of this option.  However,
     * setting this option true suggests that the protocol author believes that
     * using lazy parsing on this field is worth the additional bookkeeping
     * overhead typically needed to implement it.
     *
     * This option does not affect the public interface of any generated code;
     * all method signatures remain the same.  Furthermore, thread-safety of the
     * interface is not affected by this option; const methods remain safe to
     * call from multiple threads concurrently, while non-const methods continue
     * to require exclusive access.
     *
     * Note that lazy message fields are still eagerly verified to check
     * ill-formed wireformat or missing required fields. Calling IsInitialized()
     * on the outer message would fail if the inner message has missing required
     * fields. Failed verification would result in parsing failure (except when
     * uninitialized messages are acceptable).
     */
    Boolean lazy {
        @Override
        Boolean get() {
            return _lazy;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x02;
            _lazy = value;
        }
    }

    /**
     * Internal storage for the unverified_lazy field.
     */
    private Boolean _unverifiedLazy = False;

    /**
     * unverified_lazy does no correctness checks on the byte stream. This should
     * only be used where lazy with verification is prohibitive for performance
     * reasons.
     */
    Boolean unverifiedLazy {
        @Override
        Boolean get() {
            return _unverifiedLazy;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x04;
            _unverifiedLazy = value;
        }
    }

    /**
     * Internal storage for the deprecated field.
     */
    private Boolean _deprecated = False;

    /**
     * Is this field deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for accessors, or it will be completely ignored; in the very least, this
     * is a formalization for deprecating fields.
     */
    Boolean deprecated {
        @Override
        Boolean get() {
            return _deprecated;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x08;
            _deprecated = value;
        }
    }

    /**
     * Internal storage for the weak field.
     */
    private Boolean _weak = False;

    /**
     * DEPRECATED. DO NOT USE!
     * For Google-internal migration only. Do not use.
     */
    Boolean weak {
        @Override
        Boolean get() {
            return _weak;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x10;
            _weak = value;
        }
    }

    /**
     * Internal storage for the debug_redact field.
     */
    private Boolean _debugRedact = False;

    /**
     * Indicate that the field value should not be printed out when using debug
     * formats, e.g. when the field contains sensitive credentials.
     */
    Boolean debugRedact {
        @Override
        Boolean get() {
            return _debugRedact;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x20;
            _debugRedact = value;
        }
    }

    wellknown.FieldOptions.OptionRetention? retention = Null;

    wellknown.FieldOptions.OptionTargetType[] targets = [];

    wellknown.FieldOptions.EditionDefault[] editionDefaults = [];

    /**
     * Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     */
    protobuf.wellknown.FeatureSet? features = Null;

    wellknown.FieldOptions.FeatureSupport? featureSupport = Null;

    /**
     * The parser stores options it doesn't recognize here. See above.
     */
    protobuf.wellknown.UninterpretedOption[] uninterpretedOption = [];


    conditional Boolean hasPacked() {
        if (presentBits_0 & 0x01 != 0) {
            return True, packed;
        }
        return False;
    }

    conditional Boolean hasLazy() {
        if (presentBits_0 & 0x02 != 0) {
            return True, lazy;
        }
        return False;
    }

    conditional Boolean hasUnverifiedLazy() {
        if (presentBits_0 & 0x04 != 0) {
            return True, unverifiedLazy;
        }
        return False;
    }

    conditional Boolean hasDeprecated() {
        if (presentBits_0 & 0x08 != 0) {
            return True, deprecated;
        }
        return False;
    }

    conditional Boolean hasWeak() {
        if (presentBits_0 & 0x10 != 0) {
            return True, weak;
        }
        return False;
    }

    conditional Boolean hasDebugRedact() {
        if (presentBits_0 & 0x20 != 0) {
            return True, debugRedact;
        }
        return False;
    }

    conditional wellknown.FieldOptions.CType hasCtype() {
        wellknown.FieldOptions.CType? value = ctype;
        if (value.is(wellknown.FieldOptions.CType)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FieldOptions.JSType hasJstype() {
        wellknown.FieldOptions.JSType? value = jstype;
        if (value.is(wellknown.FieldOptions.JSType)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FieldOptions.OptionRetention hasRetention() {
        wellknown.FieldOptions.OptionRetention? value = retention;
        if (value.is(wellknown.FieldOptions.OptionRetention)) {
            return True, value;
        }
        return False;
    }
    conditional protobuf.wellknown.FeatureSet hasFeatures() {
        protobuf.wellknown.FeatureSet? value = features;
        if (value.is(protobuf.wellknown.FeatureSet)) {
            return True, value;
        }
        return False;
    }
    conditional wellknown.FieldOptions.FeatureSupport hasFeatureSupport() {
        wellknown.FieldOptions.FeatureSupport? value = featureSupport;
        if (value.is(wellknown.FieldOptions.FeatureSupport)) {
            return True, value;
        }
        return False;
    }
    // ----- enum CType ----------------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * CType defined in the proto file google/protobuf/descriptor.proto
     */
    enum CType
            implements protobuf.ProtoEnum {
        /**
         * Default mode.
         */
        String(0),
        /**
         * The option [ctype=CORD] may be applied to a non-repeated field of type
         * "bytes". It indicates that in C++, the data should be stored in a Cord
         * instead of a string.  For very large strings, this may reduce memory
         * fragmentation. It may also allow better performance when parsing from a
         * Cord, or when parsing with aliasing enabled, as the parsed Cord may then
         * alias the original buffer.
         */
        Cord(1),
        StringPiece(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum JSType ---------------------------------------------------------------------------

    /**
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * JSType defined in the proto file google/protobuf/descriptor.proto
     */
    enum JSType
            implements protobuf.ProtoEnum {
        /**
         * Use the default type.
         */
        JsNormal(0),
        /**
         * Use JavaScript strings.
         */
        JsString(1),
        /**
         * Use JavaScript numbers.
         */
        JsNumber(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum OptionRetention ------------------------------------------------------------------

    /**
     * If set to RETENTION_SOURCE, the option will be omitted from the binary.
     *
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * OptionRetention defined in the proto file google/protobuf/descriptor.proto
     */
    enum OptionRetention
            implements protobuf.ProtoEnum {
        RetentionUnknown(0),
        RetentionRuntime(1),
        RetentionSource(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- enum OptionTargetType -----------------------------------------------------------------

    /**
     * This indicates the types of entities that the field may apply to when used
     * as an option. If it is unset, then the field may be freely used as an
     * option on any kind of entity.
     *
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * OptionTargetType defined in the proto file google/protobuf/descriptor.proto
     */
    enum OptionTargetType
            implements protobuf.ProtoEnum {
        TargetTypeUnknown(0),
        TargetTypeFile(1),
        TargetTypeExtensionRange(2),
        TargetTypeMessage(3),
        TargetTypeField(4),
        TargetTypeOneof(5),
        TargetTypeEnum(6),
        TargetTypeEnumEntry(7),
        TargetTypeService(8),
        TargetTypeMethod(9);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }
    // ----- message EditionDefault ----------------------------------------------------------------

    /**
     * This class has been generated by the Ecstasy protoc plugin from the message type
     * EditionDefault defined in the proto file google/protobuf/descriptor.proto
     */
    static class EditionDefault
            extends protobuf.AbstractMessage {
        construct(
                    wellknown.Edition? edition = Null,
                    String? value = Null) {
            construct protobuf.AbstractMessage();
            this.edition = edition;
        } finally {
            this.value ?= value;
        }

        @Override
        construct(EditionDefault other) {
            construct protobuf.AbstractMessage(other);
            edition = other.edition;
            _value = other.value;
            presentBits_0 = other.presentBits_0;
        }

        private Int presentBits_0 = 0;

        wellknown.Edition? edition = Null;

        /**
         * Internal storage for the value field.
         */
        private String _value = "";

        String value {
            @Override
            String get() {
                return _value;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x01;
                _value = value;
            }
        }


        conditional String hasValue() {
            if (presentBits_0 & 0x01 != 0) {
                return True, value;
            }
            return False;
        }

        conditional wellknown.Edition hasEdition() {
            wellknown.Edition? value = edition;
            if (value.is(wellknown.Edition)) {
                return True, value;
            }
            return False;
        }

        // ----- serialization ---------------------------------------------------------------------

        @Override
        Boolean parseField(protobuf.CodedInput input, Int tag) {
            switch (protobuf.WireType.getFieldNumber(tag)) {
            case 3:
                if (wellknown.Edition v := protobuf.ProtoEnum.byProtoValue(wellknown.Edition.values, input.readEnum())) {
                    edition = v;
                }
                return True;

            case 2:
                value = input.readString();
                return True;
            }
            return False;
        }

        @Override
        void writeKnownFields(protobuf.CodedOutput out) {
            wellknown.Edition? edition = this.edition;
            if (edition != Null) {
                out.writeEnum(3, edition);
            }
            if (presentBits_0 & 0x01 != 0) {
                out.writeString(2, value);
            }
        }

        @Override
        Int knownFieldsSize() {
            Int size = 0;
            wellknown.Edition? edition = this.edition;
            if (edition != Null) {
                size += protobuf.CodedOutput.computeEnumSize(3, edition);
            }
            if (presentBits_0 & 0x01 != 0) {
                size += protobuf.CodedOutput.computeStringSize(2, value);
            }
            return size;
        }

        @Override
        EditionDefault! mergeFrom(EditionDefault other) {
            if (this.is(immutable)) {
                return new EditionDefault(this).mergeFrom(other);
            }
            if (other.edition != Null) {
                edition = other.edition;
            }
            if (other.presentBits_0 & 0x01 != 0) {
                _value = other._value;
                presentBits_0 |= 0x01;
            }
            super(other);
            return this;
        }

        @Override
        immutable EditionDefault freeze(Boolean inPlace = False) {
            if (this.is(immutable EditionDefault)) {
                return this;
            }
            if (!inPlace) {
                return new EditionDefault(this).freeze(True);
            }
            unknownFields.freeze(True);
            return this.makeImmutable();
        }
    }

    // ----- message FeatureSupport ----------------------------------------------------------------

    /**
     * Information about the support window of a feature.
     *
     * This class has been generated by the Ecstasy protoc plugin from the message type
     * FeatureSupport defined in the proto file google/protobuf/descriptor.proto
     */
    static class FeatureSupport
            extends protobuf.AbstractMessage {
        construct(
                    wellknown.Edition? editionIntroduced = Null,
                    wellknown.Edition? editionDeprecated = Null,
                    String? deprecationWarning = Null,
                    wellknown.Edition? editionRemoved = Null,
                    String? removalError = Null) {
            construct protobuf.AbstractMessage();
            this.editionIntroduced = editionIntroduced;
            this.editionDeprecated = editionDeprecated;
            this.editionRemoved = editionRemoved;
        } finally {
            this.deprecationWarning ?= deprecationWarning;
            this.removalError ?= removalError;
        }

        @Override
        construct(FeatureSupport other) {
            construct protobuf.AbstractMessage(other);
            editionIntroduced = other.editionIntroduced;
            editionDeprecated = other.editionDeprecated;
            _deprecationWarning = other.deprecationWarning;
            editionRemoved = other.editionRemoved;
            _removalError = other.removalError;
            presentBits_0 = other.presentBits_0;
        }

        private Int presentBits_0 = 0;

        /**
         * The edition that this feature was first available in.  In editions
         * earlier than this one, the default assigned to EDITION_LEGACY will be
         * used, and proto files will not be able to override it.
         */
        wellknown.Edition? editionIntroduced = Null;

        /**
         * The edition this feature becomes deprecated in.  Using this after this
         * edition may trigger warnings.
         */
        wellknown.Edition? editionDeprecated = Null;

        /**
         * Internal storage for the deprecation_warning field.
         */
        private String _deprecationWarning = "";

        /**
         * The deprecation warning text if this feature is used after the edition it
         * was marked deprecated in.
         */
        String deprecationWarning {
            @Override
            String get() {
                return _deprecationWarning;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x01;
                _deprecationWarning = value;
            }
        }

        /**
         * The edition this feature is no longer available in.  In editions after
         * this one, the last default assigned will be used, and proto files will
         * not be able to override it.
         */
        wellknown.Edition? editionRemoved = Null;

        /**
         * Internal storage for the removal_error field.
         */
        private String _removalError = "";

        /**
         * The removal error text if this feature is used after the edition it was
         * removed in.
         */
        String removalError {
            @Override
            String get() {
                return _removalError;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x02;
                _removalError = value;
            }
        }


        conditional String hasDeprecationWarning() {
            if (presentBits_0 & 0x01 != 0) {
                return True, deprecationWarning;
            }
            return False;
        }

        conditional String hasRemovalError() {
            if (presentBits_0 & 0x02 != 0) {
                return True, removalError;
            }
            return False;
        }

        conditional wellknown.Edition hasEditionIntroduced() {
            wellknown.Edition? value = editionIntroduced;
            if (value.is(wellknown.Edition)) {
                return True, value;
            }
            return False;
        }
        conditional wellknown.Edition hasEditionDeprecated() {
            wellknown.Edition? value = editionDeprecated;
            if (value.is(wellknown.Edition)) {
                return True, value;
            }
            return False;
        }
        conditional wellknown.Edition hasEditionRemoved() {
            wellknown.Edition? value = editionRemoved;
            if (value.is(wellknown.Edition)) {
                return True, value;
            }
            return False;
        }

        // ----- serialization ---------------------------------------------------------------------

        @Override
        Boolean parseField(protobuf.CodedInput input, Int tag) {
            switch (protobuf.WireType.getFieldNumber(tag)) {
            case 1:
                if (wellknown.Edition v := protobuf.ProtoEnum.byProtoValue(wellknown.Edition.values, input.readEnum())) {
                    editionIntroduced = v;
                }
                return True;

            case 2:
                if (wellknown.Edition v := protobuf.ProtoEnum.byProtoValue(wellknown.Edition.values, input.readEnum())) {
                    editionDeprecated = v;
                }
                return True;

            case 3:
                deprecationWarning = input.readString();
                return True;

            case 4:
                if (wellknown.Edition v := protobuf.ProtoEnum.byProtoValue(wellknown.Edition.values, input.readEnum())) {
                    editionRemoved = v;
                }
                return True;

            case 5:
                removalError = input.readString();
                return True;
            }
            return False;
        }

        @Override
        void writeKnownFields(protobuf.CodedOutput out) {
            wellknown.Edition? editionIntroduced = this.editionIntroduced;
            if (editionIntroduced != Null) {
                out.writeEnum(1, editionIntroduced);
            }
            wellknown.Edition? editionDeprecated = this.editionDeprecated;
            if (editionDeprecated != Null) {
                out.writeEnum(2, editionDeprecated);
            }
            if (presentBits_0 & 0x01 != 0) {
                out.writeString(3, deprecationWarning);
            }
            wellknown.Edition? editionRemoved = this.editionRemoved;
            if (editionRemoved != Null) {
                out.writeEnum(4, editionRemoved);
            }
            if (presentBits_0 & 0x02 != 0) {
                out.writeString(5, removalError);
            }
        }

        @Override
        Int knownFieldsSize() {
            Int size = 0;
            wellknown.Edition? editionIntroduced = this.editionIntroduced;
            if (editionIntroduced != Null) {
                size += protobuf.CodedOutput.computeEnumSize(1, editionIntroduced);
            }
            wellknown.Edition? editionDeprecated = this.editionDeprecated;
            if (editionDeprecated != Null) {
                size += protobuf.CodedOutput.computeEnumSize(2, editionDeprecated);
            }
            if (presentBits_0 & 0x01 != 0) {
                size += protobuf.CodedOutput.computeStringSize(3, deprecationWarning);
            }
            wellknown.Edition? editionRemoved = this.editionRemoved;
            if (editionRemoved != Null) {
                size += protobuf.CodedOutput.computeEnumSize(4, editionRemoved);
            }
            if (presentBits_0 & 0x02 != 0) {
                size += protobuf.CodedOutput.computeStringSize(5, removalError);
            }
            return size;
        }

        @Override
        FeatureSupport! mergeFrom(FeatureSupport other) {
            if (this.is(immutable)) {
                return new FeatureSupport(this).mergeFrom(other);
            }
            if (other.editionIntroduced != Null) {
                editionIntroduced = other.editionIntroduced;
            }
            if (other.editionDeprecated != Null) {
                editionDeprecated = other.editionDeprecated;
            }
            if (other.presentBits_0 & 0x01 != 0) {
                _deprecationWarning = other._deprecationWarning;
                presentBits_0 |= 0x01;
            }
            if (other.editionRemoved != Null) {
                editionRemoved = other.editionRemoved;
            }
            if (other.presentBits_0 & 0x02 != 0) {
                _removalError = other._removalError;
                presentBits_0 |= 0x02;
            }
            super(other);
            return this;
        }

        @Override
        immutable FeatureSupport freeze(Boolean inPlace = False) {
            if (this.is(immutable FeatureSupport)) {
                return this;
            }
            if (!inPlace) {
                return new FeatureSupport(this).freeze(True);
            }
            unknownFields.freeze(True);
            return this.makeImmutable();
        }
    }


    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            if (wellknown.FieldOptions.CType v := protobuf.ProtoEnum.byProtoValue(wellknown.FieldOptions.CType.values, input.readEnum())) {
                ctype = v;
            }
            return True;

        case 2:
            packed = input.readBool();
            return True;

        case 6:
            if (wellknown.FieldOptions.JSType v := protobuf.ProtoEnum.byProtoValue(wellknown.FieldOptions.JSType.values, input.readEnum())) {
                jstype = v;
            }
            return True;

        case 5:
            lazy = input.readBool();
            return True;

        case 15:
            unverifiedLazy = input.readBool();
            return True;

        case 3:
            deprecated = input.readBool();
            return True;

        case 10:
            weak = input.readBool();
            return True;

        case 16:
            debugRedact = input.readBool();
            return True;

        case 17:
            if (wellknown.FieldOptions.OptionRetention v := protobuf.ProtoEnum.byProtoValue(wellknown.FieldOptions.OptionRetention.values, input.readEnum())) {
                retention = v;
            }
            return True;

        case 19:
            if (targets.is(immutable)) {
                targets = new ecstasy.collections.Array(Mutable, targets);
            }
            if (protobuf.WireType.getWireType(tag) == protobuf.WireType.LEN) {
                for (Int32 raw : input.readPackedInt32s()) {
                    if (wellknown.FieldOptions.OptionTargetType v := protobuf.ProtoEnum.byProtoValue(wellknown.FieldOptions.OptionTargetType.values, raw)) {
                        targets.add(v);
                    }
                }
            } else {
                if (wellknown.FieldOptions.OptionTargetType v := protobuf.ProtoEnum.byProtoValue(wellknown.FieldOptions.OptionTargetType.values, input.readEnum())) {
                    targets.add(v);
                }
            }            return True;

        case 20:
            if (editionDefaults.is(immutable)) {
                editionDefaults = new ecstasy.collections.Array(Mutable, editionDefaults);
            }
            wellknown.FieldOptions.EditionDefault elem = new wellknown.FieldOptions.EditionDefault();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            editionDefaults.add(elem);
            return True;

        case 21:
            protobuf.wellknown.FeatureSet msg = new protobuf.wellknown.FeatureSet();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            features = msg;
                        return True;

        case 22:
            wellknown.FieldOptions.FeatureSupport msg = new wellknown.FieldOptions.FeatureSupport();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            featureSupport = msg;
                        return True;

        case 999:
            if (uninterpretedOption.is(immutable)) {
                uninterpretedOption = new ecstasy.collections.Array(Mutable, uninterpretedOption);
            }
            protobuf.wellknown.UninterpretedOption elem = new protobuf.wellknown.UninterpretedOption();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            uninterpretedOption.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        wellknown.FieldOptions.CType? ctype = this.ctype;
        if (ctype != Null) {
            out.writeEnum(1, ctype);
        }
        if (presentBits_0 & 0x01 != 0) {
            out.writeBool(2, packed);
        }
        wellknown.FieldOptions.JSType? jstype = this.jstype;
        if (jstype != Null) {
            out.writeEnum(6, jstype);
        }
        if (presentBits_0 & 0x02 != 0) {
            out.writeBool(5, lazy);
        }
        if (presentBits_0 & 0x04 != 0) {
            out.writeBool(15, unverifiedLazy);
        }
        if (presentBits_0 & 0x08 != 0) {
            out.writeBool(3, deprecated);
        }
        if (presentBits_0 & 0x10 != 0) {
            out.writeBool(10, weak);
        }
        if (presentBits_0 & 0x20 != 0) {
            out.writeBool(16, debugRedact);
        }
        wellknown.FieldOptions.OptionRetention? retention = this.retention;
        if (retention != Null) {
            out.writeEnum(17, retention);
        }
        for (wellknown.FieldOptions.OptionTargetType v : targets) {
            out.writeEnum(19, v);
        }
        for (wellknown.FieldOptions.EditionDefault v : editionDefaults) {
            out.writeMessage(20, v);
        }
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            out.writeMessage(21, features);
        }
        wellknown.FieldOptions.FeatureSupport? featureSupport = this.featureSupport;
        if (featureSupport != Null) {
            out.writeMessage(22, featureSupport);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            out.writeMessage(999, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        wellknown.FieldOptions.CType? ctype = this.ctype;
        if (ctype != Null) {
            size += protobuf.CodedOutput.computeEnumSize(1, ctype);
        }
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(2);
        }
        wellknown.FieldOptions.JSType? jstype = this.jstype;
        if (jstype != Null) {
            size += protobuf.CodedOutput.computeEnumSize(6, jstype);
        }
        if (presentBits_0 & 0x02 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(5);
        }
        if (presentBits_0 & 0x04 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(15);
        }
        if (presentBits_0 & 0x08 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(3);
        }
        if (presentBits_0 & 0x10 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(10);
        }
        if (presentBits_0 & 0x20 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(16);
        }
        wellknown.FieldOptions.OptionRetention? retention = this.retention;
        if (retention != Null) {
            size += protobuf.CodedOutput.computeEnumSize(17, retention);
        }
        for (wellknown.FieldOptions.OptionTargetType v : targets) {
            size += protobuf.CodedOutput.computeEnumSize(19, v);
        }
        for (wellknown.FieldOptions.EditionDefault v : editionDefaults) {
            size += protobuf.CodedOutput.computeMessageSize(20, v);
        }
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            size += protobuf.CodedOutput.computeMessageSize(21, features);
        }
        wellknown.FieldOptions.FeatureSupport? featureSupport = this.featureSupport;
        if (featureSupport != Null) {
            size += protobuf.CodedOutput.computeMessageSize(22, featureSupport);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            size += protobuf.CodedOutput.computeMessageSize(999, v);
        }
        return size;
    }

    @Override
    FieldOptions! mergeFrom(FieldOptions other) {
        if (this.is(immutable)) {
            return new FieldOptions(this).mergeFrom(other);
        }
        if (other.ctype != Null) {
            ctype = other.ctype;
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _packed = other._packed;
            presentBits_0 |= 0x01;
        }
        if (other.jstype != Null) {
            jstype = other.jstype;
        }
        if (other.presentBits_0 & 0x02 != 0) {
            _lazy = other._lazy;
            presentBits_0 |= 0x02;
        }
        if (other.presentBits_0 & 0x04 != 0) {
            _unverifiedLazy = other._unverifiedLazy;
            presentBits_0 |= 0x04;
        }
        if (other.presentBits_0 & 0x08 != 0) {
            _deprecated = other._deprecated;
            presentBits_0 |= 0x08;
        }
        if (other.presentBits_0 & 0x10 != 0) {
            _weak = other._weak;
            presentBits_0 |= 0x10;
        }
        if (other.presentBits_0 & 0x20 != 0) {
            _debugRedact = other._debugRedact;
            presentBits_0 |= 0x20;
        }
        if (other.retention != Null) {
            retention = other.retention;
        }
        targets.addAll(other.targets);
        editionDefaults.addAll(other.editionDefaults);
        protobuf.wellknown.FeatureSet? _featuresOther = other.features;
        if (_featuresOther != Null) {
            if (other.is(immutable)) {
                features = _featuresOther;
            } else {
                features = _featuresOther.duplicate();
            }
        }
        wellknown.FieldOptions.FeatureSupport? _featureSupportOther = other.featureSupport;
        if (_featureSupportOther != Null) {
            if (other.is(immutable)) {
                featureSupport = _featureSupportOther;
            } else {
                featureSupport = _featureSupportOther.duplicate();
            }
        }
        uninterpretedOption.addAll(other.uninterpretedOption);
        super(other);
        return this;
    }

    @Override
    immutable FieldOptions freeze(Boolean inPlace = False) {
        if (this.is(immutable FieldOptions)) {
            return this;
        }
        if (!inPlace) {
            return new FieldOptions(this).freeze(True);
        }
        unknownFields.freeze(True);
        targets.freeze(True);
        editionDefaults.freeze(True);
        features?.freeze(True);
        featureSupport?.freeze(True);
        uninterpretedOption.freeze(True);
        return this.makeImmutable();
    }
}
