/**
 * Describes the relationship between generated code and its original source
 * file. A GeneratedCodeInfo message is associated with only one generated
 * source file, but may contain references to different source .proto files.
 *
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * GeneratedCodeInfo defined in the proto file google/protobuf/descriptor.proto
 */
@protobuf.WellKnownLocation("google.protobuf.GeneratedCodeInfo")
class GeneratedCodeInfo
        extends protobuf.AbstractMessage {
    construct(
            wellknown.GeneratedCodeInfo.Annotation[] annotation_ = []) {
        construct protobuf.AbstractMessage();
        this.annotation_ = annotation_;
    }

    @Override
    construct(GeneratedCodeInfo other) {
        construct protobuf.AbstractMessage(other);
        annotation_ = other.annotation_.duplicate();
    }

    /**
     * An Annotation connects some span of text in generated code to an element
     * of its generating .proto file.
     */
    wellknown.GeneratedCodeInfo.Annotation[] annotation_ = [];

    // ----- message Annotation --------------------------------------------------------------------

    /**
     * This class has been generated by the Ecstasy protoc plugin from the message type
     * Annotation defined in the proto file google/protobuf/descriptor.proto
     */
    static class Annotation
            extends protobuf.AbstractMessage {
        construct(
                    Int32[] path = [],
                    String? sourceFile = Null,
                    Int32? begin = Null,
                    Int32? end = Null,
                    wellknown.GeneratedCodeInfo.Annotation.Semantic? semantic = Null) {
            construct protobuf.AbstractMessage();
            this.path = path;
            this.semantic = semantic;
        } finally {
            this.sourceFile ?= sourceFile;
            this.begin ?= begin;
            this.end ?= end;
        }

        @Override
        construct(Annotation other) {
            construct protobuf.AbstractMessage(other);
            path = other.path.duplicate();
            _sourceFile = other.sourceFile;
            _begin = other.begin;
            _end = other.end;
            semantic = other.semantic;
            presentBits_0 = other.presentBits_0;
        }

        private Int presentBits_0 = 0;

        /**
         * Identifies the element in the original source .proto file. This field
         * is formatted the same as SourceCodeInfo.Location.path.
         */
        Int32[] path = [];

        /**
         * Internal storage for the source_file field.
         */
        private String _sourceFile = "";

        /**
         * Identifies the filesystem path to the original source .proto.
         */
        String sourceFile {
            @Override
            String get() {
                return _sourceFile;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x01;
                _sourceFile = value;
            }
        }

        /**
         * Internal storage for the begin field.
         */
        private Int32 _begin = 0;

        /**
         * Identifies the starting offset in bytes in the generated code
         * that relates to the identified object.
         */
        Int32 begin {
            @Override
            Int32 get() {
                return _begin;
            }
            @Override
            void set(Int32 value) {
                presentBits_0 |= 0x02;
                _begin = value;
            }
        }

        /**
         * Internal storage for the end field.
         */
        private Int32 _end = 0;

        /**
         * Identifies the ending offset in bytes in the generated code that
         * relates to the identified object. The end offset should be one past
         * the last relevant byte (so the length of the text = end - begin).
         */
        Int32 end {
            @Override
            Int32 get() {
                return _end;
            }
            @Override
            void set(Int32 value) {
                presentBits_0 |= 0x04;
                _end = value;
            }
        }

        wellknown.GeneratedCodeInfo.Annotation.Semantic? semantic = Null;


        conditional String hasSourceFile() {
            if (presentBits_0 & 0x01 != 0) {
                return True, sourceFile;
            }
            return False;
        }

        conditional Int32 hasBegin() {
            if (presentBits_0 & 0x02 != 0) {
                return True, begin;
            }
            return False;
        }

        conditional Int32 hasEnd() {
            if (presentBits_0 & 0x04 != 0) {
                return True, end;
            }
            return False;
        }

        conditional wellknown.GeneratedCodeInfo.Annotation.Semantic hasSemantic() {
            wellknown.GeneratedCodeInfo.Annotation.Semantic? value = semantic;
            if (value.is(wellknown.GeneratedCodeInfo.Annotation.Semantic)) {
                return True, value;
            }
            return False;
        }
        // ----- enum Semantic ---------------------------------------------------------------------

        /**
         * Represents the identified object's effect on the element in the original
         * .proto file.
         *
         * This enum has been generated by the Ecstasy protoc plugin from the message type
         * Semantic defined in the proto file google/protobuf/descriptor.proto
         */
        enum Semantic
                implements protobuf.ProtoEnum {
            /**
             * There is no effect or the effect is indescribable.
             */
            None(0),
            /**
             * The element is set or otherwise mutated.
             */
            Set(1),
            /**
             * An alias to the element is returned.
             */
            Alias(2);

            construct(Int protoValue) {
                this.protoValue = protoValue;
            }

            @Override
            Int protoValue;
        }

        // ----- serialization ---------------------------------------------------------------------

        @Override
        Boolean parseField(protobuf.CodedInput input, Int tag) {
            switch (protobuf.WireType.getFieldNumber(tag)) {
            case 1:
                if (path.is(immutable)) {
                    path = new ecstasy.collections.Array(Mutable, path);
                }
                if (protobuf.WireType.getWireType(tag) == protobuf.WireType.LEN) {
                    path.addAll(input.readPackedInt32s());
                } else {
                    path.add(input.readInt32());
                }                return True;

            case 2:
                sourceFile = input.readString();
                return True;

            case 3:
                begin = input.readInt32();
                return True;

            case 4:
                end = input.readInt32();
                return True;

            case 5:
                if (wellknown.GeneratedCodeInfo.Annotation.Semantic v := protobuf.ProtoEnum.byProtoValue(wellknown.GeneratedCodeInfo.Annotation.Semantic.values, input.readEnum())) {
                    semantic = v;
                }
                return True;
            }
            return False;
        }

        @Override
        void writeKnownFields(protobuf.CodedOutput out) {
            if (!path.empty) {
                out.writePackedVarints(1, path);
            }
            if (presentBits_0 & 0x01 != 0) {
                out.writeString(2, sourceFile);
            }
            if (presentBits_0 & 0x02 != 0) {
                out.writeInt32(3, begin);
            }
            if (presentBits_0 & 0x04 != 0) {
                out.writeInt32(4, end);
            }
            wellknown.GeneratedCodeInfo.Annotation.Semantic? semantic = this.semantic;
            if (semantic != Null) {
                out.writeEnum(5, semantic);
            }
        }

        @Override
        Int knownFieldsSize() {
            Int size = 0;
            if (!path.empty) {
                size += protobuf.CodedOutput.computePackedVarintsSize(1, path);
            }
            if (presentBits_0 & 0x01 != 0) {
                size += protobuf.CodedOutput.computeStringSize(2, sourceFile);
            }
            if (presentBits_0 & 0x02 != 0) {
                size += protobuf.CodedOutput.computeInt32Size(3, begin);
            }
            if (presentBits_0 & 0x04 != 0) {
                size += protobuf.CodedOutput.computeInt32Size(4, end);
            }
            wellknown.GeneratedCodeInfo.Annotation.Semantic? semantic = this.semantic;
            if (semantic != Null) {
                size += protobuf.CodedOutput.computeEnumSize(5, semantic);
            }
            return size;
        }

        @Override
        Annotation! mergeFrom(Annotation other) {
            if (this.is(immutable)) {
                return new Annotation(this).mergeFrom(other);
            }
            path.addAll(other.path);
            if (other.presentBits_0 & 0x01 != 0) {
                _sourceFile = other._sourceFile;
                presentBits_0 |= 0x01;
            }
            if (other.presentBits_0 & 0x02 != 0) {
                _begin = other._begin;
                presentBits_0 |= 0x02;
            }
            if (other.presentBits_0 & 0x04 != 0) {
                _end = other._end;
                presentBits_0 |= 0x04;
            }
            if (other.semantic != Null) {
                semantic = other.semantic;
            }
            super(other);
            return this;
        }

        @Override
        immutable Annotation freeze(Boolean inPlace = False) {
            if (this.is(immutable Annotation)) {
                return this;
            }
            if (!inPlace) {
                return new Annotation(this).freeze(True);
            }
            unknownFields.freeze(True);
            path.freeze(True);
            return this.makeImmutable();
        }
    }


    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            if (annotation_.is(immutable)) {
                annotation_ = new ecstasy.collections.Array(Mutable, annotation_);
            }
            wellknown.GeneratedCodeInfo.Annotation elem = new wellknown.GeneratedCodeInfo.Annotation();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            annotation_.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        for (wellknown.GeneratedCodeInfo.Annotation v : annotation_) {
            out.writeMessage(1, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        for (wellknown.GeneratedCodeInfo.Annotation v : annotation_) {
            size += protobuf.CodedOutput.computeMessageSize(1, v);
        }
        return size;
    }

    @Override
    GeneratedCodeInfo! mergeFrom(GeneratedCodeInfo other) {
        if (this.is(immutable)) {
            return new GeneratedCodeInfo(this).mergeFrom(other);
        }
        annotation_.addAll(other.annotation_);
        super(other);
        return this;
    }

    @Override
    immutable GeneratedCodeInfo freeze(Boolean inPlace = False) {
        if (this.is(immutable GeneratedCodeInfo)) {
            return this;
        }
        if (!inPlace) {
            return new GeneratedCodeInfo(this).freeze(True);
        }
        unknownFields.freeze(True);
        annotation_.freeze(True);
        return this.makeImmutable();
    }
}
