/**
 * Describes a method of a service.
 *
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * MethodDescriptorProto defined in the proto file google/protobuf/descriptor.proto
 */
class MethodDescriptorProto
        extends protobuf.AbstractMessage {
    construct(
            String? name = Null,
            String? inputType = Null,
            String? outputType = Null,
            protobuf.wellknown.MethodOptions? options = Null,
            Boolean? clientStreaming = Null,
            Boolean? serverStreaming = Null) {
        construct protobuf.AbstractMessage();
        this.options = options;
    } finally {
        this.name ?= name;
        this.inputType ?= inputType;
        this.outputType ?= outputType;
        this.clientStreaming ?= clientStreaming;
        this.serverStreaming ?= serverStreaming;
    }

    @Override
    construct(MethodDescriptorProto other) {
        construct protobuf.AbstractMessage(other);
        _name = other.name;
        _inputType = other.inputType;
        _outputType = other.outputType;
        options = other.options;
        _clientStreaming = other.clientStreaming;
        _serverStreaming = other.serverStreaming;
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    /**
     * Internal storage for the name field.
     */
    private String _name = "";

    String name {
        @Override
        String get() {
            return _name;
        }
        @Override
        void set(String value) {
            presentBits_0 |= 0x01;
            _name = value;
        }
    }

    /**
     * Internal storage for the input_type field.
     */
    private String _inputType = "";

    /**
     * Input and output type names.  These are resolved in the same way as
     * FieldDescriptorProto.type_name, but must refer to a message type.
     */
    String inputType {
        @Override
        String get() {
            return _inputType;
        }
        @Override
        void set(String value) {
            presentBits_0 |= 0x02;
            _inputType = value;
        }
    }

    /**
     * Internal storage for the output_type field.
     */
    private String _outputType = "";

    String outputType {
        @Override
        String get() {
            return _outputType;
        }
        @Override
        void set(String value) {
            presentBits_0 |= 0x04;
            _outputType = value;
        }
    }

    protobuf.wellknown.MethodOptions? options = Null;
    /**
     * Internal storage for the client_streaming field.
     */
    private Boolean _clientStreaming = False;

    /**
     * Identifies if client streams multiple client messages
     */
    Boolean clientStreaming {
        @Override
        Boolean get() {
            return _clientStreaming;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x08;
            _clientStreaming = value;
        }
    }

    /**
     * Internal storage for the server_streaming field.
     */
    private Boolean _serverStreaming = False;

    /**
     * Identifies if server streams multiple server messages
     */
    Boolean serverStreaming {
        @Override
        Boolean get() {
            return _serverStreaming;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x10;
            _serverStreaming = value;
        }
    }


    conditional String hasName() {
        if (presentBits_0 & 0x01 != 0) {
            return True, name;
        }
        return False;
    }

    conditional String hasInputType() {
        if (presentBits_0 & 0x02 != 0) {
            return True, inputType;
        }
        return False;
    }

    conditional String hasOutputType() {
        if (presentBits_0 & 0x04 != 0) {
            return True, outputType;
        }
        return False;
    }

    conditional Boolean hasClientStreaming() {
        if (presentBits_0 & 0x08 != 0) {
            return True, clientStreaming;
        }
        return False;
    }

    conditional Boolean hasServerStreaming() {
        if (presentBits_0 & 0x10 != 0) {
            return True, serverStreaming;
        }
        return False;
    }

    conditional protobuf.wellknown.MethodOptions hasOptions() {
        protobuf.wellknown.MethodOptions? value = options;
        if (value.is(protobuf.wellknown.MethodOptions)) {
            return True, value;
        }
        return False;
    }
    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            name = input.readString();
            return True;

        case 2:
            inputType = input.readString();
            return True;

        case 3:
            outputType = input.readString();
            return True;

        case 4:
            protobuf.wellknown.MethodOptions msg = new protobuf.wellknown.MethodOptions();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            options = msg;
                        return True;

        case 5:
            clientStreaming = input.readBool();
            return True;

        case 6:
            serverStreaming = input.readBool();
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        if (presentBits_0 & 0x01 != 0) {
            out.writeString(1, name);
        }
        if (presentBits_0 & 0x02 != 0) {
            out.writeString(2, inputType);
        }
        if (presentBits_0 & 0x04 != 0) {
            out.writeString(3, outputType);
        }
        protobuf.wellknown.MethodOptions? options = this.options;
        if (options != Null) {
            out.writeMessage(4, options);
        }
        if (presentBits_0 & 0x08 != 0) {
            out.writeBool(5, clientStreaming);
        }
        if (presentBits_0 & 0x10 != 0) {
            out.writeBool(6, serverStreaming);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeStringSize(1, name);
        }
        if (presentBits_0 & 0x02 != 0) {
            size += protobuf.CodedOutput.computeStringSize(2, inputType);
        }
        if (presentBits_0 & 0x04 != 0) {
            size += protobuf.CodedOutput.computeStringSize(3, outputType);
        }
        protobuf.wellknown.MethodOptions? options = this.options;
        if (options != Null) {
            size += protobuf.CodedOutput.computeMessageSize(4, options);
        }
        if (presentBits_0 & 0x08 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(5);
        }
        if (presentBits_0 & 0x10 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(6);
        }
        return size;
    }

    @Override
    MethodDescriptorProto! mergeFrom(MethodDescriptorProto other) {
        if (this.is(immutable)) {
            return new MethodDescriptorProto(this).mergeFrom(other);
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _name = other._name;
            presentBits_0 |= 0x01;
        }
        if (other.presentBits_0 & 0x02 != 0) {
            _inputType = other._inputType;
            presentBits_0 |= 0x02;
        }
        if (other.presentBits_0 & 0x04 != 0) {
            _outputType = other._outputType;
            presentBits_0 |= 0x04;
        }
        protobuf.wellknown.MethodOptions? _optionsOther = other.options;
        if (_optionsOther != Null) {
            if (other.is(immutable)) {
                options = _optionsOther;
            } else {
                options = _optionsOther.duplicate();
            }
        }
        if (other.presentBits_0 & 0x08 != 0) {
            _clientStreaming = other._clientStreaming;
            presentBits_0 |= 0x08;
        }
        if (other.presentBits_0 & 0x10 != 0) {
            _serverStreaming = other._serverStreaming;
            presentBits_0 |= 0x10;
        }
        super(other);
        return this;
    }

    @Override
    immutable MethodDescriptorProto freeze(Boolean inPlace = False) {
        if (this.is(immutable MethodDescriptorProto)) {
            return this;
        }
        if (!inPlace) {
            return new MethodDescriptorProto(this).freeze(True);
        }
        unknownFields.freeze(True);
        options?.freeze(True);
        return this.makeImmutable();
    }
}
