/**
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * MethodOptions defined in the proto file google/protobuf/descriptor.proto
 */
@protobuf.WellKnownLocation("google.protobuf.MethodOptions")
class MethodOptions
        extends protobuf.AbstractMessage {
    construct(
            Boolean? deprecated = Null,
            wellknown.MethodOptions.IdempotencyLevel? idempotencyLevel = Null,
            protobuf.wellknown.FeatureSet? features = Null,
            protobuf.wellknown.UninterpretedOption[] uninterpretedOption = []) {
        construct protobuf.AbstractMessage();
        this.idempotencyLevel = idempotencyLevel;
        this.features = features;
        this.uninterpretedOption = uninterpretedOption;
    } finally {
        this.deprecated ?= deprecated;
    }

    @Override
    construct(MethodOptions other) {
        construct protobuf.AbstractMessage(other);
        _deprecated = other.deprecated;
        idempotencyLevel = other.idempotencyLevel;
        features = other.features;
        uninterpretedOption = other.uninterpretedOption.duplicate();
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    /**
     * Internal storage for the deprecated field.
     */
    private Boolean _deprecated = False;

    /**
     * Is this method deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for the method, or it will be completely ignored; in the very least,
     * this is a formalization for deprecating methods.
     */
    Boolean deprecated {
        @Override
        Boolean get() {
            return _deprecated;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x01;
            _deprecated = value;
        }
    }

    wellknown.MethodOptions.IdempotencyLevel? idempotencyLevel = Null;

    /**
     * Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     */
    protobuf.wellknown.FeatureSet? features = Null;

    /**
     * The parser stores options it doesn't recognize here. See above.
     */
    protobuf.wellknown.UninterpretedOption[] uninterpretedOption = [];


    conditional Boolean hasDeprecated() {
        if (presentBits_0 & 0x01 != 0) {
            return True, deprecated;
        }
        return False;
    }

    conditional wellknown.MethodOptions.IdempotencyLevel hasIdempotencyLevel() {
        wellknown.MethodOptions.IdempotencyLevel? value = idempotencyLevel;
        if (value.is(wellknown.MethodOptions.IdempotencyLevel)) {
            return True, value;
        }
        return False;
    }
    conditional protobuf.wellknown.FeatureSet hasFeatures() {
        protobuf.wellknown.FeatureSet? value = features;
        if (value.is(protobuf.wellknown.FeatureSet)) {
            return True, value;
        }
        return False;
    }
    // ----- enum IdempotencyLevel -----------------------------------------------------------------

    /**
     * Is this method side-effect-free (or safe in HTTP parlance), or idempotent,
     * or neither? HTTP based RPC implementation may choose GET verb for safe
     * methods, and PUT verb for idempotent methods instead of the default POST.
     *
     * This enum has been generated by the Ecstasy protoc plugin from the message type
     * IdempotencyLevel defined in the proto file google/protobuf/descriptor.proto
     */
    enum IdempotencyLevel
            implements protobuf.ProtoEnum {
        IdempotencyUnknown(0),
        NoSideEffects(1),
        Idempotent(2);

        construct(Int protoValue) {
            this.protoValue = protoValue;
        }

        @Override
        Int protoValue;
    }

    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 33:
            deprecated = input.readBool();
            return True;

        case 34:
            if (wellknown.MethodOptions.IdempotencyLevel v := protobuf.ProtoEnum.byProtoValue(wellknown.MethodOptions.IdempotencyLevel.values, input.readEnum())) {
                idempotencyLevel = v;
            }
            return True;

        case 35:
            protobuf.wellknown.FeatureSet msg = new protobuf.wellknown.FeatureSet();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            features = msg;
                        return True;

        case 999:
            if (uninterpretedOption.is(immutable)) {
                uninterpretedOption = new ecstasy.collections.Array(Mutable, uninterpretedOption);
            }
            protobuf.wellknown.UninterpretedOption elem = new protobuf.wellknown.UninterpretedOption();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            uninterpretedOption.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        if (presentBits_0 & 0x01 != 0) {
            out.writeBool(33, deprecated);
        }
        wellknown.MethodOptions.IdempotencyLevel? idempotencyLevel = this.idempotencyLevel;
        if (idempotencyLevel != Null) {
            out.writeEnum(34, idempotencyLevel);
        }
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            out.writeMessage(35, features);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            out.writeMessage(999, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(33);
        }
        wellknown.MethodOptions.IdempotencyLevel? idempotencyLevel = this.idempotencyLevel;
        if (idempotencyLevel != Null) {
            size += protobuf.CodedOutput.computeEnumSize(34, idempotencyLevel);
        }
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            size += protobuf.CodedOutput.computeMessageSize(35, features);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            size += protobuf.CodedOutput.computeMessageSize(999, v);
        }
        return size;
    }

    @Override
    MethodOptions! mergeFrom(MethodOptions other) {
        if (this.is(immutable)) {
            return new MethodOptions(this).mergeFrom(other);
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _deprecated = other._deprecated;
            presentBits_0 |= 0x01;
        }
        if (other.idempotencyLevel != Null) {
            idempotencyLevel = other.idempotencyLevel;
        }
        protobuf.wellknown.FeatureSet? _featuresOther = other.features;
        if (_featuresOther != Null) {
            if (other.is(immutable)) {
                features = _featuresOther;
            } else {
                features = _featuresOther.duplicate();
            }
        }
        uninterpretedOption.addAll(other.uninterpretedOption);
        super(other);
        return this;
    }

    @Override
    immutable MethodOptions freeze(Boolean inPlace = False) {
        if (this.is(immutable MethodOptions)) {
            return this;
        }
        if (!inPlace) {
            return new MethodOptions(this).freeze(True);
        }
        unknownFields.freeze(True);
        features?.freeze(True);
        uninterpretedOption.freeze(True);
        return this.makeImmutable();
    }
}
