/**
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * OneofOptions defined in the proto file descriptor.proto
 */
class OneofOptions
        extends protobuf.AbstractMessage {
    construct(
            FeatureSet? features = Null,
            Array<UninterpretedOption> uninterpretedOption = []) {
        construct protobuf.AbstractMessage();
        this.features = features;
        this.uninterpretedOption = uninterpretedOption;
    }

    @Override
    construct(OneofOptions other) {
        construct protobuf.AbstractMessage(other);
        features = other.features;
        uninterpretedOption = other.uninterpretedOption.duplicate();
    }

    FeatureSet? features = Null;
    Array<UninterpretedOption> uninterpretedOption = [];

    conditional FeatureSet hasFeatures() {
        FeatureSet? value = features;
        if (value.is(FeatureSet)) {
            return True, value;
        }
        return False;
    }
    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            FeatureSet msg = new FeatureSet();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            features = msg;
                        return True;

        case 999:
            if (uninterpretedOption.is(immutable)) {
                uninterpretedOption = new Array(uninterpretedOption);
            }
            UninterpretedOption elem = new UninterpretedOption();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            uninterpretedOption.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        FeatureSet? features = this.features;
        if (features != Null) {
            out.writeMessage(1, features);
        }
        for (UninterpretedOption v : uninterpretedOption) {
            out.writeMessage(999, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        FeatureSet? features = this.features;
        if (features != Null) {
            size += protobuf.CodedOutput.computeMessageSize(1, features);
        }
        for (UninterpretedOption v : uninterpretedOption) {
            size += protobuf.CodedOutput.computeMessageSize(999, v);
        }
        return size;
    }

    @Override
    OneofOptions! mergeFrom(OneofOptions other) {
        if (this.is(immutable)) {
            return new OneofOptions(this).mergeFrom(other);
        }
        FeatureSet? _featuresOther = other.features;
        if (_featuresOther != Null) {
            if (other.is(immutable)) {
                features = _featuresOther;
            } else {
                features = _featuresOther.duplicate();
            }
        }
        uninterpretedOption.addAll(other.uninterpretedOption);
        super(other);
        return this;
    }

    @Override
    immutable OneofOptions freeze(Boolean inPlace = False) {
        if (this.is(immutable OneofOptions)) {
            return this;
        }
        if (!inPlace) {
            return new OneofOptions(this).freeze(True);
        }
        unknownFields.freeze(True);
        features?.freeze(True);
        uninterpretedOption.freeze(True);
        return this.makeImmutable();
    }
}
