/**
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * ServiceOptions defined in the proto file descriptor.proto
 */
class ServiceOptions
        extends protobuf.AbstractMessage {
    construct(
            FeatureSet? features = Null,
            Boolean? deprecated = Null,
            Array<UninterpretedOption> uninterpretedOption = []) {
        construct protobuf.AbstractMessage();
        this.features = features;
        this.uninterpretedOption = uninterpretedOption;
    } finally {
        this.deprecated ?= deprecated;
    }

    @Override
    construct(ServiceOptions other) {
        construct protobuf.AbstractMessage(other);
        features = other.features;
        _deprecated = other.deprecated;
        uninterpretedOption = other.uninterpretedOption.duplicate();
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    FeatureSet? features = Null;
    private Boolean _deprecated = False;

    Boolean deprecated {
        @Override
        Boolean get() {
            return _deprecated;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x01;
            _deprecated = value;
        }
    }

    Array<UninterpretedOption> uninterpretedOption = [];

    conditional Boolean hasDeprecated() {
        if (presentBits_0 & 0x01 != 0) {
            return True, deprecated;
        }
        return False;
    }

    conditional FeatureSet hasFeatures() {
        FeatureSet? value = features;
        if (value.is(FeatureSet)) {
            return True, value;
        }
        return False;
    }
    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 34:
            FeatureSet msg = new FeatureSet();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            features = msg;
                        return True;

        case 33:
            deprecated = input.readBool();
            return True;

        case 999:
            if (uninterpretedOption.is(immutable)) {
                uninterpretedOption = new Array(uninterpretedOption);
            }
            UninterpretedOption elem = new UninterpretedOption();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            uninterpretedOption.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        FeatureSet? features = this.features;
        if (features != Null) {
            out.writeMessage(34, features);
        }
        if (presentBits_0 & 0x01 != 0) {
            out.writeBool(33, deprecated);
        }
        for (UninterpretedOption v : uninterpretedOption) {
            out.writeMessage(999, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        FeatureSet? features = this.features;
        if (features != Null) {
            size += protobuf.CodedOutput.computeMessageSize(34, features);
        }
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(33);
        }
        for (UninterpretedOption v : uninterpretedOption) {
            size += protobuf.CodedOutput.computeMessageSize(999, v);
        }
        return size;
    }

    @Override
    ServiceOptions! mergeFrom(ServiceOptions other) {
        if (this.is(immutable)) {
            return new ServiceOptions(this).mergeFrom(other);
        }
        FeatureSet? _featuresOther = other.features;
        if (_featuresOther != Null) {
            if (other.is(immutable)) {
                features = _featuresOther;
            } else {
                features = _featuresOther.duplicate();
            }
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _deprecated = other._deprecated;
            presentBits_0 |= 0x01;
        }
        uninterpretedOption.addAll(other.uninterpretedOption);
        super(other);
        return this;
    }

    @Override
    immutable ServiceOptions freeze(Boolean inPlace = False) {
        if (this.is(immutable ServiceOptions)) {
            return this;
        }
        if (!inPlace) {
            return new ServiceOptions(this).freeze(True);
        }
        unknownFields.freeze(True);
        features?.freeze(True);
        uninterpretedOption.freeze(True);
        return this.makeImmutable();
    }
}
