/**
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * ServiceOptions defined in the proto file google/protobuf/descriptor.proto
 */
class ServiceOptions
        extends protobuf.AbstractMessage {
    construct(
            protobuf.wellknown.FeatureSet? features = Null,
            Boolean? deprecated = Null,
            Array<protobuf.wellknown.UninterpretedOption> uninterpretedOption = []) {
        construct protobuf.AbstractMessage();
        this.features = features;
        this.uninterpretedOption = uninterpretedOption;
    } finally {
        this.deprecated ?= deprecated;
    }

    @Override
    construct(ServiceOptions other) {
        construct protobuf.AbstractMessage(other);
        features = other.features;
        _deprecated = other.deprecated;
        uninterpretedOption = other.uninterpretedOption.duplicate();
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    /**
     * Any features defined in the specific edition.
     * WARNING: This field should only be used by protobuf plugins or special
     * cases like the proto compiler. Other uses are discouraged and
     * developers should rely on the protoreflect APIs for their client language.
     */
    protobuf.wellknown.FeatureSet? features = Null;
    /**
     * Internal storage for the deprecated field.
     */
    private Boolean _deprecated = False;

    /**
     * Is this service deprecated?
     * Depending on the target platform, this can emit Deprecated annotations
     * for the service, or it will be completely ignored; in the very least,
     * this is a formalization for deprecating services.
     */
    Boolean deprecated {
        @Override
        Boolean get() {
            return _deprecated;
        }
        @Override
        void set(Boolean value) {
            presentBits_0 |= 0x01;
            _deprecated = value;
        }
    }

    /**
     * The parser stores options it doesn't recognize here. See above.
     */
    Array<protobuf.wellknown.UninterpretedOption> uninterpretedOption = [];

    conditional Boolean hasDeprecated() {
        if (presentBits_0 & 0x01 != 0) {
            return True, deprecated;
        }
        return False;
    }

    conditional protobuf.wellknown.FeatureSet hasFeatures() {
        protobuf.wellknown.FeatureSet? value = features;
        if (value.is(protobuf.wellknown.FeatureSet)) {
            return True, value;
        }
        return False;
    }
    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 34:
            protobuf.wellknown.FeatureSet msg = new protobuf.wellknown.FeatureSet();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            msg.mergeFrom(input);
            input.popLimit(oldLimit);
            features = msg;
                        return True;

        case 33:
            deprecated = input.readBool();
            return True;

        case 999:
            if (uninterpretedOption.is(immutable)) {
                uninterpretedOption = new Array(Mutable, uninterpretedOption);
            }
            protobuf.wellknown.UninterpretedOption elem = new protobuf.wellknown.UninterpretedOption();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            uninterpretedOption.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            out.writeMessage(34, features);
        }
        if (presentBits_0 & 0x01 != 0) {
            out.writeBool(33, deprecated);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            out.writeMessage(999, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        protobuf.wellknown.FeatureSet? features = this.features;
        if (features != Null) {
            size += protobuf.CodedOutput.computeMessageSize(34, features);
        }
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeBoolSize(33);
        }
        for (protobuf.wellknown.UninterpretedOption v : uninterpretedOption) {
            size += protobuf.CodedOutput.computeMessageSize(999, v);
        }
        return size;
    }

    @Override
    ServiceOptions! mergeFrom(ServiceOptions other) {
        if (this.is(immutable)) {
            return new ServiceOptions(this).mergeFrom(other);
        }
        protobuf.wellknown.FeatureSet? _featuresOther = other.features;
        if (_featuresOther != Null) {
            if (other.is(immutable)) {
                features = _featuresOther;
            } else {
                features = _featuresOther.duplicate();
            }
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _deprecated = other._deprecated;
            presentBits_0 |= 0x01;
        }
        uninterpretedOption.addAll(other.uninterpretedOption);
        super(other);
        return this;
    }

    @Override
    immutable ServiceOptions freeze(Boolean inPlace = False) {
        if (this.is(immutable ServiceOptions)) {
            return this;
        }
        if (!inPlace) {
            return new ServiceOptions(this).freeze(True);
        }
        unknownFields.freeze(True);
        features?.freeze(True);
        uninterpretedOption.freeze(True);
        return this.makeImmutable();
    }
}
