/**
 * Encapsulates information about the original source file from which a
 * FileDescriptorProto was generated.
 *
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * SourceCodeInfo defined in the proto file google/protobuf/descriptor.proto
 */
@protobuf.WellKnownLocation("google.protobuf.SourceCodeInfo")
class SourceCodeInfo
        extends protobuf.AbstractMessage {
    construct(
            wellknown.SourceCodeInfo.Location[] location = []) {
        construct protobuf.AbstractMessage();
        this.location = location;
    }

    @Override
    construct(SourceCodeInfo other) {
        construct protobuf.AbstractMessage(other);
        location = other.location.duplicate();
    }

    /**
     * A Location identifies a piece of source code in a .proto file which
     * corresponds to a particular definition.  This information is intended
     * to be useful to IDEs, code indexers, documentation generators, and similar
     * tools.
     *
     * For example, say we have a file like:
     * message Foo {
     * optional string foo = 1;
     * }
     * Let's look at just the field definition:
     * optional string foo = 1;
     * ^       ^^     ^^  ^  ^^^
     * a       bc     de  f  ghi
     * We have the following locations:
     * span   path               represents
     * [a,i)  [ 4, 0, 2, 0 ]     The whole field definition.
     * [a,b)  [ 4, 0, 2, 0, 4 ]  The label (optional).
     * [c,d)  [ 4, 0, 2, 0, 5 ]  The type (string).
     * [e,f)  [ 4, 0, 2, 0, 1 ]  The name (foo).
     * [g,h)  [ 4, 0, 2, 0, 3 ]  The number (1).
     *
     * Notes:
     * - A location may refer to a repeated field itself (i.e. not to any
     * particular index within it).  This is used whenever a set of elements are
     * logically enclosed in a single code segment.  For example, an entire
     * extend block (possibly containing multiple extension definitions) will
     * have an outer location whose path refers to the "extensions" repeated
     * field without an index.
     * - Multiple locations may have the same path.  This happens when a single
     * logical declaration is spread out across multiple places.  The most
     * obvious example is the "extend" block again -- there may be multiple
     * extend blocks in the same scope, each of which will have the same path.
     * - A location's span is not always a subset of its parent's span.  For
     * example, the "extendee" of an extension declaration appears at the
     * beginning of the "extend" block and is shared by all extensions within
     * the block.
     * - Just because a location's span is a subset of some other location's span
     * does not mean that it is a descendant.  For example, a "group" defines
     * both a type and a field in a single declaration.  Thus, the locations
     * corresponding to the type and field and their components will overlap.
     * - Code which tries to interpret locations should probably be designed to
     * ignore those that it doesn't understand, as more types of locations could
     * be recorded in the future.
     */
    wellknown.SourceCodeInfo.Location[] location = [];

    // ----- message Location ----------------------------------------------------------------------

    /**
     * This class has been generated by the Ecstasy protoc plugin from the message type
     * Location defined in the proto file google/protobuf/descriptor.proto
     */
    static class Location
            extends protobuf.AbstractMessage {
        construct(
                    Int32[] path = [],
                    Int32[] span = [],
                    String? leadingComments = Null,
                    String? trailingComments = Null,
                    String[] leadingDetachedComments = []) {
            construct protobuf.AbstractMessage();
            this.path = path;
            this.span = span;
            this.leadingDetachedComments = leadingDetachedComments;
        } finally {
            this.leadingComments ?= leadingComments;
            this.trailingComments ?= trailingComments;
        }

        @Override
        construct(Location other) {
            construct protobuf.AbstractMessage(other);
            path = other.path.duplicate();
            span = other.span.duplicate();
            _leadingComments = other.leadingComments;
            _trailingComments = other.trailingComments;
            leadingDetachedComments = other.leadingDetachedComments.duplicate();
            presentBits_0 = other.presentBits_0;
        }

        private Int presentBits_0 = 0;

        /**
         * Identifies which part of the FileDescriptorProto was defined at this
         * location.
         *
         * Each element is a field number or an index.  They form a path from
         * the root FileDescriptorProto to the place where the definition appears.
         * For example, this path:
         * [ 4, 3, 2, 7, 1 ]
         * refers to:
         * file.message_type(3)  // 4, 3
         * .field(7)         // 2, 7
         * .name()           // 1
         * This is because FileDescriptorProto.message_type has field number 4:
         * repeated DescriptorProto message_type = 4;
         * and DescriptorProto.field has field number 2:
         * repeated FieldDescriptorProto field = 2;
         * and FieldDescriptorProto.name has field number 1:
         * optional string name = 1;
         *
         * Thus, the above path gives the location of a field name.  If we removed
         * the last element:
         * [ 4, 3, 2, 7 ]
         * this path refers to the whole field declaration (from the beginning
         * of the label to the terminating semicolon).
         */
        Int32[] path = [];

        /**
         * Always has exactly three or four elements: start line, start column,
         * end line (optional, otherwise assumed same as start line), end column.
         * These are packed into a single field for efficiency.  Note that line
         * and column numbers are zero-based -- typically you will want to add
         * 1 to each before displaying to a user.
         */
        Int32[] span = [];

        /**
         * Internal storage for the leading_comments field.
         */
        private String _leadingComments = "";

        /**
         * If this SourceCodeInfo represents a complete declaration, these are any
         * comments appearing before and after the declaration which appear to be
         * attached to the declaration.
         *
         * A series of line comments appearing on consecutive lines, with no other
         * tokens appearing on those lines, will be treated as a single comment.
         *
         * leading_detached_comments will keep paragraphs of comments that appear
         * before (but not connected to) the current element. Each paragraph,
         * separated by empty lines, will be one comment element in the repeated
         * field.
         *
         * Only the comment content is provided; comment markers (e.g. //) are
         * stripped out.  For block comments, leading whitespace and an asterisk
         * will be stripped from the beginning of each line other than the first.
         * Newlines are included in the output.
         */
        String leadingComments {
            @Override
            String get() {
                return _leadingComments;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x01;
                _leadingComments = value;
            }
        }

        /**
         * Internal storage for the trailing_comments field.
         */
        private String _trailingComments = "";

        String trailingComments {
            @Override
            String get() {
                return _trailingComments;
            }
            @Override
            void set(String value) {
                presentBits_0 |= 0x02;
                _trailingComments = value;
            }
        }

        String[] leadingDetachedComments = [];


        conditional String hasLeadingComments() {
            if (presentBits_0 & 0x01 != 0) {
                return True, leadingComments;
            }
            return False;
        }

        conditional String hasTrailingComments() {
            if (presentBits_0 & 0x02 != 0) {
                return True, trailingComments;
            }
            return False;
        }


        // ----- serialization ---------------------------------------------------------------------

        @Override
        Boolean parseField(protobuf.CodedInput input, Int tag) {
            switch (protobuf.WireType.getFieldNumber(tag)) {
            case 1:
                if (path.is(immutable)) {
                    path = new ecstasy.collections.Array(Mutable, path);
                }
                if (protobuf.WireType.getWireType(tag) == protobuf.WireType.LEN) {
                    path.addAll(input.readPackedInt32s());
                } else {
                    path.add(input.readInt32());
                }                return True;

            case 2:
                if (span.is(immutable)) {
                    span = new ecstasy.collections.Array(Mutable, span);
                }
                if (protobuf.WireType.getWireType(tag) == protobuf.WireType.LEN) {
                    span.addAll(input.readPackedInt32s());
                } else {
                    span.add(input.readInt32());
                }                return True;

            case 3:
                leadingComments = input.readString();
                return True;

            case 4:
                trailingComments = input.readString();
                return True;

            case 6:
                if (leadingDetachedComments.is(immutable)) {
                    leadingDetachedComments = new ecstasy.collections.Array(Mutable, leadingDetachedComments);
                }
                leadingDetachedComments.add(input.readString());
                return True;
            }
            return False;
        }

        @Override
        void writeKnownFields(protobuf.CodedOutput out) {
            if (!path.empty) {
                out.writePackedVarints(1, path);
            }
            if (!span.empty) {
                out.writePackedVarints(2, span);
            }
            if (presentBits_0 & 0x01 != 0) {
                out.writeString(3, leadingComments);
            }
            if (presentBits_0 & 0x02 != 0) {
                out.writeString(4, trailingComments);
            }
            for (String v : leadingDetachedComments) {
                out.writeString(6, v);
            }
        }

        @Override
        Int knownFieldsSize() {
            Int size = 0;
            if (!path.empty) {
                size += protobuf.CodedOutput.computePackedVarintsSize(1, path);
            }
            if (!span.empty) {
                size += protobuf.CodedOutput.computePackedVarintsSize(2, span);
            }
            if (presentBits_0 & 0x01 != 0) {
                size += protobuf.CodedOutput.computeStringSize(3, leadingComments);
            }
            if (presentBits_0 & 0x02 != 0) {
                size += protobuf.CodedOutput.computeStringSize(4, trailingComments);
            }
            for (String v : leadingDetachedComments) {
                size += protobuf.CodedOutput.computeStringSize(6, v);
            }
            return size;
        }

        @Override
        Location! mergeFrom(Location other) {
            if (this.is(immutable)) {
                return new Location(this).mergeFrom(other);
            }
            path.addAll(other.path);
            span.addAll(other.span);
            if (other.presentBits_0 & 0x01 != 0) {
                _leadingComments = other._leadingComments;
                presentBits_0 |= 0x01;
            }
            if (other.presentBits_0 & 0x02 != 0) {
                _trailingComments = other._trailingComments;
                presentBits_0 |= 0x02;
            }
            leadingDetachedComments.addAll(other.leadingDetachedComments);
            super(other);
            return this;
        }

        @Override
        immutable Location freeze(Boolean inPlace = False) {
            if (this.is(immutable Location)) {
                return this;
            }
            if (!inPlace) {
                return new Location(this).freeze(True);
            }
            unknownFields.freeze(True);
            path.freeze(True);
            span.freeze(True);
            leadingDetachedComments.freeze(True);
            return this.makeImmutable();
        }
    }


    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            if (location.is(immutable)) {
                location = new ecstasy.collections.Array(Mutable, location);
            }
            wellknown.SourceCodeInfo.Location elem = new wellknown.SourceCodeInfo.Location();
            Int len = input.readVarint().toInt();
            Int oldLimit = input.pushLimit(len);
            elem.mergeFrom(input);
            input.popLimit(oldLimit);
            location.add(elem);
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        for (wellknown.SourceCodeInfo.Location v : location) {
            out.writeMessage(1, v);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        for (wellknown.SourceCodeInfo.Location v : location) {
            size += protobuf.CodedOutput.computeMessageSize(1, v);
        }
        return size;
    }

    @Override
    SourceCodeInfo! mergeFrom(SourceCodeInfo other) {
        if (this.is(immutable)) {
            return new SourceCodeInfo(this).mergeFrom(other);
        }
        location.addAll(other.location);
        super(other);
        return this;
    }

    @Override
    immutable SourceCodeInfo freeze(Boolean inPlace = False) {
        if (this.is(immutable SourceCodeInfo)) {
            return this;
        }
        if (!inPlace) {
            return new SourceCodeInfo(this).freeze(True);
        }
        unknownFields.freeze(True);
        location.freeze(True);
        return this.makeImmutable();
    }
}
