name: 'Setup XVM Build Environment'
description: 'Sets up Java, Gradle, and XVM-specific environment for building XVM projects'
inputs:
  java-version:
    description: 'Java version to set up'
    required: false
    default: '21'
  java-distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  gradle-version:
    description: 'Gradle version to use'
    required: false
    default: '9.0.0'
  cache-read-only:
    description: 'Set Gradle cache to read-only mode'
    required: false
    default: 'false'
  enable-debug:
    description: 'Enable Gradle build action debug logging'
    required: false
    default: 'true'

outputs:
  java-version:
    description: 'The Java version that was set up'
    value: ${{ steps.setup-java.outputs.version }}
  gradle-version:
    description: 'The Gradle version that was set up'
    value: ${{ inputs.gradle-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      id: setup-java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-disabled: false
        cache-read-only: ${{ inputs.cache-read-only }}
        gradle-version: ${{ inputs.gradle-version }}
      env:
        GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: ${{ inputs.enable-debug }}
        ACTIONS_STEP_DEBUG: ${{ inputs.enable-debug }}

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

branding:
  icon: 'settings'
  color: 'blue'