name: 'Create Snapshot Release'
description: 'Creates or updates the xdk-latest-snapshot GitHub release with XDK zip file'
inputs:
  xdk-version:
    description: 'XDK version (e.g., 0.4.4-SNAPSHOT)'
    required: true
  commit-sha:
    description: 'Full commit SHA for release tagging'
    required: true
  xdk-zip-name:
    description: 'Name of the XDK zip file to upload'
    required: true
  github-token:
    description: 'GitHub token with release permissions'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create or update snapshot release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        RELEASE_TAG="xdk-latest-snapshot"
        RELEASE_NAME="XDK Latest Snapshot"
        ZIP_FILE="${{ inputs.xdk-zip-name }}"
        
        echo "Creating/updating snapshot release with:"
        echo "  Tag: $RELEASE_TAG"
        echo "  Version: ${{ inputs.xdk-version }}"
        echo "  Commit: ${{ inputs.commit-sha }}"
        echo "  Zip file: $ZIP_FILE"
        
        # Delete existing release if it exists (to overwrite)
        if gh release view $RELEASE_TAG >/dev/null 2>&1; then
          echo "Deleting existing snapshot release..."
          gh release delete $RELEASE_TAG --yes
        fi
        
        # Create new snapshot release
        echo "Creating new snapshot release..."
        gh release create $RELEASE_TAG \
          --title "$RELEASE_NAME" \
          --notes "**Automated snapshot release**

Built from commit: \`${{ inputs.commit-sha }}\`  
Version: \`${{ inputs.xdk-version }}\`  
Build date: \`$(date -u '+%Y-%m-%d %H:%M:%S UTC')\`

This is a snapshot release that gets automatically updated on every push to master. Use this for development and testing - stable releases will be tagged separately.

**Installation via Homebrew:**
\`\`\`bash
brew tap xtclang/xvm && brew install xdk-latest
\`\`\`

**Direct download:**
Download the zip file below and extract to your preferred location." \
          --prerelease \
          "$ZIP_FILE"
          
        echo "✅ Snapshot release created successfully"

branding:
  icon: 'upload'
  color: 'blue'