#
# Downloads commit-specific XDK snapshot from the xdk-snapshots release
#
# This action downloads the exact snapshot built for a specific commit,
# ensuring workflows use artifacts from the correct commit. The download
# fails automatically if the commit-specific snapshot doesn't exist.
#
name: 'Download Snapshot Release'
description: 'Downloads commit-specific XDK snapshot and validates it exists'

inputs:
    commit:
        description: 'The commit SHA to download snapshot for'
        required: true
    xdk-version:
        description: 'XDK version (e.g., 0.4.4-SNAPSHOT)'
        required: true
    repo:
        description: 'Repository in format owner/repo'
        required: true
    github-token:
        description: 'GitHub token for download access'
        required: true

outputs:
    snapshot-file:
        description: 'Path to downloaded snapshot file'
        value: ${{ steps.download.outputs.snapshot-file }}
    snapshot-name:
        description: 'Name of downloaded snapshot file'
        value: ${{ steps.download.outputs.snapshot-name }}

runs:
    using: 'composite'
    steps:
        - name: Download commit-specific snapshot
          id: download
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.github-token }}
          run: |
              COMMIT="${{ inputs.commit }}"
              VERSION="${{ inputs.xdk-version }}"
              REPO="${{ inputs.repo }}"
              SNAPSHOT_NAME="xdk-${VERSION}-${COMMIT}.zip"

              echo "📥 Downloading commit-specific XDK snapshot"
              echo "  Commit:  $COMMIT"
              echo "  Version: $VERSION"
              echo "  File:    $SNAPSHOT_NAME"
              echo ""

              if ! gh release download xdk-snapshots \
                  --pattern "$SNAPSHOT_NAME" \
                  --repo "$REPO"; then
                  echo ""
                  echo "❌ Failed to download $SNAPSHOT_NAME"
                  echo ""
                  echo "This snapshot may not exist yet. Possible reasons:"
                  echo "  - CI build for commit $COMMIT hasn't completed"
                  echo "  - CI build failed"
                  echo "  - Wrong commit reference"
                  echo ""
                  echo "Available snapshots (last 10):"
                  gh release view xdk-snapshots --repo "$REPO" --json assets \
                      --jq '.assets[].name' | grep "^xdk-" | tail -10 || echo "  None found"
                  exit 1
              fi

              echo ""
              echo "✅ Downloaded: $SNAPSHOT_NAME"
              ls -lh "$SNAPSHOT_NAME"

              echo "snapshot-file=$SNAPSHOT_NAME" >> $GITHUB_OUTPUT
              echo "snapshot-name=$SNAPSHOT_NAME" >> $GITHUB_OUTPUT

branding:
    icon: 'download'
    color: 'blue'
