package org.xtclang.ecstasy;

import org.xtclang.ecstasy.reflect.Enumeration;

import org.xtclang.ecstasy.text.String;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Native representation for "ecstasy.Boolean".
 *
 * TODO how to ensure that if `static foo$p()` exists but `foo()` doesn't, that we gen the foo() wrapper?
 * TODO which wrappers can we delete now?
 * TODO alternatively just spell it all out since this is such a core class?
 */
public abstract class Boolean
        extends nEnum {
    public static final Boolean False = new False();
    public static final Boolean True  = new True();

    public static class False extends Boolean {
        public False() {
            super($xvm().ecstasyPool.typeFalse(), false, 0, String.of(null, "False"));
        }
    }

    public static class True extends Boolean {
        public True() {
            super($xvm().ecstasyPool.typeTrue(), true, 1, String.of(null, "True"));
        }
    }

    private Boolean(TypeConstant type, boolean value, long ordinal, String name) {
        super(null);
        $type    = type;
        $value   = value;
        $ordinal = ordinal;
        $name    = name;
    }

    public final TypeConstant $type;
    public final boolean      $value;
    public final long         $ordinal;
    public final String       $name;

    @Override public TypeConstant $xvmType(Ctx ctx) {
        return $type;
    }

    public static Boolean $box(boolean value) {
        return value ? True : False;
    }

    // TODO this method should be generated by the augmenting builder
    @Override public Enumeration enumeration$get(Ctx ctx) {
        return eBoolean.$INSTANCE;
    }

    public static Enumeration enumeration$get$p(boolean thi$, Ctx ctx) {
        return eBoolean.$INSTANCE;
    }

    // TODO this method should be generated by the augmenting builder
    @Override public String name$get(Ctx ctx) {
        return $name;
    }

    public static String name$get$p(boolean thi$, Ctx ctx) {
        return (thi$ ? True : False).$name;
    }

    @Override public long ordinal$get$p(Ctx ctx) {
        return $ordinal;
    }

    public static long ordinal$get$p(boolean thi$, Ctx ctx) {
        return thi$ ? 1 : 0;
    }

    public static boolean and$p(boolean thi$, Ctx ctx, boolean that) {
        return thi$  & that;
    }

    public static boolean or$p(boolean thi$, Ctx ctx, boolean that) {
        return thi$;
    }

    public static boolean xor$p(boolean thi$, Ctx ctx, boolean that) {
        return thi$ ^ that;
    }

    public static boolean not$p(boolean thi$, Ctx ctx) {
        return !thi$;
    }

    public static int toBit$p(boolean thi$, Ctx ctx) {
        return thi$ ? 1 : 0;
    }

    public static int toByte$p(boolean thi$, Ctx ctx) {
        return thi$ ? (byte) 1 : (byte) 0;
    }

    // TODO this method should be generated by the augmenting builder
    @Override public String toString(Ctx ctx) {
        return $name;
    }

    public static String toString$p(boolean thi$, Ctx ctx) {
        return name$get$p(thi$, ctx);
    }

    public static long estimateStringLength$p(boolean thi$, Ctx ctx) {
        return name$get$p(thi$, ctx).size$get$p(ctx);
    }

    public static AppenderᐸCharᐳ appendTo$p(boolean thi$, Ctx ctx, AppenderᐸCharᐳ appender) {
        return name$get$p(thi$, ctx).appendTo(ctx, appender);
    }

    // ----- debugging support ---------------------------------------------------------------------

    @Override public java.lang.String toString() {
        return $name.toString();
    }
}
