/**
 * The version number of protocol compiler.
 *
 * This class has been generated by the Ecstasy protoc plugin from the message type
 * Version defined in the proto file google/protobuf/compiler/plugin.proto
 */
@protobuf.WellKnownLocation("google.protobuf.compiler.Version")
class Version
        extends protobuf.AbstractMessage {
    construct(
            Int32? major = Null,
            Int32? minor = Null,
            Int32? patch = Null,
            String? suffix = Null) {
        construct protobuf.AbstractMessage();
    } finally {
        this.major ?= major;
        this.minor ?= minor;
        this.patch ?= patch;
        this.suffix ?= suffix;
    }

    @Override
    construct(Version other) {
        construct protobuf.AbstractMessage(other);
        _major = other.major;
        _minor = other.minor;
        _patch = other.patch;
        _suffix = other.suffix;
        presentBits_0 = other.presentBits_0;
    }

    private Int presentBits_0 = 0;

    /**
     * Internal storage for the major field.
     */
    private Int32 _major = 0;

    Int32 major {
        @Override
        Int32 get() {
            return _major;
        }
        @Override
        void set(Int32 value) {
            presentBits_0 |= 0x01;
            _major = value;
        }
    }

    /**
     * Internal storage for the minor field.
     */
    private Int32 _minor = 0;

    Int32 minor {
        @Override
        Int32 get() {
            return _minor;
        }
        @Override
        void set(Int32 value) {
            presentBits_0 |= 0x02;
            _minor = value;
        }
    }

    /**
     * Internal storage for the patch field.
     */
    private Int32 _patch = 0;

    Int32 patch {
        @Override
        Int32 get() {
            return _patch;
        }
        @Override
        void set(Int32 value) {
            presentBits_0 |= 0x04;
            _patch = value;
        }
    }

    /**
     * Internal storage for the suffix field.
     */
    private String _suffix = "";

    /**
     * A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
     * be empty for mainline stable releases.
     */
    String suffix {
        @Override
        String get() {
            return _suffix;
        }
        @Override
        void set(String value) {
            presentBits_0 |= 0x08;
            _suffix = value;
        }
    }


    conditional Int32 hasMajor() {
        if (presentBits_0 & 0x01 != 0) {
            return True, major;
        }
        return False;
    }

    conditional Int32 hasMinor() {
        if (presentBits_0 & 0x02 != 0) {
            return True, minor;
        }
        return False;
    }

    conditional Int32 hasPatch() {
        if (presentBits_0 & 0x04 != 0) {
            return True, patch;
        }
        return False;
    }

    conditional String hasSuffix() {
        if (presentBits_0 & 0x08 != 0) {
            return True, suffix;
        }
        return False;
    }


    // ----- serialization -------------------------------------------------------------------------

    @Override
    Boolean parseField(protobuf.CodedInput input, Int tag) {
        switch (protobuf.WireType.getFieldNumber(tag)) {
        case 1:
            major = input.readInt32();
            return True;

        case 2:
            minor = input.readInt32();
            return True;

        case 3:
            patch = input.readInt32();
            return True;

        case 4:
            suffix = input.readString();
            return True;
        }
        return False;
    }

    @Override
    void writeKnownFields(protobuf.CodedOutput out) {
        if (presentBits_0 & 0x01 != 0) {
            out.writeInt32(1, major);
        }
        if (presentBits_0 & 0x02 != 0) {
            out.writeInt32(2, minor);
        }
        if (presentBits_0 & 0x04 != 0) {
            out.writeInt32(3, patch);
        }
        if (presentBits_0 & 0x08 != 0) {
            out.writeString(4, suffix);
        }
    }

    @Override
    Int knownFieldsSize() {
        Int size = 0;
        if (presentBits_0 & 0x01 != 0) {
            size += protobuf.CodedOutput.computeInt32Size(1, major);
        }
        if (presentBits_0 & 0x02 != 0) {
            size += protobuf.CodedOutput.computeInt32Size(2, minor);
        }
        if (presentBits_0 & 0x04 != 0) {
            size += protobuf.CodedOutput.computeInt32Size(3, patch);
        }
        if (presentBits_0 & 0x08 != 0) {
            size += protobuf.CodedOutput.computeStringSize(4, suffix);
        }
        return size;
    }

    @Override
    Version! mergeFrom(Version other) {
        if (this.is(immutable)) {
            return new Version(this).mergeFrom(other);
        }
        if (other.presentBits_0 & 0x01 != 0) {
            _major = other._major;
            presentBits_0 |= 0x01;
        }
        if (other.presentBits_0 & 0x02 != 0) {
            _minor = other._minor;
            presentBits_0 |= 0x02;
        }
        if (other.presentBits_0 & 0x04 != 0) {
            _patch = other._patch;
            presentBits_0 |= 0x04;
        }
        if (other.presentBits_0 & 0x08 != 0) {
            _suffix = other._suffix;
            presentBits_0 |= 0x08;
        }
        super(other);
        return this;
    }

    @Override
    immutable Version freeze(Boolean inPlace = False) {
        if (this.is(immutable Version)) {
            return this;
        }
        if (!inPlace) {
            return new Version(this).freeze(True);
        }
        unknownFields.freeze(True);
        return this.makeImmutable();
    }
}
