import org.gradle.jvm.toolchain.JavaLanguageVersion

plugins {
    alias(libs.plugins.xdk.build.properties)
    alias(libs.plugins.kotlin.jvm)
    id("org.jetbrains.intellij.platform") version "2.10.5"
}

// Access version from xdkProperties (set by xdk.build.properties plugin)
val xdkVersion: String = project.version.toString()
val releaseChannel: String = xdkProperties.stringValue("xdk.intellij.release.channel", "alpha")

// Publishing is disabled by default. Enable with: ./gradlew publishPlugin -PenablePublish=true
val enablePublish = project.findProperty("enablePublish")?.toString()?.toBoolean() ?: false

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation(kotlin("stdlib"))

    intellijPlatform {
        intellijIdeaCommunity("2025.1")
        bundledPlugin("com.intellij.gradle")
        // LSP4IJ provides LSP support for Community Edition
        plugin("com.redhat.devtools.lsp4ij:0.11.0")
        pluginVerifier()
    }
}

// Use Kotlin JDK version from xdkProperties
val kotlinJdkVersion = xdkProperties.int("org.xtclang.kotlin.jdk")

java {
    toolchain {
        languageVersion.set(kotlinJdkVersion.map { JavaLanguageVersion.of(it) })
    }
}

kotlin {
    jvmToolchain {
        languageVersion.set(kotlinJdkVersion.map { JavaLanguageVersion.of(it) })
    }
}

intellijPlatform {
    pluginConfiguration {
        id = "org.xtclang.idea"
        name = "XTC Language Support"
        version = project.version.toString()

        ideaVersion {
            sinceBuild = "251" // IntelliJ 2025.1+
            untilBuild = provider { null } // No upper bound - compatible with future versions
        }

        changeNotes = """
            <h2>$xdkVersion</h2>
            <ul>
                <li>Initial alpha release</li>
                <li>New Project wizard for XTC projects</li>
                <li>Run configurations for XTC applications</li>
                <li>File type support for .x files</li>
            </ul>
        """.trimIndent()
    }

    signing {
        // Plugin signing is optional but recommended for production releases
        // Set these environment variables to enable signing:
        //   JETBRAINS_CERTIFICATE_CHAIN - Base64-encoded certificate chain
        //   JETBRAINS_PRIVATE_KEY - Base64-encoded private key
        //   JETBRAINS_PRIVATE_KEY_PASSWORD - Private key password
        certificateChain = providers.environmentVariable("JETBRAINS_CERTIFICATE_CHAIN")
        privateKey = providers.environmentVariable("JETBRAINS_PRIVATE_KEY")
        password = providers.environmentVariable("JETBRAINS_PRIVATE_KEY_PASSWORD")
    }

    publishing {
        // Token from https://plugins.jetbrains.com/author/me/tokens
        token = providers.environmentVariable("JETBRAINS_TOKEN")

        // Release channel from version.properties: alpha, beta, or default (stable)
        channels = listOf(releaseChannel)
    }
}

val publishCheck by tasks.registering {
    doFirst {
        if (!enablePublish) {
            throw GradleException(
                """
                |Publishing is disabled by default.
                |To publish the plugin, run:
                |  ./gradlew publishPlugin -PenablePublish=true
                |
                |Current version: $xdkVersion
                |Release channel: $releaseChannel
                |
                |Required environment variables:
                |  JETBRAINS_TOKEN - Your JetBrains Marketplace token
                |
                |Optional (for signed releases):
                |  JETBRAINS_CERTIFICATE_CHAIN - Base64-encoded certificate chain
                |  JETBRAINS_PRIVATE_KEY - Base64-encoded private key
                |  JETBRAINS_PRIVATE_KEY_PASSWORD - Private key password
                """.trimMargin()
            )
        }
    }
}

val publishPlugin by tasks.existing {
    enabled = enablePublish
    dependsOn(publishCheck)
}

val buildSearchableOptions by tasks.existing {
    enabled = false // Speeds up build; enable for production
}

// =============================================================================
// TextMate Grammar Integration
// =============================================================================
// Copy TextMate grammar from parent lang project's build output into plugin resources.
// The grammar is generated by lang's generateTextMate task from dsl/XtcLanguage.kt.
//
// IMPORTANT: When building via lang:build, the grammar is generated first.
// When building standalone, run `../gradlew generateEditorSupport` first.

val parentTextMateDir: Directory = layout.projectDirectory.dir("../build/generated/textmate")
val pluginTextMateDir: Directory = layout.projectDirectory.dir("src/main/resources/textmate")

val copyTextMateGrammar by tasks.registering(Sync::class) {
    group = "build"
    description = "Sync generated TextMate grammar into plugin resources"

    from(parentTextMateDir)
    into(pluginTextMateDir)

    // Declare explicit file inputs for proper up-to-date checking
    inputs.dir(parentTextMateDir).optional()
}

// Ensure grammar is synced before processing resources
val processResources by tasks.existing {
    dependsOn(copyTextMateGrammar)
}
