package org.xtclang.ecstasy.text;

import org.xtclang.ecstasy.AppenderᐸCharᐳ;
import org.xtclang.ecstasy.OutOfBounds;
import org.xtclang.ecstasy.nConst;
import org.xtclang.ecstasy.numbers.IntLiteral;
import org.xtclang.ecstasy.numbers.IntN;
import org.xtclang.ecstasy.numbers.UInt32;
import org.xtclang.ecstasy.numbers.UIntN;

import org.xvm.javajit.Ctx;

/**
 * Native shell for "ecstasy.text.Char".
 */
public class Char extends nConst {
    private Char(int codepoint) {
        super(null);
        $value = codepoint;
    }

    public static Char $new$0$p(Ctx ctx, int codepoint) {
        return $box(codepoint);
    }

    /**
     * Lazily populated cache.
     */
    private static final Char[][] $cache = new Char[1088][];

    public static final int $MaxValue = 0x10FFFF;

    public final int $value;

    public static Char $box(int codepoint) {
        Char ch = null;

        assert codepoint >= 0 && codepoint <= $MaxValue;

        // the cache is divided in 0x440 (1088) pages of 0x400 (1024) characters;
        // the pages are lazily created
        Char[] page = $cache[codepoint >>> 10];
        if (page == null) {
            $cache[codepoint >>> 10] = page = new Char[1024];
        } else {
            ch = page[codepoint & 0x3FF];
        }

        // the Char objects in the pages are lazily created
        if (ch == null) {
            page[codepoint & 0x3FF] = ch = new Char(codepoint);
        }

        return ch;
    }

    public static int codepoint$get$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public UInt32 codepoint$get(Ctx ctx) {
        return UInt32.$box($value);
    }

    /**
     * Native implementation of optimized "Char add(Int n)".
     *
     * Calls to this method are generated by the JIT's
     * {@link org.xvm.javajit.TextSupport#buildAddIntToChar} method.
     *
     * @throws OutOfBounds if the result is not a valid Unicode codepoint
     */
    public static int add$p(int this$, Ctx ctx, long n) {
        long cp = this$ + n;
        if (cp < 0 || cp > 0x10FFFF) {
            OutOfBounds oob = new OutOfBounds(ctx);
            throw oob.$init(ctx, "Adding " + n + " to character code-point "
                    + this$ + " would exceed the Unicode range");
        }
        return (int) cp;
    }

    /**
     * Native implementation of optimized "Char sub(Int n)"
     *
     * Calls to this method are generated by the JIT's
     * {@link org.xvm.javajit.TextSupport#buildSubIntFromChar} method.
     *
     * @throws OutOfBounds if the result is not a valid Unicode codepoint
     */
    public static int sub$p(int this$, Ctx ctx, long n) {
        long cp = (long) this$ - n;
        if (cp < 0 || cp > 0x10FFFF) {
            OutOfBounds oob = new OutOfBounds(ctx);
            throw oob.$init(ctx, "Subtracting " + n + " from character code-point "
                    + this$ + " would be below the Unicode range");
        }
        return (int) cp;
    }

    @Override
    public String toString(Ctx ctx) {
        return String.of(null, toString());
    }

    public static String toString$p(int thi$, Ctx ctx) {
        return String.of(ctx, java.lang.Character.toString(thi$));
    }

    public static long estimateStringLength$p(int thi$, Ctx ctx) {
        return 1;
    }

    public AppenderᐸCharᐳ appendTo(Ctx ctx, AppenderᐸCharᐳ appender) {
        return appender.add$p(ctx, $value);
    }

    public static AppenderᐸCharᐳ appendTo$p(int thi$, Ctx ctx, AppenderᐸCharᐳ appender) {
        return appender.add$p(ctx, thi$);
    }

    /**
     * Native implementation of optimized "UInt64 toUnit64()"
     */
    public static long toInt64$p(int thi$, Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        return thi$;
    }

    @Override
    public java.lang.String toString() {
        return java.lang.Character.toString($value);
    }

    // ----- delegated IntConvertible methods -----------------------------------------------------

    public static long toInt$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static int toInt8$d$p(int thi$, Ctx ctx) {
        return (byte) thi$;
    }

    public static int toInt16$d$p(int thi$, Ctx ctx) {
        return (short) thi$;
    }

    public static int toInt32$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static long toInt64$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static long toInt128$d$p(int thi$, Ctx ctx) {
        ctx.i0 = 0;
        return thi$;
    }

    public static IntN toIntN$d$p(int thi$, Ctx ctx) {
        return IntN.$box(thi$);
    }

    public static long toUInt$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static int toUInt8$d$p(int thi$, Ctx ctx) {
        return thi$ & 0xFF;
    }

    public static int toUInt16$d$p(int thi$, Ctx ctx) {
        return thi$ & 0xFFFF;
    }

    public static int toUInt32$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static long toUInt64$d$p(int thi$, Ctx ctx) {
        return thi$;
    }

    public static long toUInt128$d$p(int thi$, Ctx ctx) {
        ctx.i0 = 0;
        return thi$;
    }

    public static UIntN toUIntN$d$p(int thi$, Ctx ctx) {
        return UIntN.$box(thi$);
    }

    public static IntLiteral toIntLiteral$d$p(int thi$, Ctx ctx) {
        return null;
    }

    public static int toNibble$d$p(int thi$, Ctx ctx) {
        return thi$ & 0xF;
    }
}
