import com.diffplug.gradle.spotless.SpotlessCheck
import com.diffplug.gradle.spotless.SpotlessExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/**
 * Root project for XTC language tooling.
 *
 * Subprojects:
 * - dsl: Language model DSL and editor support generators
 * - lsp-server: Language Server Protocol implementation
 * - intellij-plugin: IntelliJ IDEA plugin
 * - vscode-extension: VS Code extension
 */

plugins {
    base
    alias(libs.plugins.lang.kotlin.jvm) apply false
    alias(libs.plugins.lang.kotlin.serialization) apply false
    alias(libs.plugins.spotless)
}

// =============================================================================
// Kotlin formatting
// =============================================================================
// Spotless runs ktlint with its default rules, as the ktlint Gradle plugin did. Each Kotlin
// subproject checks its own sources, tests and build script; generated and synced build outputs
// stay excluded. The lang root, tree-sitter and vscode-extension scripts were never under ktlint
// and would need a one-off reformat to join.
val ktlintVersion = libs.versions.lang.ktlint.get()
val ci = providers.environmentVariable("CI").isPresent

allprojects {
    pluginManager.withPlugin("com.diffplug.spotless") {
        if (!ci) {
            val applyFormatting = tasks.named("spotlessApply")
            tasks.named("check") { dependsOn(applyFormatting) }
            tasks.withType<SpotlessCheck>().configureEach { mustRunAfter(applyFormatting) }
        }
    }
}

subprojects {
    pluginManager.withPlugin("com.diffplug.spotless") {
        configure<SpotlessExtension> {
            kotlin {
                target("src/**/*.kt", "src/**/*.kts")
                ktlint(ktlintVersion)
            }
            kotlinGradle {
                ktlint(ktlintVersion)
            }
        }
        val applyFormatting = tasks.named("spotlessApply")
        val checkFormatting = tasks.named("spotlessCheck")
        val formatting = if (ci) checkFormatting else applyFormatting
        tasks.withType<KotlinCompile>().configureEach { dependsOn(formatting) }
        rootProject.tasks.named("spotlessApply") { dependsOn(applyFormatting) }
        rootProject.tasks.named("spotlessCheck") { dependsOn(checkFormatting) }
    }
}

// =============================================================================
// Update generated-examples directory
// =============================================================================
//
// The generated-examples directory contains output from the editor support
// generators. These files ARE generated by the build, but are committed to
// source control in a well-defined location for two reasons:
//
// 1. Experimentation: Users can explore syntax highlighting definitions for
//    various editors (Vim, Emacs, VS Code, Sublime, Tree-sitter) without
//    needing to set up and build the entire project.
//
// 2. Reference: The examples serve as documentation showing what the language
//    model DSL produces for each target editor format.
//
// Run `./gradlew :lang:updateGeneratedExamples` to regenerate these files
// after modifying the language model or generators.
// =============================================================================

val updateGeneratedExamples = tasks.register<Copy>("updateGeneratedExamples") {
    group = "generation"
    description = "Update the generated-examples directory with freshly generated files"

    dependsOn(project(":dsl").tasks.named("generateEditorSupport"))

    from(project(":dsl").layout.buildDirectory.dir("generated")) {
        include("xtc.tmLanguage.json")
        include("language-configuration.json")
        include("xtc.vim")
        include("xtc-mode.el")
        include("grammar.js")
        include("highlights.scm")
        include("xtc.sublime-syntax")
    }

    into(layout.projectDirectory.dir("generated-examples"))
}

// =============================================================================
// Aggregate subproject tasks
// =============================================================================

// Projects to aggregate standard lifecycle tasks from
val coreProjects = listOf(":dsl", ":tree-sitter", ":lsp-server", ":dap-server", ":intellij-plugin")
val allProjects = coreProjects + ":vscode-extension"

// Map of aggregate task -> subproject task (null means same name)
val taskMappings = mapOf(
    "build" to mapOf(":intellij-plugin" to "buildPlugin"),  // intellij uses buildPlugin
    "assemble" to emptyMap(),
    "check" to emptyMap(),
    "clean" to emptyMap()
)

taskMappings.forEach { (aggregateTask, overrides) ->
    val projects = if (aggregateTask == "clean") allProjects else coreProjects
    tasks.named(aggregateTask) {
        projects.forEach { proj ->
            val subTask = overrides[proj] ?: aggregateTask
            dependsOn(project(proj).tasks.named(subTask))
        }
    }
}

// =============================================================================
// IDE run tasks - convenience aliases for subproject tasks
// =============================================================================

val runIntellijPlugin = tasks.register("runIntellijPlugin") {
    group = "run"
    description = "Launch IntelliJ IDEA with the XTC plugin loaded for testing"
    dependsOn(project(":intellij-plugin").tasks.named("runIde"))
}

val runVsCodeExtension = tasks.register("runVsCodeExtension") {
    group = "run"
    description = "Launch VS Code with the XTC extension loaded for testing"
    dependsOn(project(":vscode-extension").tasks.named("runCode"))
}
