/**
 * A representation of HTTP status codes.
 *
 * @see [RFC 2616 §10](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html)
 * @see [RFC 7231 §8.2.3](https://datatracker.ietf.org/doc/html/rfc7231#section-8.2.3)
 */
enum HttpStatus(Int code, String reason)
    {
    Continue                        (100, "Continue"),
    SwitchingProtocols              (101, "Switching Protocols"),
    Processing                      (102, "Processing"),
    OK                              (200, "Ok"),
    Created                         (201, "Created"),
    Accepted                        (202, "Accepted"),
    NonAuthoritativeInformation     (203, "Non-Authoritative Information"),
    NoContent                       (204, "No Content"),
    ResetContent                    (205, "Reset Content"),
    PartialContent                  (206, "Partial Content"),
    MultiStatus                     (207, "Multi Status"),
    AlreadyImported                 (208, "Already imported"),
    ImUsed                          (226, "IM Used"),
    MultipleChoices                 (300, "Multiple Choices"),
    MovedPermanently                (301, "Moved Permanently"),
    Found                           (302, "Found"),
    SeeOther                        (303, "See Other"),
    NotModified                     (304, "Not Modified"),
    UseProxy                        (305, "Use Proxy"),
    SwitchProxy                     (306, "Switch Proxy"),
    TemporaryRedirect               (307, "Temporary Redirect"),
    PermanentRedirect               (308, "Permanent Redirect"),
    BadRequest                      (400, "Bad Request"),
    Unauthorized                    (401, "Unauthorized"),
    PaymentRequired                 (402, "Payment Required"),
    Forbidden                       (403, "Forbidden"),
    NotFound                        (404, "Not Found"),
    MethodNotAllowed                (405, "Method Not Allowed"),
    NotAcceptable                   (406, "Not Acceptable"),
    ProxyAuthenticationRequired     (407, "Proxy Authentication Required"),
    RequestTimeout                  (408, "Request Timeout"),
    Conflict                        (409, "Conflict"),
    Gone                            (410, "Gone"),
    LengthRequired                  (411, "Length Required"),
    PreconditionFailed              (412, "Precondition Failed"),
    PayloadTooLarge                 (413, "Payload Too Large"),
    UriTooLong                      (414, "URI Too Long"),
    UnsupportedMediaType            (415, "Unsupported Media Type"),
    RequestedRangeNotSatisfiable    (416, "Requested Range Not Satisfiable"),
    ExpectationFailed               (417, "Expectation Failed"),
    IamATeapot                      (418, "I am a teapot"),
    EnhanceYourCalm                 (420, "Enhance your calm"),
    UnprocessableEntity             (422, "Unprocessable Entity"),
    Locked                          (423, "Locked"),
    FailedDependency                (424, "Failed Dependency"),
    UnorderedCollection             (425, "Unordered Collection"),
    UpgradeRequired                 (426, "Upgrade Required"),
    PreconditionRequired            (428, "Precondition Required"),
    TooManyRequestS                 (429, "Too Many Requests"),
    RequestHeaderFieldsTooLarge     (431, "Request Header Fields Too Large"),
    NoResponse                      (444, "No Response"),
    BlockedByWindowsParentalControls(450, "Blocked by Windows Parental Controls"),
    UnavailableForLegalReasons      (451, "Unavailable For Legal Reasons"),
    RequestHeaderTooLarge           (494, "Request Header Too Large"),
    InternalServerError             (500, "Internal Server Error"),
    NotImplemented                  (501, "Not Implemented"),
    BadGateway                      (502, "Bad Gateway"),
    ServiceUnavailable              (503, "Service Unavailable"),
    GatewayTimeout                  (504, "Gateway Timeout"),
    HttpVersionNotSUPPORTED         (505, "HTTP Version Not Supported"),
    VariantAlsoNegotiates           (506, "Variant Also Negotiates"),
    InsufficientStorage             (507, "Insufficient Storage"),
    LoopDetected                    (508, "Loop Detected"),
    BandwidthLimitExceeded          (509, "Bandwidth Limit Exceeded"),
    NotExtended                     (510, "Not Extended"),
    NetworkAuthenticationRequired   (511, "Network Authentication Required"),
    ConnectionTimedOut              (522, "Connection Timed Out"),
    }