package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Int16;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int16, stored in an array of Java longs, four Int16 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸInt16ᐳ
        extends nLongBasedArray<ArrayᐸInt16ᐳ> {

    public ArrayᐸInt16ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸInt16ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸInt16ᐳ array = new ArrayᐸInt16ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸInt16ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        if (supply instanceof Int16 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸInt16ᐳ array = new ArrayᐸInt16ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFFFF;
            long fill  = value == 0 ? 0 : value | (value << 16);
            fill |= (fill << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸInt16ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸInt16ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸInt16ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Int16 getElement$p(Ctx ctx, long index) {
        return Int16.$box(getElement$pi(ctx, index));
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((Int16) value).$value);
    }

    @Override
    public ArrayᐸInt16ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((Int16) element).$value);
    }

    public ArrayᐸInt16ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, (long) value);
    }

    @Override
    public ArrayᐸInt16ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸInt16ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Int16 c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeInt16();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity16bit();
    }

    protected long $getElement(Ctx ctx, long index) {
        return $get16bitSignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set16bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len16bits(cap);
    }
}
