package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.UInt64;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of UInt64, stored in an array of Java longs.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸUInt64ᐳ
        extends nLongBasedArray<ArrayᐸUInt64ᐳ> {

    public ArrayᐸUInt64ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸUInt64ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸUInt64ᐳ array = new ArrayᐸUInt64ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸUInt64ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        if (supply instanceof UInt64 boxed) {
            ctx.alloc(size * 8); // REVIEW + HEADER_SIZE?
            ArrayᐸUInt64ᐳ array = new ArrayᐸUInt64ᐳ(ctx, type);
            array.$mut($FIXED);

            long fill = boxed.$value;

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸUInt64ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸUInt64ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸUInt64ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public UInt64 getElement$p(Ctx ctx, long index) {
        return UInt64.$box(getElement$pi(ctx, index));
    }

    public long getElement$pi(Ctx ctx, long index) {
        return $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((UInt64) value).$value);
    }

    @Override
    public ArrayᐸUInt64ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((UInt64) element).$value);
    }

    // this method must be here even though all is does is call super, otherwise the JIT
    // will not be able to find this method as it uses "invokevirtual" for the invocation
    @Override
    public ArrayᐸUInt64ᐳ add$p(Ctx ctx, long value) {
        return super.add$p(ctx, value);
    }

    @Override
    public ArrayᐸUInt64ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸUInt64ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        long n = getElement$pi(ctx, index);
        return Long.toString(n);
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeUInt64();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity64bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $storage[(int) index];
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $storage[(int) index] = value;
    }

    @Override
    protected long $cap2len(long cap) {
        return cap;
    }
}
