package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸDec128ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Dec128;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Dec128, stored in an array of Java longs, two long array elements for ech Dec128.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸDec128ᐳ
        extends nLongBasedArray<ArrayᐸDec128ᐳ> {

    public ArrayᐸDec128ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸDec128ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸDec128ᐳ array = new ArrayᐸDec128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸDec128ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Dec128 boxed) {
            ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
            ArrayᐸDec128ᐳ array = new ArrayᐸDec128ᐳ(ctx, type);
            array.$mut($FIXED);

            if (array.$growInPlace(ctx, size)) {
                long low  = boxed.$lowBits;
                long high = boxed.$highBits;
                long[] storage = array.$storage;
                for (int i = 0, len = (int) size * 2; i < len; i += 2) {
                    storage[i]   = low;
                    storage[i+1] = high;
                }
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸDec128ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸDec128ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸDec128ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Dec128 getElement(Ctx ctx, Int64 index) {
        long low = getElement$pi(ctx, index.$value);
        return Dec128.$box(low, ctx.i0);
    }

    public long getElement$p(Ctx ctx, long index) {
        return $getElement$pi(ctx, index);
    }

    public long getElement$pi(Ctx ctx, long index) {
        return $getElement$pi(ctx, index);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Dec128) value).$lowBits, ((Dec128) value).$highBits);
    }

    public void setElement$p(Ctx ctx, long index, Dec128 value) {
        setElement$pi(ctx, index, value.$lowBits, value.$highBits);
    }

    public void setElement$pi(Ctx ctx, long index, long lowValue, long highValue) {
        ctx.i0 = highValue;
        setElement$pi(ctx, index, lowValue);
    }

    public IteratorᐸDec128ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸDec128ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Dec128) element).$lowBits, ((Dec128) element).$highBits);
    }

    public ArrayᐸDec128ᐳ add$p(Ctx ctx, long lowValue, long highValue) {
        ctx.i0 = highValue;
        return super.add$p(ctx, lowValue);
    }

    public ArrayᐸDec128ᐳ insert$p(Ctx ctx, long index, long lowValue, long highValue) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $set128bitElement(index, lowValue, highValue);
        return this;
    }

    @Override
    public ArrayᐸDec128ᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    @Override
    public ArrayᐸDec128ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸDec128ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        long   low = getElement$pi(ctx, index);
        Dec128 n   = Dec128.$box(low, ctx.i0);
        return n.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity128bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get128bitElement(ctx, index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set128bitElement(index, value, ctx.i0);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len128bits(cap);
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate128BitHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete128bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert128bit(index, count);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸDec128ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.container.typeSystem.pool().typeDec128());
        }

        @Override
        public boolean next$p(Ctx ctx) {
            if (index < size$get$p(ctx)) {
                long low = getElement$pi(ctx, index++);
                // high is already in ctx.i0
                ctx.i1 = ctx.i0;
                ctx.i0 = low;
                return true;
            }
            return false;
        }
    }
}
