package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;
import org.xtclang.ecstasy.numbers.Dec32;
import org.xvm.asm.ConstantPool;
import org.xvm.asm.constants.TypeConstant;
import org.xvm.javajit.Ctx;

/**
 * Array of Dec32, stored in an array of Java longs, two Dec32 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸDec32ᐳ
        extends nLongBasedArray<ArrayᐸDec32ᐳ> {

    public ArrayᐸDec32ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸDec32ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸDec32ᐳ array = new ArrayᐸDec32ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸDec32ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸDec32ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸDec32ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸDec32ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Dec32 getElement$p(Ctx ctx, long index) {
        return Dec32.$box(getElement$pi(ctx, index));
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((Dec32) value).$bits);
    }

    @Override
    public ArrayᐸDec32ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((Dec32) element).$bits);
    }

    public ArrayᐸDec32ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    @Override
    public ArrayᐸDec32ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸDec32ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        Dec32 c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeDec32();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity32bit();
    }

    protected long $getElement(Ctx ctx, long index) {
        return $get32bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set32bitElement(index, value);
    }

    @Override
    protected int $cap2len(int cap) {
        return $cap2len32bits(cap);
    }
}
