package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.UInt128;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of UInt128, stored in an array of Java longs, two long array elements for ech UInt128.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸUInt128ᐳ
        extends nLongBasedArray<ArrayᐸUInt128ᐳ> {

    public ArrayᐸUInt128ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸUInt128ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸUInt128ᐳ array = new ArrayᐸUInt128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸUInt128ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        if (supply instanceof UInt128 boxed) {
            ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
            ArrayᐸUInt128ᐳ array = new ArrayᐸUInt128ᐳ(ctx, type);
            array.$mut($FIXED);

            if (array.$growInPlace(ctx, size)) {
                long low  = boxed.$lowValue;
                long high = boxed.$highValue;
                long[] storage = array.$storage;
                for (int i = 0, len = (int) size * 2; i < len; i += 2) {
                    storage[i]   = low;
                    storage[i+1] = high;
                }
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸUInt128ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸUInt128ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸUInt128ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public UInt128 getElement$p(Ctx ctx, long index) {
        long low = getElement$pi(ctx, index);
        return UInt128.$box(low, ctx.i0);
    }

    public long getElement$pi(Ctx ctx, long index) {
        return $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((UInt128) value).$lowValue, ((UInt128) value).$highValue);
    }

    public void setElement$pi(Ctx ctx, long index, long lowValue, long highValue) {
        ctx.i0 = highValue;
        setElement$pi(ctx, index, lowValue);
    }

    @Override
    public ArrayᐸUInt128ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((UInt128) element).$lowValue, ((UInt128) element).$highValue);
    }

    public ArrayᐸUInt128ᐳ add$p(Ctx ctx, long lowValue, long highValue) {
        ctx.i0 = highValue;
        return super.add$p(ctx, lowValue);
    }

    @Override
    public ArrayᐸUInt128ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸUInt128ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        UInt128 n = getElement$p(ctx, index);
        return n.toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeUInt128();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity128bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get128bitElement(ctx, index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set128bitElement(index, value, ctx.i0);
    }

    @Override
    protected int $cap2len(int cap) {
        return $cap2len128bits(cap);
    }
}
