package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.UInt32;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of UInt32, stored in an array of Java longs, two UInt32 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸUInt32ᐳ
        extends nLongBasedArray<ArrayᐸUInt32ᐳ> {

    public ArrayᐸUInt32ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸUInt32ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸUInt32ᐳ array = new ArrayᐸUInt32ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸUInt32ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        if (supply instanceof UInt32 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸUInt32ᐳ array = new ArrayᐸUInt32ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFFFFFFFFL;
            long fill  = value == 0 ? 0 : value | (value << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸUInt32ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸUInt32ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸUInt32ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public UInt32 getElement$p(Ctx ctx, long index) {
        return UInt32.$box(getElement$pi(ctx, index));
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((UInt32) value).$value);
    }

    @Override
    public ArrayᐸUInt32ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((UInt32) element).$value);
    }

    public ArrayᐸUInt32ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    @Override
    public ArrayᐸUInt32ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸUInt32ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        UInt32 c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity32bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get32bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set32bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len32bits(cap);
    }
}
