package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Int8;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int8, stored in an array of Java longs, eight Int8 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸInt8ᐳ
        extends nLongBasedArray<ArrayᐸInt8ᐳ> {

    public ArrayᐸInt8ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸInt8ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸInt8ᐳ array = new ArrayᐸInt8ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸInt8ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        if (supply instanceof Int8 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸInt8ᐳ array = new ArrayᐸInt8ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFF;
            long fill  = value == 0 ? 0 : value | (value << 8) | (value << 16) | (value << 24);
            fill |= (fill << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸInt8ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸInt8ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸInt8ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Int8 getElement$p(Ctx ctx, long index) {
        return Int8.$box(getElement$pi(ctx, index));
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((Int8) value).$value);
    }

    @Override
    public ArrayᐸInt8ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((Int8) element).$value);
    }

    public ArrayᐸInt8ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    @Override
    public ArrayᐸInt8ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸInt8ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Int8 c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity8bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get8bitSignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set8bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len8bits(cap);
    }
}
