package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸInt128ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;

import org.xtclang.ecstasy.numbers.Int128;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int128, stored in an array of Java longs, two long array elements for ech Int128.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸInt128ᐳ
        extends nLongLongBasedArray<ArrayᐸInt128ᐳ> {

    public ArrayᐸInt128ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸInt128ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸInt128ᐳ array = new ArrayᐸInt128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸInt128ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Int128 boxed) {
            ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
            ArrayᐸInt128ᐳ array = new ArrayᐸInt128ᐳ(ctx, type);
            array.$mut($FIXED);
            array.$fill128(ctx, size, boxed.$lowValue, boxed.$highValue);
            return array;
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸInt128ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        long size = elements.size$get$p(ctx);
        ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
        ArrayᐸInt128ᐳ array = new ArrayᐸInt128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.addAll(ctx, elements);
        array.$mut((int) mutability.ordinal$get$p(ctx));
        return array;
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸInt128ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸInt128ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Int128 getElement(Ctx ctx, Int64 index) {
        long low = getElement$pi(ctx, index.$value);
        return Int128.$box(low, ctx.i0);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Int128) value).$lowValue, ((Int128) value).$highValue);
    }

    public IteratorᐸInt128ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸInt128ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Int128) element).$lowValue, ((Int128) element).$highValue);
    }

    public ArrayᐸInt128ᐳ add$p(Ctx ctx, long lowValue, long highValue) {
        return $add128(ctx, lowValue, highValue);
    }

    public ArrayᐸInt128ᐳ insert$p(Ctx ctx, long index, long lowValue, long highValue) {
        return $insert128(ctx, index, lowValue, highValue);
    }

    @Override
    public ArrayᐸInt128ᐳ delete$p(Ctx ctx, long index) {
        return $delete128(ctx, index);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        long   low = getElement$pi(ctx, index);
        Int128 n   = Int128.$box(low, ctx.i0);
        return n.toString(ctx).toString();
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends n128BitIterator implements IteratorᐸInt128ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.pool().typeInt128());
        }
    }
}
