package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸInt32ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Int32;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int32, stored in an array of Java longs, two Int32 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸInt32ᐳ
        extends nLongBasedArray<ArrayᐸInt32ᐳ> {

    public ArrayᐸInt32ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸInt32ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸInt32ᐳ array = new ArrayᐸInt32ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸInt32ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Int32 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸInt32ᐳ array = new ArrayᐸInt32ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFFFFFFFFL;
            long fill  = value == 0 ? 0 : value | (value << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸInt32ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        long size = elements.size$get$p(ctx);
        ctx.alloc(size * 4); // REVIEW + HEADER_SIZE?
        ArrayᐸInt32ᐳ array = new ArrayᐸInt32ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.addAll(ctx, elements);
        array.$mut((int) mutability.ordinal$get$p(ctx));
        return array;
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸInt32ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸInt32ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Int32 getElement(Ctx ctx, Int64 index) {
        return Int32.$box(getElement$pi(ctx, index.$value));
    }

    public int getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Int32) value).$value);
    }

    public void setElement$p(Ctx ctx, long index, int value) {
        setElement$pi(ctx, index, value);
    }

    public IteratorᐸInt32ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸInt32ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Int32) element).$value);
    }

    public ArrayᐸInt32ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    public ArrayᐸInt32ᐳ insert$p(Ctx ctx, long index, int value) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $set32bitElement(index, value);
        return this;
    }

    @Override
    public ArrayᐸInt32ᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    @Override
    public ArrayᐸInt32ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸInt32ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Int32 c = Int32.$box(getElement$pi(ctx, index));
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity32bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get32bitSignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set32bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len32bits(cap);
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate32BitSignedHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete32bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert32bit(index, count);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸInt32ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.container.typeSystem.pool().typeInt32());
        }
    }
}
