package org.xtclang.ecstasy.collections;

import java.math.BigInteger;

import java.util.Arrays;

import org.xtclang.ecstasy.Exception;
import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸBitᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;

import org.xtclang.ecstasy.numbers.Bit;
import org.xtclang.ecstasy.numbers.Int64;
import org.xtclang.ecstasy.numbers.IntN;
import org.xtclang.ecstasy.numbers.UIntN;

import org.xtclang.ecstasy.text.String;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Bit, stored in an array of Java longs, sixty-four Bits per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸBitᐳ
        extends nLongBasedArray<ArrayᐸBitᐳ> {

    public ArrayᐸBitᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸBitᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸBitᐳ array = new ArrayᐸBitᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸBitᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Bit boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸBitᐳ array = new ArrayᐸBitᐳ(ctx, type);
            array.$mut($FIXED);

            long fill = boxed.$value == 0 ? 0 : -1L;

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸBitᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        long size = elements.size$get$p(ctx);
        ctx.alloc(size / 8); // REVIEW + HEADER_SIZE?
        ArrayᐸBitᐳ array = new ArrayᐸBitᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.addAll(ctx, elements);
        array.$mut((int) mutability.ordinal$get$p(ctx));
        return array;
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸBitᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸBitᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Bit getElement(Ctx ctx, Int64 index) {
        return Bit.$box(getElement$pi(ctx, index.$value));
    }

    public int getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Bit) value).$value);
    }

    public void setElement$p(Ctx ctx, long index, int value) {
        setElement$pi(ctx, index, value);
    }

    public IteratorᐸBitᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸBitᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Bit) element).$value);
    }

    public ArrayᐸBitᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    public ArrayᐸBitᐳ insert$p(Ctx ctx, long index, int value) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $set1bitElement(index, value);
        return this;
    }

    @Override
    public ArrayᐸBitᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    // TODO remove this when it can be generated by the JIT
    @Override
    public long estimateStringLength$p(Ctx ctx) {
        return size$get$p(ctx) + 2;
    }

    // TODO remove this when it can be generated by the JIT
    @Override
    public String toString(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toString(ctx);
        }
        int           cb = (int) size$get$p(ctx);
        StringBuilder sb = new StringBuilder();
        sb.append("0b");
        for (int i = 0; i < cb; i++) {
            long bit = (($storage[i >>> 6] >>> (63 - (i & 0x3F))) & 1L);
            sb.append(bit);
        }
        return String.of(ctx, sb.toString());
    }

    // ----- conversion ----------------------------------------------------------------------------

    /**
     * The native implementation of:
     *     Int8 toInt8(Boolean checkBounds = False)
     */
    public int toInt8$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toInt(ctx);
        if (check && (n < Byte.MIN_VALUE || n > Byte.MAX_VALUE)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid Int8 value");
        }
        return (byte) n;
    }

    /**
     * The native implementation of:
     *     Int16 toInt16(Boolean checkBounds = False)
     */
    public int toInt16$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toInt(ctx);
        if (check && (n < Short.MIN_VALUE || n > Short.MAX_VALUE)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid Int16 value");
        }
        return (short) n;
    }

    /**
     * The native implementation of:
     *     Int32 toInt32(Boolean checkBounds = False)
     */
    public int toInt32$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toInt(ctx);
        if (check && (n < Integer.MIN_VALUE || n > Integer.MAX_VALUE)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid Int32 value");
        }
        return (int) n;
    }

    /**
     * The native implementation of:
     *     Int toInt(Boolean checkBounds = False)
     */
    public long toInt$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        return toInt64$p(ctx, checkBounds, dfltCheckBounds);
    }

    /**
     * The native implementation of:
     *     Int64 toInt64(Boolean checkBounds = False)
     */
    public long toInt64$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        long size = size$get$p(ctx);
        long n;

        if (size <= 64) {
            n = $storage[0] >> (64 - size);
        } else {
            IntN i = toIntN(ctx);
            n = i.toInt64$p(ctx, checkBounds, dfltCheckBounds);
        }
        return n;
    }

    /**
     * The native implementation of:
     *     Int128 toInt128(Boolean checkBounds = False)
     */
    public long toInt128$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        IntN i = toIntN(ctx);
        return i.toInt128$p(ctx, checkBounds, dfltCheckBounds);
    }

    /**
     * The native implementation of:
     *     IntN toIntN()
     */
    public IntN toIntN(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toIntN(ctx);
        }
        return IntN.$box($toBigInteger(ctx, true));
    }

    /**
     * The native implementation of:
     *     Nibble toNibble(Boolean checkBounds = False)
     */
    public int toNibble$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toUInt(ctx);
        if (check && (n < 0 || n > 0xF)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid Nibble value");
        }
        return (byte) n & 0xF;
    }

    /**
     * The native implementation of:
     *     Byte toByte(Boolean checkBounds = False)
     */
    public int toByte$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        return toUInt8$p(ctx, checkBounds, dfltCheckBounds);
    }

    /**
     * The native implementation of:
     *     UInt8 toUInt8(Boolean checkBounds = False)
     */
    public int toUInt8$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toUInt(ctx);
        if (check && (n < 0 || n > 0xFFL)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid UInt8 value");
        }
        return (byte) n & 0xFF;
    }

    /**
     * The native implementation of:
     *     UInt16 toUInt16(Boolean checkBounds = False)
     */
    public int toUInt16$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toUInt(ctx);
        if (check && (n < 0 || n > 0xFFFFL)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid UInt16 value");
        }
        return (short) n & 0xFFFF;
    }

    /**
     * The native implementation of:
     *     UInt32 toUInt32(Boolean checkBounds = False)
     */
    public int toUInt32$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        boolean check = !dfltCheckBounds && checkBounds;
        long    n     = $toUInt(ctx);
        if (check && (n < 0 || n > 0xFFFFFFFFL)) {
            throw Exception.$oob(ctx, "Bit[] is not a valid UInt32 value");
        }
        return (int) n;
    }

    /**
     * The native implementation of:
     *     UInt toUInt(Boolean checkBounds = False)
     */
    public long toUInt$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        return toUInt64$p(ctx, checkBounds, dfltCheckBounds);
    }

    /**
     * The native implementation of:
     *     UInt64 toUInt64(Boolean checkBounds = False)
     */
    public long toUInt64$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        long size = size$get$p(ctx);
        long n;

        if (size == 64) {
            n = $storage[0];
        } else if (size <= 64) {
            n = $storage[0] >>> (64 - size);
        } else {
            UIntN i = toUIntN(ctx);
            n = i.toUInt64$p(ctx, checkBounds, dfltCheckBounds);
        }
        return n;
    }

    /**
     * The native implementation of:
     *     UInt128 toUInt128(Boolean checkBounds = False)
     */
    public long toUInt128$p(Ctx ctx, boolean checkBounds, boolean dfltCheckBounds) {
        if ($delegate != null) {
            return $delegate.toUInt8$p(ctx, checkBounds, dfltCheckBounds);
        }
        long size = size$get$p(ctx);
        if (size == 128) {
            ctx.i0 = $storage[0];
            return $storage[1];
        } else if (size <= 64) {
            ctx.i0 = 0;
            return $storage[0] >>> (64 - size);
        } else if (size < 128) { // size 64 >..< 128
            ctx.i0 = $storage[0] >>> (128 - size);
            return ($storage[1] >>> (128 - size)) & ($storage[0] << (128 - size));
        } else {
            UIntN i = toUIntN(ctx);
            return i.toUInt128$p(ctx, checkBounds, dfltCheckBounds);
        }
    }

    /**
     * The native implementation of:
     *     UIntN toUIntN()
     */
    public UIntN toUIntN(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toUIntN(ctx);
        }
        BigInteger bi = new BigInteger(1, $toJavaByteArray(ctx));
        return UIntN.$box(bi);
    }

    /**
     * The primitive implementation of:
     *     Dec32 toDec32()
     */
    public int toDec32$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toDec32$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 32) {
            throw Exception.$oob(ctx, "\"size == 32\": size=" + size);
        }
        return (int) ($storage[0] >>> 32);
    }

    /**
     * The primitive implementation of:
     *     Dec64 toDec64()
     */
    public long toDec64$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toDec64$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 64) {
            throw Exception.$oob(ctx, "\"size == 64\": size=" + size);
        }
        return $storage[0];
    }

    /**
     * The primitive implementation of:
     *     Dec128 toDec128()
     */
    public long toDec128$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toDec128$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 128) {
            throw Exception.$oob(ctx, "\"size == 128\": size=" + size);
        }
        ctx.i0 = $storage[0];
        return $storage[1];
    }

    /**
     * The primitive implementation of:
     *     Float8e4 toFloat8e4()
     */
    public int toFloat8e4$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat8e4$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 8) {
            throw Exception.$oob(ctx, "\"size == 8\": size=" + size);
        }
        return (int) ($storage[0] >>> 56);
    }

    /**
     * The primitive implementation of:
     *     Float8e5 toFloat8e5()
     */
    public int toFloat8e5$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat8e5$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 8) {
            throw Exception.$oob(ctx, "\"size == 8\": size=" + size);
        }
        return (int) ($storage[0] >>> 56);
    }

    /**
     * The primitive implementation of:
     *     BFloat16 toBFloat16()
     */
    public int toBFloat16$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toBFloat16$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 16) {
            throw Exception.$oob(ctx, "\"size == 16\": size=" + size);
        }
        return (int) ($storage[0] >>> 48);
    }

    /**
     * The primitive implementation of:
     *     Float16 toFloat16()
     */
    public int toFloat16$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat16$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 16) {
            throw Exception.$oob(ctx, "\"size == 16\": size=" + size);
        }
        return (int) ($storage[0] >>> 48);
    }

    /**
     * The primitive implementation of:
     *     Float32 toFloat32()
     */
    public int toFloat32$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat32$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 32) {
            throw Exception.$oob(ctx, "\"size == 32\": size=" + size);
        }
        return (int) ($storage[0] >>> 32);
    }

    /**
     * The primitive implementation of:
     *     Float64 toFloat64()
     */
    public long toFloat64$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat64$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 64) {
            throw Exception.$oob(ctx, "\"size == 64\": size=" + size);
        }
        return $storage[0];
    }

    /**
     * The primitive implementation of:
     *     Float128 toFloat128()
     */
    public long toFloat128$p(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toFloat128$p(ctx);
        }
        long size = size$get$p(ctx);
        if (size != 128) {
            throw Exception.$oob(ctx, "\"size == 128\": size=" + size);
        }
        ctx.i0 = $storage[0];
        return $storage[1];
    }

    /**
     * The native implementation of:
     *     Byte[] asByteArray()
     */
    public ArrayᐸUInt8ᐳ asByteArray(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.asByteArray(ctx);
        }
        long size = size$get$p(ctx);
        if (size % 8 != 0) {
            throw Exception.$oob(ctx, "Bit[] size is not a multiple of 8");
        }
        Mutability mut = mutability$get(ctx);
        long[]     an  = mut.equals(Mutability.Constant.$INSTANCE)
                            ? $storage : Arrays.copyOf($storage, $storage.length);
        return ArrayᐸUInt8ᐳ.$fromLongs(ctx, mut, size / 8, an);
    }

    // ----- Array internals -----------------------------------------------------------------------


    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        int i = getElement$pi(ctx, index);
        return java.lang.String.valueOf(i);
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity1bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get1bitElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set1bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len1bit(cap);
    }

    // ----- helper methods ------------------------------------------------------------------------

    /**
     * Internal method to create a constant bit array from a long array.
     *
     * @param bits  the size of the array in bits
     */
    public static ArrayᐸBitᐳ $fromLongs(Ctx ctx, long bits, long... values) {
        return $fromLongs(ctx, null, bits, values);
    }

    /**
     * Internal method to create a bit array from a long array.
     *
     * @param bits  the size of the array in bits
     */
    public static ArrayᐸBitᐳ $fromLongs(Ctx ctx, Mutability mutability, long bits, long... values) {
        TypeConstant type  = ctx.pool().typeBitArray();
        ArrayᐸBitᐳ   array = $new$p(ctx, type, bits, false);
        array.$mut(mutability == null ? $CONSTANT : (int) mutability.$ordinal);
        array.$storage = values;
        array.$size((int) bits);
        return array;
    }

    /**
     * Read a 64-bit segment of this array.
     * Used by {@link org.xvm.javajit.builders.NumberBuilder#loadConstructorLong}.
     *
     * @param index  the index of the 64-bit segment
     *
     * @return the segment, with the first bit stored in its most significant position
     */
    public long $toLong(Ctx ctx, int index) {
        long start = (long) index << 6;
        long count = Math.min(size$get$p(ctx) - start, Long.SIZE);
        long value = 0;
        for (long offset = 0; offset < count; offset++) {
            value |= (long) getElement$pi(ctx, start + offset) << (63 - offset);
        }
        return value;
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate1BitHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete1bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert1bit(index, count);
    }

    /**
     * Return this bit array converted to a Java byte array.
     * <p>
     * The bits of the byte array will be in reverse order to this bit array, that is, the byte
     * at index zero will contain bits from index (size - 8)..(size - 1).
     * <p>
     * If the size of this bit array is not a multiple of eight, the byte at index zero will be
     * sign extended to 8-bits.
     * <p>
     * This method is typically used to convert this bit array to Java numbers such as
     * {@link java.math.BigInteger} or {@link java.math.BigDecimal} that require bytes in the
     * opposite order to this bit array.
     */
    public byte[] $toJavaByteArray(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.$toJavaByteArray(ctx);
        }

        int    bitCount = (int) size$get$p(ctx);
        int    cb       = (bitCount + 7) / 8;
        byte[] ab       = new byte[cb];
        int    shift    = 0;
        int    idx      = cb - 1;
        long   bit      = 0;

        for (int i = bitCount - 1; i >= 0; i--) {
            bit = (($storage[i >>> 6] >>> (63 - (i & 0x3F))) & 1L) << shift;
            ab[idx] += (byte) bit;
            shift++;
            if (shift == 8) {
                shift = 0;
                idx--;
            }
        }

        return ab;
    }

    /**
     * Convert this bit array to an Int64 (Java long) value.
     */
    protected long $toInt(Ctx ctx) {
        if ($storage.length == 0 || $storage[0] == 0) {
            return 0;
        }
        long size = size$get$p(ctx);
        long n;

        if (size <= 64) {
            n = $storage[0] >> (64 - size);
        } else {
            IntN i = toIntN(ctx);
            n = i.toInt64$p(ctx, true, false);
        }
        return n;
    }

    /**
     * Convert this bit array to a UInt64 (Java long) value.
     */
    protected long $toUInt(Ctx ctx) {
        if ($storage.length == 0 || $storage[0] == 0) {
            return 0;
        }
        long size = size$get$p(ctx);
        long n;

        if (size <= 64) {
            n = $storage[0] >>> (64 - size);
        } else {
            UIntN i = toUIntN(ctx);
            n = i.toUInt64$p(ctx, true, false);
        }
        return n;
    }

    /**
     * Convert this bit array to a {@link BigInteger}.
     * <p>
     * Called by the JIT in from IntN and UIntN constructors
     */
    public BigInteger $toBigInteger(Ctx ctx, boolean signed) {
        int bitCount = (int) size$get$p(ctx);

        BigInteger bi;
        if (bitCount == 64) {
            if (signed) {
                bi = BigInteger.valueOf($storage[0]);
            } else {
                bi = $toUnsignedBigInteger($storage[0]);
            }
        } else if (bitCount < 64) {
            if (signed) {
                bi =  BigInteger.valueOf($storage[0] >> (64 - bitCount));
            } else {
                bi = $toUnsignedBigInteger($storage[0] >>> (64 - bitCount));
            }
        } else {
            if (signed) {
                bi = new BigInteger($toJavaByteArray(ctx));
            } else {
                bi = new BigInteger(1, $toJavaByteArray(ctx));
            }
        }
        return bi;
    }

    private static BigInteger $toUnsignedBigInteger(long value) {
        if (value >= 0L) {
            return BigInteger.valueOf(value);
        }
        int nHigh = (int) (value >>> 32);
        int nLow  = (int) value;
        return (BigInteger.valueOf(Integer.toUnsignedLong(nHigh))).shiftLeft(32).
                add(BigInteger.valueOf(Integer.toUnsignedLong(nLow)));
    }


    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸBitᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.pool().typeBit());
        }
    }
}
