package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IterableᐸFloat8e4ᐳ;
import org.xtclang.ecstasy.IteratorᐸFloat8e4ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;

import org.xtclang.ecstasy.numbers.Float8e4;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Float8e4, stored in an array of Java longs, eight Float8e4 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸFloat8e4ᐳ
        extends nLongBasedArray<ArrayᐸFloat8e4ᐳ> {

    public ArrayᐸFloat8e4ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸFloat8e4ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸFloat8e4ᐳ array = new ArrayᐸFloat8e4ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸFloat8e4ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Float8e4 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸFloat8e4ᐳ array = new ArrayᐸFloat8e4ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFF;
            long fill  = value == 0 ? 0 : value | (value << 8) | (value << 16) | (value << 24);
            fill |= (fill << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸFloat8e4ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        long size = elements.size$get$p(ctx);
        ctx.alloc(size); // REVIEW + HEADER_SIZE?
        ArrayᐸFloat8e4ᐳ array = new ArrayᐸFloat8e4ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.addAll(ctx, elements);
        array.$mut((int) mutability.ordinal$get$p(ctx));
        return array;
    }

    public static ArrayᐸFloat8e4ᐳ $new$2(Ctx ctx, TypeConstant type, Mutability mutability,
                                            IterableᐸFloat8e4ᐳ elements) {
        return $new$2$p(ctx, type, mutability, elements);
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸFloat8e4ᐳ $new$3(Ctx ctx, TypeConstant type, ArrayᐸFloat8e4ᐳ that) {
        return $new$2$p(ctx, type, that.mutability$get(ctx), (Iterable) that);
    }

    public Float8e4 getElement(Ctx ctx, Int64 index) {
        return Float8e4.$box(getElement$pi(ctx, index.$value));
    }

    public int getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Float8e4) value).$value);
    }

    public void setElement$p(Ctx ctx, long index, int value) {
        setElement$pi(ctx, index, value);
    }

    public IteratorᐸFloat8e4ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸFloat8e4ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Float8e4) element).$value);
    }

    public ArrayᐸFloat8e4ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    public ArrayᐸFloat8e4ᐳ insert$p(Ctx ctx, long index, int value) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $set8bitElement(index, value);
        return this;
    }

    @Override
    public ArrayᐸFloat8e4ᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        Float8e4 c = Float8e4.$box(getElement$pi(ctx, index));
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity8bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get8bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set8bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len8bits(cap);
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate8BitUnsignedHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete8bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert8bit(index, count);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸFloat8e4ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.pool().typeFloat8e4());
        }
    }
}
