package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸDec128ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;

import org.xtclang.ecstasy.numbers.Dec128;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Dec128, stored in an array of Java longs, two long array elements for ech Dec128.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸDec128ᐳ
        extends nLongLongBasedArray<ArrayᐸDec128ᐳ> {

    public ArrayᐸDec128ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸDec128ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸDec128ᐳ array = new ArrayᐸDec128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸDec128ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Dec128 boxed) {
            ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
            ArrayᐸDec128ᐳ array = new ArrayᐸDec128ᐳ(ctx, type);
            array.$mut($FIXED);
            array.$fill128(ctx, size, boxed.$lowBits, boxed.$highBits);
            return array;
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸDec128ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        long size = elements.size$get$p(ctx);
        ctx.alloc(size * 16); // REVIEW + HEADER_SIZE?
        ArrayᐸDec128ᐳ array = new ArrayᐸDec128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.addAll(ctx, elements);
        array.$mut((int) mutability.ordinal$get$p(ctx));
        return array;
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸDec128ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸDec128ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Dec128 getElement(Ctx ctx, Int64 index) {
        long low = getElement$pi(ctx, index.$value);
        return Dec128.$box(low, ctx.i0);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Dec128) value).$lowBits, ((Dec128) value).$highBits);
    }

    public IteratorᐸDec128ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸDec128ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Dec128) element).$lowBits, ((Dec128) element).$highBits);
    }

    public ArrayᐸDec128ᐳ add$p(Ctx ctx, long lowValue, long highValue) {
        return $add128(ctx, lowValue, highValue);
    }

    public ArrayᐸDec128ᐳ insert$p(Ctx ctx, long index, long lowValue, long highValue) {
        return $insert128(ctx, index, lowValue, highValue);
    }

    @Override
    public ArrayᐸDec128ᐳ delete$p(Ctx ctx, long index) {
        return $delete128(ctx, index);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        long   low = getElement$pi(ctx, index);
        Dec128 n   = Dec128.$box(low, ctx.i0);
        return n.toString(ctx).toString();
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends n128BitIterator implements IteratorᐸDec128ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.pool().typeDec128());
        }
    }
}
