package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸInt16ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Int16;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int16, stored in an array of Java longs, four Int16 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸInt16ᐳ
        extends nLongBasedArray<ArrayᐸInt16ᐳ> {

    public ArrayᐸInt16ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * @see {@link Array#$new$p}
     */
    public static ArrayᐸInt16ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸInt16ᐳ array = new ArrayᐸInt16ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    /**
     * @see {@link Array#$new$1$p}
     */
    public static ArrayᐸInt16ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof Int16 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸInt16ᐳ array = new ArrayᐸInt16ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = boxed.$value & 0xFFFF;
            long fill  = value == 0 ? 0 : value | (value << 16);
            fill |= (fill << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$2}
     */
    public static ArrayᐸInt16ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    /**
     * @see {@link Array#$new$3}
     */
    public static ArrayᐸInt16ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸInt16ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Int16 getElement(Ctx ctx, Int64 index) {
        return Int16.$box(getElement$pi(ctx, index.$value));
    }

    public int getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, ((Int16) value).$value);
    }

    public void setElement$p(Ctx ctx, long index, int value) {
        setElement$pi(ctx, index, value);
    }

    public IteratorᐸInt16ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸInt16ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, ((Int16) element).$value);
    }

    public ArrayᐸInt16ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, (long) value);
    }

    public ArrayᐸInt16ᐳ insert$p(Ctx ctx, long index, int value) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $set16bitElement(index, value);
        return this;
    }

    @Override
    public ArrayᐸInt16ᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    @Override
    public ArrayᐸInt16ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸInt16ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Int16 c = Int16.$box(getElement$pi(ctx, index));
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity16bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get16bitSignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set16bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len16bits(cap);
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate16BitSignedHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete16bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert16bit(index, count);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸInt16ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.container.typeSystem.pool().typeInt16());
        }
    }
}
