package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸFloat64ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Float64;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Float64, stored in an array of Java longs.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸFloat64ᐳ
        extends nLongBasedArray<ArrayᐸFloat64ᐳ> {

    public ArrayᐸFloat64ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸFloat64ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸFloat64ᐳ array = new ArrayᐸFloat64ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸFloat64ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof org.xtclang.ecstasy.numbers.Float64 boxed) {
            ctx.alloc(size * 8); // REVIEW + HEADER_SIZE?
            ArrayᐸFloat64ᐳ array = new ArrayᐸFloat64ᐳ(ctx, type);
            array.$mut($FIXED);

            long fill = Double.doubleToRawLongBits(boxed.$value);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸFloat64ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸFloat64ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸFloat64ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Float64 getElement(Ctx ctx, Int64 index) {
        return Float64.$box(getElement$pi(ctx, index.$value));
    }

    public double getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public double getElement$pi(Ctx ctx, long index) {
        return Double.longBitsToDouble($getElement$pi(ctx, index));
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, Double.doubleToRawLongBits(((Float64) value).$value));
    }

    public void setElement$p(Ctx ctx, long index, double value) {
        setElement$pi(ctx, index, Double.doubleToRawLongBits(value));
    }

    public void setElement$pi(Ctx ctx, long index, double value) {
        setElement$pi(ctx, index, Double.doubleToRawLongBits(value));
    }

    public IteratorᐸFloat64ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸFloat64ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, Double.doubleToRawLongBits(((Float64) element).$value));
    }

    public ArrayᐸFloat64ᐳ add$p(Ctx ctx, double value) {
        return super.add$p(ctx, Double.doubleToRawLongBits(value));
    }

    public ArrayᐸFloat64ᐳ insert$p(Ctx ctx, long index, double value) {
        if (index < 0 || index > size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $insert(ctx, index, 1);
        $storage[(int) index] = Double.doubleToRawLongBits(value);
        return this;
    }

    @Override
    public ArrayᐸFloat64ᐳ delete$p(Ctx ctx, long index) {
        if (index < 0 || index >= size$get$p(ctx)) {
            throw $oob(ctx, index);
        }
        $delete(ctx, index, 1);
        return this;
    }

    @Override
    public ArrayᐸFloat64ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸFloat64ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        Float64 n = Float64.$box(getElement$pi(ctx, index));
        return n.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity64bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $storage[(int) index];
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $storage[(int) index] = value;
    }

    @Override
    protected long $cap2len(long cap) {
        return cap;
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate64BitHash(ctx);
    }

    @Override
    protected void $deleteElements(long index, long count) {
        $delete64bit(index, count);
    }

    @Override
    protected void $insertElements(long index, long count) {
        $insert64bit(index, count);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸFloat64ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.container.typeSystem.pool().typeFloat64());
        }
    }
}
