package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.IteratorᐸFloat32ᐳ;
import org.xtclang.ecstasy.Object;
import org.xtclang.ecstasy.nType;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Float32;
import org.xtclang.ecstasy.numbers.Int64;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Float32, stored in an array of Java longs, two Float32 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class ArrayᐸFloat32ᐳ
        extends nLongBasedArray<ArrayᐸFloat32ᐳ> {

    public ArrayᐸFloat32ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static ArrayᐸFloat32ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        ArrayᐸFloat32ᐳ array = new ArrayᐸFloat32ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static ArrayᐸFloat32ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, Object supply) {
        if (supply instanceof org.xtclang.ecstasy.numbers.Float32 boxed) {
            ctx.alloc(size); // REVIEW + HEADER_SIZE?
            ArrayᐸFloat32ᐳ array = new ArrayᐸFloat32ᐳ(ctx, type);
            array.$mut($FIXED);

            long value = Float.floatToRawIntBits(boxed.$value) & 0xFFFFFFFFL;
            long fill  = value == 0 ? 0 : value | (value << 32);

            if (array.$growInPlace(ctx, size)) {
                Arrays.fill(array.$storage, fill);
                array.$size((int) size);
                return array;
            } else {
                throw array.$oob(ctx, size);
            }
        }
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸFloat32ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static ArrayᐸFloat32ᐳ $new$3$p(Ctx ctx, TypeConstant type, ArrayᐸFloat32ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public Float32 getElement(Ctx ctx, Int64 index) {
        return Float32.$box(getElement$pi(ctx, index.$value));
    }

    public float getElement$p(Ctx ctx, long index) {
        return getElement$pi(ctx, index);
    }

    public float getElement$pi(Ctx ctx, long index) {
        return Float.intBitsToFloat((int) $getElement$pi(ctx, index));
    }

    public void setElement(Ctx ctx, Int64 index, Object value) {
        setElement$pi(ctx, index.$value, Float.floatToRawIntBits(((Float32) value).$value));
    }

    public void setElement$p(Ctx ctx, long index, float value) {
        setElement$pi(ctx, index, Float.floatToRawIntBits(value));
    }

    public void setElement$pi(Ctx ctx, long index, float value) {
        setElement$pi(ctx, index, Float.floatToRawIntBits(value));
    }

    public IteratorᐸFloat32ᐳ iterator(Ctx ctx) {
        return new nIterator(ctx);
    }

    @Override
    public ArrayᐸFloat32ᐳ add(Ctx ctx, Object element) {
        return add$p(ctx, Float.floatToRawIntBits(((Float32) element).$value));
    }

    public ArrayᐸFloat32ᐳ add$p(Ctx ctx, float value) {
        return super.add$p(ctx, Float.floatToRawIntBits(value));
    }

    @Override
    public ArrayᐸFloat32ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (ArrayᐸFloat32ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        Float32 c = Float32.$box(getElement$p(ctx, index));
        return c.toString(ctx).toString();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity32bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get32bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set32bitElement(index, value);
    }

    @Override
    protected long $cap2len(long cap) {
        return $cap2len32bits(cap);
    }

    @Override
    protected long $calculateHash(Ctx ctx) {
        return $calculate32BitUnsignedHash(ctx);
    }

    // ---- Iterator implementation ----------------------------------------------------------------

    private class nIterator extends nBaseIterator implements IteratorᐸFloat32ᐳ {
        public nIterator(Ctx ctx) {
            super(ctx);
        }

        @Override
        public nType Element$get(Ctx ctx) {
            return nType.$ensureType(ctx, ctx.container.typeSystem.pool().typeFloat32());
        }
    }
}
