package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.Int128;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Int128, stored in an array of Java longs, two long array elements for ech Int128.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class nArrayᐸInt128ᐳ
        extends nLongBasedArray<nArrayᐸInt128ᐳ> {

    public nArrayᐸInt128ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static nArrayᐸInt128ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        nArrayᐸInt128ᐳ array = new nArrayᐸInt128ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static nArrayᐸInt128ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸInt128ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸInt128ᐳ $new$3$p(Ctx ctx, TypeConstant type, nArrayᐸInt128ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Int128 getElement$p(Ctx ctx, long index) {
        long low = getElement$pi(ctx, index);
        return Int128.$box(low, ctx.i0);
    }

    public long getElement$pi(Ctx ctx, long index) {
        return $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((Int128) value).$lowValue, ((Int128) value).$highValue);
    }

    public void setElement$pi(Ctx ctx, long index, long lowValue, long highValue) {
        ctx.i0 = highValue;
        setElement$pi(ctx, index, lowValue);
    }

    @Override
    public nArrayᐸInt128ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((Int128) element).$lowValue, ((Int128) element).$highValue);
    }

    public nArrayᐸInt128ᐳ add$p(Ctx ctx, long lowValue, long highValue) {
        ctx.i0 = highValue;
        return super.add$p(ctx, lowValue);
    }

    @Override
    public nArrayᐸInt128ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (nArrayᐸInt128ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Int128 n = getElement$p(ctx, index);
        return n.toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeInt128();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity128bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $get128bitElement(ctx, index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set128bitElement(index, value, ctx.i0);
    }

    @Override
    protected int $cap2len(int cap) {
        return $cap2len128bits(cap);
    }
}
