package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.numbers.UInt16;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of UInt16, stored in an array of Java longs, four UInt16 per long.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class nArrayᐸUInt16ᐳ
        extends nLongBasedArray<nArrayᐸUInt16ᐳ> {

    public nArrayᐸUInt16ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static nArrayᐸUInt16ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        nArrayᐸUInt16ᐳ array = new nArrayᐸUInt16ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static nArrayᐸUInt16ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸUInt16ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸUInt16ᐳ $new$3$p(Ctx ctx, TypeConstant type, nArrayᐸUInt16ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public UInt16 getElement$p(Ctx ctx, long index) {
        return UInt16.$box(getElement$pi(ctx, index));
    }

    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((UInt16) value).$value);
    }

    @Override
    public nArrayᐸUInt16ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((UInt16) element).$value);
    }

    public nArrayᐸUInt16ᐳ add$p(Ctx ctx, int value) {
        return super.add$p(ctx, value);
    }

    @Override
    public nArrayᐸUInt16ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (nArrayᐸUInt16ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        UInt16 c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeUInt16();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity16bit();
    }

    protected long $getElement(Ctx ctx, long index) {
        return $get16bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $set16bitElement(index, value);
    }

    @Override
    protected int $cap2len(int cap) {
        return $cap2len16bits(cap);
    }
}
