package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Exception;
import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.text.Char;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

/**
 * Array of Unicode characters, stored in an array of Java longs, either 8x per long (0x00..0xFF) or
 * 3x per long (0x00..0x10FFFF).
 *
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 *
 * Size - 48 bits
 * Mutability - 2 bits
 * Format (8 vs 21) - 1 bit
 *
 * Capacity - 48 bits (pre storage)
 * Hash - 64 bits (only if mutability==Constant, requires storage != null)
 */
public class nArrayᐸCharᐳ
        extends nLongBasedArray<nArrayᐸCharᐳ> {

    public nArrayᐸCharᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    public boolean $utf21;      // REVIEW: this could just use a bit in (steal a bit from) $sizeEtc

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static nArrayᐸCharᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        nArrayᐸCharᐳ array = new nArrayᐸCharᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static nArrayᐸCharᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸCharᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸCharᐳ $new$3$p(Ctx ctx, TypeConstant type, nArrayᐸCharᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Char getElement$p(Ctx ctx, long index) {
        return Char.$box(getElement$pi(ctx, index));
    }

    /**
     * Optimized "primitive intrinsic" form of the getElement() method. The JIT will use this method
     * in lieu of getElement$p() whenever it has enough information to do so.
     */
    public int getElement$pi(Ctx ctx, long index) {
        return (int) $getElement$pi(ctx, index);
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, ((Char) value).$value);
    }

    @Override
    public nArrayᐸCharᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, ((Char) element).$value);
    }

    public nArrayᐸCharᐳ add$p(Ctx ctx, int ch) {
        return super.add$p(ctx, (long) ch);
    }

    @Override
    public nArrayᐸCharᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (nArrayᐸCharᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected java.lang.String $elementToString(Ctx ctx, long index) {
        Char c = getElement$p(ctx, index);
        return c.toString(ctx).toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeChar();
    }

    @Override
    protected long $storageCapacity() {
        return $utf21 ? $storageCapacity21bit() : $storageCapacity8bit();
    }

    protected long $getElement(Ctx ctx, long index) {
        return $utf21 ? $get21bitUnsignedElement(index)
                : $get8bitUnsignedElement(index);
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        if (!$utf21) {
            if (value < 0x100) {
                $set8bitElement(index, value);
                return;
            }
            // TODO convert from 8-bit format to 21-bit format
        }
        // 21-bit version of: $storage[(int) index] = value;
        throw Exception.$unsupported(ctx, null); // TODO
    }

    @Override
    protected int $cap2len(int cap) {
        return $utf21 ? $cap2len21bits(cap) : $cap2len8bits(cap);
    }
}
