package org.xtclang.ecstasy.collections;

import org.xtclang.ecstasy.Iterable;
import org.xtclang.ecstasy.nObj;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;
import org.xtclang.ecstasy.numbers.Float64;
import org.xvm.asm.ConstantPool;
import org.xvm.asm.constants.TypeConstant;
import org.xvm.javajit.Ctx;

/**
 * Array of Float64, stored in an array of Java longs.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public class nArrayᐸFloat64ᐳ
        extends nLongBasedArray<nArrayᐸFloat64ᐳ> {

    public nArrayᐸFloat64ᐳ(Ctx ctx, TypeConstant type) {
        super(ctx, type);
    }

    // ----- Array API -----------------------------------------------------------------------------

    /**
     * Array Constructor: construct(Int capacity = 0)
     */
    public static nArrayᐸFloat64ᐳ $new$p(Ctx ctx, TypeConstant type, long capacity, boolean _capacity) {
        assert !type.isImmutable();

        ctx.alloc(64); // REVIEW how big?
        nArrayᐸFloat64ᐳ array = new nArrayᐸFloat64ᐳ(ctx, type);
        array.$mut($MUTABLE);
        array.$capCfg(ctx, capacity);
        return array;
    }

    public static nArrayᐸFloat64ᐳ $new$1$p(Ctx ctx, TypeConstant type, long size, nObj supply) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸFloat64ᐳ $new$2$p(Ctx ctx, TypeConstant type, Mutability mutability, Iterable elements) {
        // TODO
        throw new UnsupportedOperationException();
    }

    public static nArrayᐸFloat64ᐳ $new$3$p(Ctx ctx, TypeConstant type, nArrayᐸFloat64ᐳ that) {
        // TODO
        throw new UnsupportedOperationException();
    }

    @Override public Float64 getElement$p(Ctx ctx, long index) {
        return Float64.$box(getElement$pi(ctx, index));
    }

    public double getElement$pi(Ctx ctx, long index) {
        return Double.longBitsToDouble($getElement$pi(ctx, index));
    }

    @Override public void setElement$p(Ctx ctx, long index, nObj value) {
        setElement$pi(ctx, index, Double.doubleToRawLongBits(((Float64) value).$value));
    }

    public void setElement$pi(Ctx ctx, long index, double value) {
        setElement$pi(ctx, index, Double.doubleToRawLongBits(value));
    }

    @Override
    public nArrayᐸFloat64ᐳ add(Ctx ctx, nObj element) {
        return add$p(ctx, Double.doubleToRawLongBits(((Float64) element).$value));
    }

    public nArrayᐸFloat64ᐳ add$p(Ctx ctx, double value) {
        return super.add$p(ctx, Double.doubleToRawLongBits(value));
    }

    @Override
    public nArrayᐸFloat64ᐳ slice(Ctx ctx, nRangeᐸInt64ᐳ range) {
        return (nArrayᐸFloat64ᐳ) super.slice(ctx, range);
    }

    // ----- Array internals -----------------------------------------------------------------------

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    @Override
    protected String $elementToString(Ctx ctx, long index) {
        Float64 n = getElement$p(ctx, index);
        return n.toString(ctx).toString();
    }

    @Override
    protected TypeConstant $elementType(ConstantPool pool) {
        return pool.typeFloat64();
    }

    @Override
    protected long $storageCapacity() {
        return $storageCapacity64bit();
    }

    @Override
    protected long $getElement(Ctx ctx, long index) {
        return $storage[(int) index];
    }

    @Override
    protected void $setElement(Ctx ctx, long index, long value) {
        $storage[(int) index] = value;
    }

    @Override
    protected int $cap2len(int cap) {
        return cap;
    }
}
