package org.xtclang.ecstasy.collections;

import java.util.Arrays;

import org.xtclang.ecstasy.Exception;
import org.xtclang.ecstasy.nException;
import org.xtclang.ecstasy.nRangeᐸInt64ᐳ;

import org.xtclang.ecstasy.text.String;

import org.xvm.asm.ConstantPool;

import org.xvm.asm.constants.TypeConstant;

import org.xvm.javajit.Ctx;

import static java.lang.Math.max;
import static java.lang.System.arraycopy;

/**
 * An {@link Array} implementation where the elements are mapped into an array of Java {@code long}
 * values.
 * <p>
 * Array elements are mapped to long values in the {@link #$storage} array depending on their
 * size, for example, eight 8-bit values can be packed into each {@code long} value in the
 * {@link #$storage} array, wheras storing a 128-bit value will require two {@code long} values.
 * <p>
 * Object header
 * xObj - 64 bits of flags
 * ---
 * Delegate - ref
 * Storage - ref
 */
public abstract class nLongBasedArray<ArrayType extends nLongBasedArray<ArrayType>>
        extends Array {

    public nLongBasedArray(Ctx ctx, TypeConstant type) {
        super(ctx);
    }

    // REVIEW: to save space, we could combine the $storage and $delegate fields into a single field, e.g.
    //
    //  @Override protected Array$Char $delegate() {
    //      if ($storage instanceof Array$Char delegate) {
    //          return delegate;
    //      }
    //      return null;
    //  }
    public ArrayType $delegate;

    public long[] $storage;

    // ----- xObj API ------------------------------------------------------------------------------

    @Override public TypeConstant $xvmType(Ctx ctx) {
        ConstantPool pool = $owner().typeSystem.pool();
        TypeConstant type = pool.ensureArrayType($elementType(pool));
        return $isImmut() ? type.freeze() : type;
    }

    protected abstract TypeConstant $elementType(ConstantPool pool);

    // ToDo GG/JK remove this when it can be generated by the JIT
    @Override
    public String toString(Ctx ctx) {
        if ($delegate != null) {
            return $delegate.toString(ctx);
        }
        if ($storage == null) {
            return org.xtclang.ecstasy.text.String.of(ctx, "[]");
        }
        StringBuilder buf  = new StringBuilder("[");
        long          size = size$get$p(ctx);
        for (long i = 0; i < size; i++) {
            if (i > 0) {
                buf.append(", ");
            }
            buf.append($elementToString(ctx, i));
        }
        buf.append(']');
        return String.of(ctx, buf.toString());
    }

    // ToDo GG/JK remove this (and sub classes) when toString() can be generated by the JIT
    protected abstract java.lang.String $elementToString(Ctx ctx, long index);

    // ----- Array API -----------------------------------------------------------------------------

    @Override public long capacity$get$p(Ctx ctx) {
        return $delegate == null
                ? $storage == null ? $capCfg(ctx) : $storageCapacity()
                : $delegate.capacity$get$p(ctx);
    }

    /**
     * @return the current storage capacity for this array.
     */
    protected abstract long $storageCapacity();

    /**
     * @return the current storage capacity when storing 1-bit values
     */
    protected long $storageCapacity1bit() {
        return $storage.length * 64L;
    }

    /**
     * @return the current storage capacity when storing 4-bit values
     */
    protected long $storageCapacity4bit() {
        return $storage.length * 16L;
    }

    /**
     * @return the current storage capacity when storing 8-bit values
     */
    protected long $storageCapacity8bit() {
        return $storage.length * 8L;
    }

    /**
     * @return the current storage capacity when storing 16-bit values
     */
    protected long $storageCapacity16bit() {
        return $storage.length * 4L;
    }

    /**
     * @return the current storage capacity when storing 21-bit values
     */
    protected long $storageCapacity21bit() {
        return $storage.length * 3L;
    }

    /**
     * @return the current storage capacity when storing 32-bit values
     */
    protected long $storageCapacity32bit() {
        return $storage.length * 2L;
    }

    /**
     * @return the current storage capacity when storing 64-bit values
     */
    protected long $storageCapacity64bit() {
        return $storage.length;
    }

    /**
     * @return the current storage capacity when storing 128-bit values
     */
    protected long $storageCapacity128bit() {
        return $storage.length / 2L;
    }

    @Override public long size$get$p(Ctx ctx) {
        // for virtual calls coded against xArray$Int64, this avoids the virtual field accessor
        return $delegate == null ? ($sizeEtc & $SIZE_MASK) : $delegate.size$get$p(ctx);
    }

    /**
     * Add a value to the array.
     *
     * @param ctx    the current context
     * @param value  the value to add
     *
     * @return this array
     */
    @SuppressWarnings("unchecked")
    public ArrayType add$p(Ctx ctx, long value) {
        if ($delegate != null) {
            $delegate.add$p(ctx, value);
            return (ArrayType) this;
        }

        if (($sizeEtc >>> $MUT_SHIFT) != $MUTABLE) {
            // TODO: persistent
            throw $ro(ctx);
        }

        int size = $sizeEtc & $SIZE_MASK;
        if (($storage == null || $storage.length == $cap2len(size)) && !$growInPlace(ctx, size+1)) {
            // we just transitioned to the "huge model"
            $delegate.add$p(ctx, value);
            return (ArrayType) this;
        }

        try {
            $setElement(ctx, size, value);
            $size(size + 1);
            return (ArrayType) this;
        } catch (ArrayIndexOutOfBoundsException e) {
            throw $oob(ctx, size);
        }
    }

    /**
     * Return the element from the array at the specified index.
     * <p>
     * For subclasses that are storing values that are less than 64-bits, the return value is
     * always converted to a {@link long} value.
     *
     * @param ctx    the current context
     * @param index  the index of the element to retrieve
     *
     * @return the value of the array element at the specified index
     *
     * @throws nException wrapping an {@link org.xtclang.ecstasy.OutOfBounds} if the index is out
     *         of range
     */
    public long $getElement$pi(Ctx ctx, long index) {
        if ($delegate != null) {
            return $delegate.$getElement$pi(ctx, index);
        }

        if (index >= ($sizeEtc & $SIZE_MASK)) {
            throw $oob(ctx, index);
        }

        try {
            return $getElement(ctx, index);
        } catch (ArrayIndexOutOfBoundsException e) {
            throw $oob(ctx, index);
        }
    }

    @Override public ArrayType slice$p(Ctx ctx, long n1, long n2) {
        // slice must be in-range
        // TODO check lower bound as well
        long upper = nRangeᐸInt64ᐳ.$effectiveUpperBound(ctx, n1, n2);
        if (size$get$p(ctx) > upper) {
            throw $oob(ctx, upper);
        }

        // optimized empty slice
        if (nRangeᐸInt64ᐳ.$empty(ctx, n1, n2)) {
            // return TODO empty Array$Object
        }

        // return TODO Array$Object$Slice
        throw $oob(ctx, upper);
    }

    /**
     * Return the element from the array at the specified index.
     * <p>
     * Subclasses should override this method to correctly unpack the required element from the
     * underlying {@link #$storage} array.
     * <p>
     * This method is not required to check for a {@link #$delegate} or perform a range chec as
     * this will have been done by the caller.
     * <p>
     * For subclasses that are storing values that are less than 64-bits, the return value should
     * always be converted to a {@link long} value.
     *
     * @param ctx    the current context
     * @param index  the index of the element to retrieve
     *
     * @return the value of the array element at the specified index
     *
     * @throws ArrayIndexOutOfBoundsException if the specified index is out of range
     */
    protected abstract long $getElement(Ctx ctx, long index);

    /**
     * Return the 1-bit value from the specified array index.
     * <p>
     * This method assumes that sixty-four 1-bit elements have been packed into each long value in
     * the long array.
     *
     * @param index  the index of the 1-bit value to obtain
     *
     * @return  the 1-bit value (0 or 1) at the specified array index
     */
    protected long $get1bitElement(long index) {
        return ($storage[(int) (index >>> 6)] >>> (63 - ((int) (index & 0x3F)))) & 1L;
    }

    /**
     * Return the 4-bit value from the specified array index.
     * <p>
     * This method will NOT sign-extend the 4-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that sixteen 4-bit elements have been packed into each long value in
     * the long array.
     *
     * @param index  the index of the 4-bit value to obtain
     *
     * @return  the 4-bit value at the specified array index
     */
    protected long $get4bitUnsignedElement(long index) {
        return ($storage[(int) (index >>> 4)] >>> ((15 - ((int) (index & 0xF))) << 2)) & 0xFL;
    }

    /**
     * Return the 8-bit value from the specified array index.
     * <p>
     * This method will NOT sign-extend the 8-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 8-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 8-bit value to obtain
     *
     * @return  the 8-bit value at the specified array index
     */
    protected long $get8bitUnsignedElement(long index) {
        return ($storage[(int) (index >>> 3)] >>> ((7 - ((int) (index & 0x7))) << 3) & 0xFFL);
    }

    /**
     * Return the 8-bit value from the specified array index.
     * <p>
     * This method will sign-extend the 8-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 8-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 8-bit value to obtain
     *
     * @return  the 8-bit value at the specified array index
     */
    protected long $get8bitSignedElement(long index) {
        long n = $get8bitUnsignedElement(index);
        if ((n & 0x80L) > 0) {
            // sign bit set so sign extend to a 64-bit long
            n |= 0xFFFFFFFFFFFFFF00L;
        }
        return n;
    }

    /**
     * Return the 16-bit value from the specified array index.
     * <p>
     * This method will NOT sign-extend the 16-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 16-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 16-bit value to obtain
     *
     * @return  the 16-bit value at the specified array index
     */
    protected long $get16bitUnsignedElement(long index) {
        return ($storage[(int) (index >>> 2)] >>> ((3 - ((int) (index & 0x3))) << 4) & 0xFFFFL);
    }

    /**
     * Return the 16-bit value from the specified array index.
     * <p>
     * This method will sign-extend the 16-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 16-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 16-bit value to obtain
     *
     * @return  the 16-bit value at the specified array index
     */
    protected long $get16bitSignedElement(long index) {
        long n = $get16bitUnsignedElement(index);
        if ((n & 0x8000L) > 0) {
            // sign bit set so sign extend to a 64-bit long
            n |= 0xFFFFFFFFFFFF0000L;
        }
        return n;
    }

    /**
     * Return the 21-bit value from the specified array index.
     * <p>
     * This method will NOT sign-extend the 8-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that three 21-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 21-bit value to obtain
     *
     * @return  the 21-bit value at the specified array index
     */
    protected long $get21bitUnsignedElement(long index) {
        // frdc algorithm: https://arxiv.org/abs/1902.01961
        return ($storage[(int) ((index *= 0x55555556L) >>> 32)] >>>
               (21 * (2 - ((int) (((index & 0xFFFFFFFFL) * 3) >>> 32)))));
    }

    /**
     * Return the 32-bit value from the specified array index.
     * <p>
     * This method will NOT sign-extend the 32-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 32-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 32-bit value to obtain
     *
     * @return  the 32-bit value at the specified array index
     */
    protected long $get32bitUnsignedElement(long index) {
        return ($storage[(int) (index >>> 1)] >>> ((1 - ((int) (index & 0x1))) << 5) & 0xFFFFFFFFL);
    }

    /**
     * Return the 32-bit value from the specified array index.
     * <p>
     * This method will sign-extend the 32-bit value to a full 64-bit long value.
     * <p>
     * This method assumes that eight 32-bit elements have been packed into each long value in the
     * long array.
     *
     * @param index  the index of the 32-bit value to obtain
     *
     * @return  the 32-bit value at the specified array index
     */
    protected long $get32bitSignedElement(long index) {
        long n = $get32bitUnsignedElement(index);
        if ((n & 0x80000000L) > 0) {
            // sign bit set so sign extend to a long
            n |= 0xFFFFFFFF00000000L;
        }
        return n;
    }

    /**
     * Return the 128-bit value from the specified array index.
     * <p>
     * The low 64-bits of the 128-bit value will be returned, and the high 64-bits will be set into
     * the {@link Ctx#i0} field.
     * <p>
     * This method assumes that the 128-bit values have been stored using two long array elements
     * for each 128-bit value.
     *
     * @param index  the index of the 128-bit value to obtain
     *
     * @return  the low 64-bits of the 128-bit value at the specified array index
     */
    protected long $get128bitElement(Ctx ctx, long index) {
        int idx = (int) index * 2;
        ctx.i0 = $storage[idx + 1];
        return $storage[idx];
    }

    public void setElement$pi(Ctx ctx, long index, int value) {
        setElement$pi(ctx, index, (long) value);
    }

    public void setElement$pi(Ctx ctx, long index, long value) {
        if ($delegate != null) {
            $delegate.setElement$pi(ctx, index, value);
            return;
        }

        int size = $sizeEtc & $SIZE_MASK;
        if (index >= size) {
            if (index == size && ($sizeEtc >>> $MUT_SHIFT) == $MUTABLE) {
                // index==size up to 2^30 is an append operation within this array's storage;
                // anything over that requires a transition to the "huge" model
                if (($storage == null || index >= $storage.length) && !$growInPlace(ctx, index+1)) {
                    // we just transitioned to the "huge model"
                    $delegate.setElement$pi(ctx, index, value);
                    return;
                }
            } else {
                throw $oob(ctx, index);
            }
            $size(size + 1);
        }

        try {
            $setElement(ctx, index, value);
        } catch (ArrayIndexOutOfBoundsException e) {
            throw $oob(ctx, index);
        }
    }

    protected abstract void $setElement(Ctx ctx, long index, long value);

    /**
     * Store a 1-bit element value into the array.
     * <p>
     * This method will pack sixty-four 1-bit elements into each long value in the long array.
     *
     * @param index  the index to store the element at
     * @param value  the value to store (0 or 1)
     */
    protected void $set1bitElement(long index, long value) {
        int idx = (int) index;
        int i = idx >>> 6;
        int s = 63 - (idx & 0x3F);
        $storage[i] = $storage[i] & ~(1L << s) | ((value & 1L) << s);
    }

    /**
     * Store a 4-bit element value into the array.
     * <p>
     * This method will pack sixteen 4-bit elements into each long value in the long array.
     *
     * @param index  the index to store the element at
     * @param value  the value to store (0-15)
     */
    protected void $set4bitElement(long index, long value) {
        int idx = (int) index;
        int i = idx >>> 4;
        int s = (15 - (idx & 0xF)) << 2;
        $storage[i] = $storage[i] & ~(0xFL << s) | ((value & 0xFL) << s);
    }

    /**
     * Store an 8-bit element value into the array.
     * <p>
     * This method will pack eight 8-bit elements into each long value in the long array.
     *
     * @param index  the index to store the element at
     * @param value  the value to store
     */
    protected void $set8bitElement(long index, long value) {
        int idx = (int) index;
        int i = idx >>> 3;
        int s = (7 - (idx & 0x7)) << 3;
        $storage[i] = $storage[i] & ~(0xFFL << s) | ((value & 0xFFL) << s);
    }

    /**
     * Store a 16-bit element value into the array.
     * <p>
     * This method will pack two 16-bit elements into each long value in the long array.
     *
     * @param index  the index to store the element at
     * @param value  the value to store
     */
    protected void $set16bitElement(long index, long value) {
        int idx = (int) index;
        int i = idx >>> 2;
        int s = (3 - (idx & 0x3)) << 4;
        $storage[i] = $storage[i] & ~(0xFFFFL << s) | ((value & 0xFFFFL) << s);
    }

    /**
     * Store a 32-bit element value into the array.
     * <p>
     * This method will pack two 32-bit elements into each long value in the long array.
     *
     * @param index  the index to store the element at
     * @param value  the value to store
     */
    protected void $set32bitElement(long index, long value) {
        int idx = (int) index;
        int i = idx >>> 1;
        int s = (1 - (idx & 0x1)) << 5;
        $storage[i] = $storage[i] & ~(0xFFFFFFFFL << s) | ((value & 0xFFFFFFFFL) << s);
    }

    /**
     * Store a 128-bit element value into the array.
     * <p>
     * This method will store 128-bit elements into the array using two long array elements for
     * each 128-bit value
     *
     * @param index     the index to store the element at
     * @param lowBits   the lower 64 bits of the value to store
     * @param highBits  the upper 64 bits of the value to store
     */
    protected void $set128bitElement(long index, long lowBits, long highBits) {
        int idx = (int) index * 2;
        $storage[idx] = lowBits;
        $storage[idx + 1] = highBits;
    }

    // ----- Array internals -----------------------------------------------------------------------

    @Override protected ArrayType $delegate() {
        return $delegate;
    }

    @Override protected Object $storage() {
        return $storage;
    }

    /**
     * Ensure the specified capacity.
     *
     * @param ctx     the runtime context
     * @param minCap  the minimum capacity requirement
     *
     * @return true iff this array has able to grow "in place" to support the capacity requirement;
     *         false indicates that the array transitioned to the "huge" model
     */
    @Override protected boolean $growInPlace(Ctx ctx, long minCap) {
        // the caller is responsible for passing valid args; this will not be checked at runtime
        minCap = Long.max(minCap, $cap2len((int) minCap));
        assert minCap > 0 && minCap <= $SIZE_MASK+1 && ($storage == null || minCap > $storage.length);

        if ($storage == null) {
            long cap = max($capCfg(ctx), minCap);
            if (cap > $SIZE_MASK) {
                $growHuge(ctx, cap);
                return false;
            } else {
                $storage = new long[$cap2len((int) cap)];
                return true;
            }
        }

        // calculate power of 2 growth
        long cap = max($MIN_CAP, Long.highestOneBit(-1 + minCap + minCap)); // TODO current cap, not requested cap
        if (cap > $SIZE_MASK) {
            $growHuge(ctx, cap);
            return false;
        }

        $storage = Arrays.copyOf($storage, $cap2len((int) cap));
        return true;
    }

    /**
     * Get the long array length required to store the specified capacity.
     *
     * @param cap  the desired storage capacity
     *
     * @return the number of longs required
     */
    protected abstract int $cap2len(int cap);

    /**
     * Return the {@link #$cap2len(int)} value for 1-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 1-bit values
     */
    protected int $cap2len1bit(int cap) {
        return (cap + 63) / 64;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 4-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 4-bit values
     */
    protected int $cap2len4bits(int cap) {
        return (cap + 15) / 16;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 8-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 8-bit values
     */
    protected int $cap2len8bits(int cap) {
        return (cap + 7) / 8;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 16-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 16-bit values
     */
    protected int $cap2len16bits(int cap) {
        return (cap + 3) / 4;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 21-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 21-bit values
     */
    protected int $cap2len21bits(int cap) {
        return (cap + 2) / 3;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 32-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 32-bit values
     */
    protected int $cap2len32bits(int cap) {
        return (cap + 1) / 2;
    }

    /**
     * Return the {@link #$cap2len(int)} value for 128-bit elements.
     *
     * @param cap  the array capacity
     *
     * @return  the storage length required to hold the specified array capacity of 128-bit values
     */
    protected int $cap2len128bits(int cap) {
        return cap * 2;
    }

    @Override protected void $growHuge(Ctx ctx, long cap) {
        // TODO new Array$Object$Huge
        throw $oob(ctx, cap);
    }

    @Override protected void $shrinkToSize(Ctx ctx) {
        int size = $sizeEtc & $MUT_MASK;
        int min  = size;
        if ($storage != null && $storage.length > min) {
             long[] newArray = new long[min];
             arraycopy($storage, 0, newArray, 0, min);
             $storage = newArray;
        }
    }

    @Override public void $insert(Ctx ctx, long index, long count) {
        if ($delegate != null) {
            $delegate.$insert(ctx, index, count);
            return;
        }

        // the caller is responsible for passing valid args; this will not be checked at runtime
        assert index >= 0 && index <= size$get$p(ctx) && count > 0;

        // only mutable arrays can insert
        if (($sizeEtc >>> $MUT_SHIFT) != $MUTABLE) {
            throw $ro(ctx);
        }

        // need to compare size and capacity to see if we can insert without running out of room
        int  size = $sizeEtc & $SIZE_MASK;
        long req  = size + count;
        if (($storage == null || req > $storage.length) && !$growInPlace(ctx, req)) {
            $delegate.$insert(ctx, index, count);
            return;
        }

        if (index < size) {
            // move elements [index..size)
            arraycopy($storage, (int) index, $storage, (int) (index+count), size-((int) index));
            throw Exception.$unsupported(ctx, null); // TODO
        }
    }

    @Override public void $delete(Ctx ctx, long index, long count) {
        if ($delegate != null) {
            $delegate.$delete(ctx, index, count);
            return;
        }

        // only mutable arrays can delete
        if (($sizeEtc >>> $MUT_SHIFT) != $MUTABLE) {
            throw $ro(ctx);
        }

        throw Exception.$unsupported(ctx, null); // TODO
    }
}
