name: Dependency Submission

# Run on pushes to main branches and pull requests  
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

env:
  gradle_version: 8.14.2
  # Exclude manual tests to avoid plugin configuration issues in dependency analysis
  ORG_GRADLE_PROJECT_includeBuildManualTests: false
  ORG_GRADLE_PROJECT_includeBuildAttachManualTests: false
  
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    # if: false  # DISABLED: Circular dependency issues with composite build
    permissions:
      contents: read
      actions: read
      security-events: write
      id-token: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get Java version from properties
      id: get-java-version
      uses: ./.github/actions/get-java-version
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.get-java-version.outputs.java_version }}
        distribution: temurin
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: ${{ env.gradle_version }}
        cache-disabled: false
        
    # Clean first (standalone as per CLAUDE.md requirements)
    - name: Clean build
      run: ./gradlew clean
      
    # Generate dependency graph by running actual build tasks that resolve all dependencies  
    - name: Generate dependency graph from full build
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate
        arguments: :xdk:installDist
