name: Dependency Submission

# Run on pushes to main branches and pull requests  
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read
  
jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      # Write permission needed for dependency submission
      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get Java version from properties
      id: get-java-version
      uses: ./.github/actions/get-java-version
      
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ steps.get-java-version.outputs.java_version }}
        distribution: temurin
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: 8.14.2
        cache-disabled: false
        
    # Generate and submit dependency graph for root project
    - name: Generate dependency graph for root
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate-and-submit
        
    # Generate dependency graph for each subproject
    - name: Generate dependency graph for XDK
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate-and-submit
        build-root-directory: ./xdk
        
    - name: Generate dependency graph for JavaTools
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate-and-submit 
        build-root-directory: ./javatools
        
    - name: Generate dependency graph for Plugin
      uses: gradle/actions/dependency-submission@v4
      with:
        dependency-graph: generate-and-submit 
        build-root-directory: ./plugin