# Send Discord notifications for GitHub events
#
# Posts notifications to the #github Discord channel when:
# - Pull requests are opened, reopened, or closed
# - Workflow runs complete (success/failure)
#
name: Discord Notifications

on:
    pull_request:
        types: [opened, reopened, closed, ready_for_review]
    workflow_run:
        workflows: ["Verify Commit"]
        types: [completed]

jobs:
    notify-pr:
        name: Notify Discord - Pull Request
        runs-on: ubuntu-latest
        if: false  # Temporarily disabled
        # if: github.event_name == 'pull_request'

        steps:
            - name: Send Discord notification
              run: |
                  PR_NUMBER="${{ github.event.pull_request.number }}"
                  PR_TITLE="${{ github.event.pull_request.title }}"
                  PR_URL="${{ github.event.pull_request.html_url }}"
                  PR_AUTHOR="${{ github.event.pull_request.user.login }}"
                  PR_ACTION="${{ github.event.action }}"
                  PR_STATE="${{ github.event.pull_request.state }}"
                  PR_DRAFT="${{ github.event.pull_request.draft }}"

                  # Determine emoji and action text
                  case "$PR_ACTION" in
                      opened)
                          if [ "$PR_DRAFT" = "true" ]; then
                              EMOJI="📝"
                              ACTION_TEXT="opened draft PR"
                          else
                              EMOJI="🔔"
                              ACTION_TEXT="opened PR"
                          fi
                          COLOR=5793266  # Blue
                          ;;
                      reopened)
                          EMOJI="🔄"
                          ACTION_TEXT="reopened PR"
                          COLOR=16776960  # Yellow
                          ;;
                      ready_for_review)
                          EMOJI="✅"
                          ACTION_TEXT="marked PR ready for review"
                          COLOR=3066993  # Green
                          ;;
                      closed)
                          if [ "${{ github.event.pull_request.merged }}" = "true" ]; then
                              EMOJI="🎉"
                              ACTION_TEXT="merged PR"
                              COLOR=6684876  # Purple
                          else
                              EMOJI="❌"
                              ACTION_TEXT="closed PR"
                              COLOR=15158332  # Red
                          fi
                          ;;
                      *)
                          EMOJI="📋"
                          ACTION_TEXT="updated PR"
                          COLOR=9807270  # Gray
                          ;;
                  esac

                  # Build JSON payload for Discord webhook
                  PAYLOAD=$(cat <<EOF
                  {
                    "embeds": [{
                      "title": "$EMOJI PR #$PR_NUMBER: $PR_TITLE",
                      "url": "$PR_URL",
                      "description": "**$PR_AUTHOR** $ACTION_TEXT",
                      "color": $COLOR,
                      "footer": {
                        "text": "${{ github.repository }}"
                      }
                    }]
                  }
                  EOF
                  )

                  # Send to Discord
                  curl -H "Content-Type: application/json" \
                       -d "$PAYLOAD" \
                       "${{ secrets.DISCORD_GITHUB_WEBHOOK }}"

    notify-workflow:
        name: Notify Discord - Workflow
        runs-on: ubuntu-latest
        if: false  # Temporarily disabled
        # if: github.event_name == 'workflow_run'

        steps:
            - name: Send Discord notification
              run: |
                  WORKFLOW_NAME="${{ github.event.workflow_run.name }}"
                  WORKFLOW_STATUS="${{ github.event.workflow_run.conclusion }}"
                  WORKFLOW_URL="${{ github.event.workflow_run.html_url }}"
                  WORKFLOW_BRANCH="${{ github.event.workflow_run.head_branch }}"
                  WORKFLOW_COMMIT="${{ github.event.workflow_run.head_sha }}"
                  WORKFLOW_AUTHOR="${{ github.event.workflow_run.head_commit.author.name }}"

                  # Only notify on failure for now (success notifications can be too noisy)
                  if [ "$WORKFLOW_STATUS" != "failure" ]; then
                      echo "Workflow succeeded - skipping notification to reduce noise"
                      exit 0
                  fi

                  # Determine emoji and color based on status
                  case "$WORKFLOW_STATUS" in
                      success)
                          EMOJI="✅"
                          COLOR=3066993  # Green
                          ;;
                      failure)
                          EMOJI="❌"
                          COLOR=15158332  # Red
                          ;;
                      cancelled)
                          EMOJI="⚠️"
                          COLOR=16776960  # Yellow
                          ;;
                      *)
                          EMOJI="❓"
                          COLOR=9807270  # Gray
                          ;;
                  esac

                  # Build JSON payload for Discord webhook
                  PAYLOAD=$(cat <<EOF
                  {
                    "embeds": [{
                      "title": "$EMOJI Workflow: $WORKFLOW_NAME",
                      "url": "$WORKFLOW_URL",
                      "description": "**Status:** $WORKFLOW_STATUS\n**Branch:** \`$WORKFLOW_BRANCH\`\n**Author:** $WORKFLOW_AUTHOR\n**Commit:** \`${WORKFLOW_COMMIT:0:7}\`",
                      "color": $COLOR,
                      "footer": {
                        "text": "${{ github.repository }}"
                      }
                    }]
                  }
                  EOF
                  )

                  # Send to Discord
                  curl -H "Content-Type: application/json" \
                       -d "$PAYLOAD" \
                       "${{ secrets.DISCORD_GITHUB_WEBHOOK }}"
