#
# Action when a push event happens in our github repository.
#
# (It may be overkill, and we may want to switch to 'on: pull_request'
#  when we have tested this out enough. It is the branch developer's
#  responsibility to manually nsure the branch tests clean during
#  development and before submission as pull request)
#
name: Build and verify XTC project on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3      
      - uses: actions/setup-java@v3
        with: 
          distribution: 'adopt'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2
      - name: Execute Gradle build
        run: ./gradlew build --info
