#
# GitHub runner workflow for building, verifying and testing the XVM repo.
#

name: XVM Install and Check

# Check if "pull-request" makes it possible to add a branch protection status check requirement on master.
on: push

env:
  ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true

  ORG_GRADLE_PROJECT_includeBuildManualTests: true
  ORG_GRADLE_PROJECT_includeBuildAttachManualTests: true

  ORG_XTCLANG_JAVATOOLS_SANITY_CHECK_JAR: true
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: false

  gradle_options: --stacktrace --warning-mode all --console verbose

#concurrency:
  #group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  #cancel-in-progress: true

jobs:
  setup:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    # Declare outputs for one of the steps in the job.
    outputs:
      version: ${{ steps.properties.outputs.version }}
      major: ${{ steps.properties.outputs.major }}
      minor: ${{ steps.properties.outputs.minor }}
      patch: ${{ steps.properties.outputs.patch }}
      snapshot: ${{ steps.properties.outputs.snapshot }}
      tag_last_release: ${{ steps.properties.outputs.tag_last_release }}
      tag_new_release: ${{ steps.properties.outputs.tag_new_release }}
      tag_next_release: ${{ steps.properties.outputs.tag_next_release }}
      #changelog: ${{ steps.properties.outputs.changelog }}

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-tags: true # fetch tags even if fetch-depth == 0
          show-progress: true

      - name: Export Properties
        id: properties
        #shell: bash
        run: |
          # Parse XDK version from VERSION file in repo root
          xdk_version="$(cat ./VERSION)"
          echo "xdk_version from disk: $xdk_version"
          
          # Check if the version is a snapshot (will lead to publication for any push to master)
          if [[ "$xdk_version" == *SNAPSHOT ]]; then
            echo "snapshot identified"
            echo "snapshot=true" >> $GITHUB_OUTPUT
          fi

          # Strip version string suffix (i.e. remove -SNAPSHOT, -M1, etc)          
          xdk_version="${xdk_version%-SNAPSHOT}"                   
          
          # Parse the major, minor and patch version
          _re='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
          major=$(echo "$xdk_version" | sed -e "s#$_re#\1#")
          minor=$(echo "$xdk_version" | sed -e "s#$_re#\2#")
          patch=$(echo "$xdk_version" | sed -e "s#$_re#\3#")

          # Set up tags, where applicable
          tag_last_release=$(git describe --tags --abbrev=0 --always)
          tag_this_release="v$xdk_version"
          tag_next_release="v$major.$minor.$((patch + 1))-SNAPSHOT"
          echo "tag:"
          echo "  last=$tag_last_release"
          echo "  this=$tag_this_release"
          echo "  next=$tag_next_release"
          
          # Write resolved variables to output
          echo "version=$xdk_version" >> $GITHUB_OUTPUT
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT
          echo "tag_last_release=$tag_last_release" >> $GITHUB_OUTPUT
          echo "tag_this_release=$tag_this_release" >> $GITHUB_OUTPUT
          echo "tag_next_release=$tag_next_release" >> $GITHUB_OUTPUT

          # TODO: changelog          

  build:
    name: Build 'installDist'
    needs: setup
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-tags: true # fetch tags even if fetch-depth == 0
          show-progress: true

      - name: Setup Java and system-wide caching
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '21'
          cache: 'gradle'

      - name: Setup Gradle and Gradle Cache
        uses: gradle/actions/setup-gradle@v3
        with:
          #gradle-home-cache-cleanup: true
          cache-read-only: false

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v2.1.2

      - name: Check XDK version and tags
        run: |
          echo "*** XDK_VERSION: ${{ needs.setup.outputs.version }}"
          echo "*** XDK_SNAPSHOT: ${{ needs.setup.outputs.snapshot }}"  
          echo "*** XDK_VERSION_MAJOR: ${{ needs.setup.outputs.major }}"
          echo "*** XDK_VERSION_MINOR: ${{ needs.setup.outputs.minor }}"
          echo "*** XDK_VERSION_PATCH: ${{ needs.setup.outputs.patch }}"
          echo "*** XDK_VERSION_LAST_TAG: ${{ needs.setup.outputs.tag_last_release }}"
          echo "*** XDK_VERSION_THIS_TAG: ${{ needs.setup.outputs.tag_this_release }}"
          echo "*** XDK_VERSION_NEXT_TAG: ${{ needs.setup.outputs.tag_next_release }}"

      - name: Check for Tag
        run: |          
          echo "Checking for tag ${{ needs.setup.outputs.tag_this_release }}"
          git tag -l ${{ needs.setup.outputs.tag_this_release }}
          existing_tags=$?        
          if [[ $existing_tags -eq 0 ]]; then
            echo "ERROR: Tag for this release already exists $tag"
            exit 1
          fi
          echo "*** Tag ${{ needs.setup.outputs.tag_this_release }} does not exist yet; proceeding with buuild."

      - name: Forbid merges
        run: |
          echo "TODO: Here we need to check whether someone has added merges since we last tagged the release."
          # (and fail)

      - name: Execute Gradle installDist
        run: ./gradlew ${{ env.gradle_options }} installDist

      - name: Execute Gradle manualTest sanity checks
        if: ${{ false }}
        run: |
          ./gradlew ${{ env.gradle_options }} manualTests:runXtc
          ./gradlew ${{ env.gradle_options }} manualTests:runOne -PtestName=TestMisc
          ./gradlew ${{ env.gradle_options }} manualTests:runTwoTestsInSequence
          ./gradlew ${{ env.gradle_options }} manualTests:runParallel

      - name: Publish XDK Snapshot
        if: ${{ needs.setup.output.snapshot == 'true' }}
        env:
          ORG_XTCLANG_REPO_GITHUB_USER: xtclang-bot
          ORG_XTCLANG_REPO_GITHUB_TOKEN: ${{ secrets.ORG_XTCLANG_GITHUB_MAVEN_PACKAGE_REPOSITORY_READ_WRITE }}
        run: |
          echo "******************** XDK_VERSION Publishing SNAPSHOT: ${{ needs.setup.outputs.xdk_version  }}"
          ./gradlew ${{ env.gradle_options }} publishRemoteSnapshot

      - name: Publish XDK Release Artifact
        if: ${{ needs.setup.output.snapshot != 'true' }}
        env:
          ORG_XTCLANG_REPO_GITHUB_USER: xtclang-bot
          ORG_XTCLANG_REPO_GITHUB_TOKEN: ${{ secrets.ORG_XTCLANG_GITHUB_MAVEN_PACKAGE_REPOSITORY_READ_WRITE }}
        run: |
          echo "******************* XCK_VERSION PUBLISHING RELEASE"
          all_tags=$(git tag --list)
          echo "ALL TAGS: $all_tags"
          echo "NEW TAG: $tagnew"
#          if [ ${{ steps.check-tag.outputs.exists }} ]; then
#            echo "FAILURE. Tag exists; tag '$tagnew' created from version ${{ needs.setup.outputs.version }} as already in use."
#            exit 1
#          else
#              echo "SUCCESS. We may proceeed with tag: ${{ steps.check-tag.outputs.exists }}"
#          fi
          
          #echo "*** TAGGING RELEASE: ${{ needs.setup.outputs.tagnew }}"
          #git tag --annotate $tagnew HEAD -am "XDK Release: $tagnew"
          #git tag --list
          #echo "*** TAGGED RELEASE $tagnew"  
          #./gradlew ${{ env.gradle_options }} publishRemoteRelease
          
          # Now we know it's a release and ith as tag that hasn't been used to staap this verison before.
          # Build the master release and publish it.
          # Create a branch for the next version update. From a release it goes from a.b.c to a.b.(c + 1)-SNAPSHOT
          # Modify version file accordingly, commit and create a pull request for the branch to go into master.
          # Maybe manually merge it, but could be dangerous.
          # TODO: Think about release branches.