#
# GitHub workflow for publishing Maven snapshot artifacts
#
# This workflow publishes Maven snapshots to GitHub Packages.
# It triggers automatically on master after CI completes, or can be manually triggered.
#
name: Publish Maven Snapshot

permissions:
    contents: read
    packages: write
    actions: read

on:
    # Automatic trigger after CI completes on master
    workflow_run:
        workflows: ["VerifyCommit"]
        types: [completed]
        branches: [master]

    # Manual trigger from any branch
    workflow_dispatch:

jobs:
    publish-maven:
        name: Publish Maven artifacts
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

        steps:
            - name: Fetch Sources
              uses: actions/checkout@v5

            - name: Get versions
              id: versions
              uses: ./.github/actions/get-versions

            - name: Setup XVM Build Environment
              uses: ./.github/actions/setup-xvm-build
              with:
                  java-version: ${{ steps.versions.outputs.java-version }}
                  java-distribution: ${{ steps.versions.outputs.java-distribution }}
                  gradle-version: ${{ steps.versions.outputs.gradle-version }}
                  cache-read-only: false
                  enable-debug: false

            - name: Publish Maven snapshots
              env:
                  GITHUB_ACTOR: ${{ github.actor }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GRADLE_PUBLISH_KEY: ${{ secrets.ORG_XTCLANG_GRADLE_PLUGIN_PORTAL_PUBLISH_KEY }}
                  GRADLE_PUBLISH_SECRET: ${{ secrets.ORG_XTCLANG_GRADLE_PLUGIN_PORTAL_PUBLISH_SECRET }}
                  ORG_GRADLE_PROJECT_github_actor: ${{ github.actor }}
                  ORG_GRADLE_PROJECT_github_token: ${{ secrets.GITHUB_TOKEN }}
                  SIGNING_KEY: ${{ secrets.ORG_XTCLANG_SIGNING_KEY }}
                  SIGNING_KEYID: ${{ secrets.ORG_XTCLANG_SIGNING_KEY_ID }}
                  SIGNING_PASSWORD: ${{ secrets.ORG_XTCLANG_SIGNING_PASSWORD }}
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_XTCLANG_MAVEN_CENTRAL_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_XTCLANG_MAVEN_CENTRAL_PASSWORD }}
                  GRADLE_OPTS: ${{ steps.versions.outputs.gradle-jvm-opts }}
              run: |
                  echo "📦 Publishing Maven snapshot artifacts to GitHub Packages..."
                  ./gradlew ${{ steps.versions.outputs.gradle-options }} publish --info
                  echo "✅ Maven snapshots published"

            - name: Clean up old XDK package versions (keep 50 newest)
              if: success()
              uses: actions/delete-package-versions@v5
              with:
                  package-name: 'org.xtclang.xdk'
                  package-type: 'maven'
                  min-versions-to-keep: 50
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Clean up old Plugin package versions (keep 50 newest)
              if: success()
              uses: actions/delete-package-versions@v5
              with:
                  package-name: 'org.xtclang.xtc-plugin'
                  package-type: 'maven'
                  min-versions-to-keep: 50
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Clean up old Plugin Marker package versions (keep 50 newest)
              if: success()
              uses: actions/delete-package-versions@v5
              with:
                  package-name: 'org.xtclang.xtc-plugin.org.xtclang.xtc-plugin.gradle.plugin'
                  package-type: 'maven'
                  min-versions-to-keep: 50
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Summary
              if: success()
              run: |
                  echo "### ✅ Maven Snapshots Published" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "Published to GitHub Packages:" >> $GITHUB_STEP_SUMMARY
                  echo "- **Version:** ${{ steps.versions.outputs.xdk-version }}" >> $GITHUB_STEP_SUMMARY
                  echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY
                  echo "**Published artifacts:**" >> $GITHUB_STEP_SUMMARY
                  echo "- XDK distribution" >> $GITHUB_STEP_SUMMARY
                  echo "- javatools JAR" >> $GITHUB_STEP_SUMMARY
                  echo "- Gradle plugin" >> $GITHUB_STEP_SUMMARY
