name: 'Setup XVM Project'
description: 'Complete XVM project setup: checkout sources, extract versions, and optionally setup build environment'

inputs:
    setup-build:
        description: 'Setup Java and Gradle build environment (set false for metadata-only jobs)'
        required: false
        default: 'true'
    cache-read-only:
        description: 'Set Gradle cache to read-only mode (only used if setup-build is true)'
        required: false
        default: 'false'
    checkout-depth:
        description: 'Checkout depth (1 for shallow clone, 0 for full history)'
        required: false
        default: '1'
    enable-debug:
        description: 'Enable debug logging for Gradle and setup actions'
        required: false
        default: 'false'

outputs:
    java-version:
        description: 'Java version from version.properties'
        value: ${{ steps.versions.outputs.java-version }}
    xdk-version:
        description: 'XDK version from version.properties'
        value: ${{ steps.versions.outputs.xdk-version }}
    gradle-version:
        description: 'Gradle version from gradle-wrapper.properties'
        value: ${{ steps.versions.outputs.gradle-version }}
    java-distribution:
        description: 'Java distribution to use (temurin)'
        value: ${{ steps.versions.outputs.java-distribution }}
    gradle-options:
        description: 'Standard Gradle command line options'
        value: ${{ steps.versions.outputs.gradle-options }}
    gradle-jvm-opts:
        description: 'Standard Gradle JVM options (GRADLE_OPTS)'
        value: ${{ steps.versions.outputs.gradle-jvm-opts }}

runs:
    using: 'composite'
    steps:
        - name: Fetch Sources
          uses: actions/checkout@v5
          with:
              fetch-depth: ${{ inputs.checkout-depth }}

        - name: Get versions
          id: versions
          uses: ./.github/actions/get-versions

        - name: Setup XVM Build Environment
          if: ${{ inputs.setup-build == 'true' }}
          uses: ./.github/actions/setup-xvm-build
          with:
              java-version: ${{ steps.versions.outputs.java-version }}
              java-distribution: ${{ steps.versions.outputs.java-distribution }}
              gradle-version: ${{ steps.versions.outputs.gradle-version }}
              cache-read-only: ${{ inputs.cache-read-only }}
              enable-debug: ${{ inputs.enable-debug }}

branding:
    icon: 'package'
    color: 'purple'
